<div id="basket-container-wrapper">
	<div id="basket-container" class="container clearfix">
		<div class="row">
			<div class="col-md-8">
				<div class="row">
					<div class="col-md-12 clearfix">
						<h1 class="fl">Giỏ hàng của tôi</h1>
						<a style="float: right;" href="/thuc-don" class="basket-continue-shopping button minibutton checkout-submit secondary span6">Tiếp tục mua hàng</a>
					</div>	
					<?php $totalPriceOrder = 0;?>				
					<div class="col-md-12">
						<?php if(!empty($this->arrayReturn[TYPE_DISH])){?>
						<div class="basket-order-items">
							<div class="basket-order-items-header">
								<h4 class="pull-left basket-order-items-header">Thông tin món ăn</h4>
							</div>
							<table class="table basket-order-items-table text-center">
								<thead class="basket-order-items-table-head">
									<tr>
										<th class="text-left">Món ăn</th>
										<th class="basket-table-price">Giá</th>
									</tr>
								</thead>
								<tbody class="basket-order-items-body">
									<?php foreach($this->arrayReturn[TYPE_DISH] as $item){?>
									<tr>
										<td class="basket-order-item-name text-left">
											<div class="basket-thumbnail-image">
												<img style="left:0px;width:75px;height:75px" alt="<?php echo $item['name']?>" class="basket-order-item-name-image" src="<?php echo $item['image'];?>">
											</div>
											<div class="cart-item-title"><?php echo $item['name']?></div>
											<div class="basket-light-text">Số lượng: 
												<select style="width:50px;" onchange="cart.updateQuantityItem(this)">
													<?php for($i = 1; $i <= 10;$i++){?>
													<option value="<?php echo $i?>" <?php if($i == $item['quantity']) echo 'selected';?>><?php echo $i;?></option>
													<?php }?>
												</select><br >
												<a href="javascript:void(0)" class="basket-order-item-remove-link" data-item-type="<?php echo $item['type']?>" data-item-id="<?php echo $item['id']?>" data-item-price="<?php echo $item['price']?>" data-item-quantity="<?php echo $item['quantity']?>" onclick="cart.deleteItemCart(this)" data-item-more-info="<?php echo $item['more_info']?>" data-item-quantity-array="">Loại bỏ</a>
											</div>
										</td>
										<td class="basket-order-item-price"><span class="item_price_cart"><?php echo My_Zend_Globals::numberFormat($item['price']*$item['quantity'])?></span> VNĐ</td>
									</tr>	
									<?php $totalPriceOrder+= ($item['price']*$item['quantity']);?>
									<?php }?>							
								</tbody>
							</table>                            
						</div>
						<?php }?>
						<?php if(!empty($this->arrayReturn[TYPE_INGREDIENT])){?>
						<div class="basket-order-items">
							<div class="basket-order-items-header">
								<h4 class="pull-left basket-order-items-header">Thông tin nguyên liệu</h4>
							</div>
							<table class="table basket-order-items-table text-center">
								<thead class="basket-order-items-table-head">
									<tr>
										<th class="text-left">Tên nguyên liệu</th>
										<th class="basket-table-price">Giá</th>
									</tr>
								</thead>
								<tbody class="basket-order-items-body">
									<?php foreach($this->arrayReturn[TYPE_INGREDIENT] as $item){?>
									<tr>
										<td class="basket-order-item-name text-left">
											<div class="basket-thumbnail-image">
												<img style="left:0px;width:75px;height:75px" alt="<?php echo $item['name']?>" class="basket-order-item-name-image" src="<?php echo $item['image'];?>">
											</div>
											<div class="cart-item-title"><?php echo $item['name']?></div>
											<div class="basket-light-text">Số lượng: 
												<select style="width:50px;" onchange="cart.updateQuantityItem(this)">
													<?php for($i = 1; $i <= 10;$i++){?>
													<option value="<?php echo $i?>" <?php if($i == $item['quantity']) echo 'selected';?>><?php echo $i;?></option>
													<?php }?>
												</select><br >
												<a href="javascript:void(0)" class="basket-order-item-remove-link" data-item-type="<?php echo $item['type']?>" data-item-id="<?php echo $item['id']?>" data-item-price="<?php echo $item['price']?>" data-item-quantity="<?php echo $item['quantity']?>" onclick="cart.deleteItemCart(this)" data-item-more-info="<?php echo $item['more_info']?>" data-item-quantity-array="">Loại bỏ</a>
											</div>
										</td>
										<td class="basket-order-item-price"><span class="item_price_cart"><?php echo My_Zend_Globals::numberFormat($item['price']*$item['quantity'])?></span> VNĐ</td>
									</tr>	
									<?php $totalPriceOrder+= ($item['price']*$item['quantity']);?>
									<?php }?>							
								</tbody>
							</table>                            
						</div>
						<?php }?>
						<?php if(!empty($this->arrayReturn[TYPE_GIFT])){?>
						<div class="basket-order-items">
							<div class="basket-order-items-header">
								<h4 class="pull-left basket-order-items-header">Phiếu quà tặng</h4>
							</div>
							<table class="table basket-order-items-table text-center">
								<thead class="basket-order-items-table-head">
									<tr>
										<th class="text-left">Loại phiếu</th>
										<th style="text-align:center">Loại giao</th>
										<th style="text-align:center">Người nhận</th>
										<th style="text-align:center" class="basket-table-price">Giá</th>
									</tr>
								</thead>
								<tbody class="basket-order-items-body">
									<?php foreach($this->arrayReturn[TYPE_GIFT] as $item){?>
									<tr>
										<td class="basket-order-item-name text-left">
											<div class="basket-thumbnail-image">
												<i style="left:0px;" class="icon-giftcard-large basket-order-item-name-image"></i>
											</div>
											<div class="cart-item-title mobile-hidden"><?php echo $item['name']?></div>
											<div class="basket-light-text">
												<a href="javascript:void(0)" class="basket-order-item-remove-link" data-item-type="<?php echo $item['type']?>" data-item-id="<?php echo $item['id']?>" data-item-name="<?php echo $item['name']?>" data-item-quantity="<?php echo $item['quantity']?>" onclick="cart.deleteItemCart(this)" data-item-more-info="<?php echo $item['more_info']?>" data-item-quantity-array="<?php echo $item['str_quantity']?>">Loại bỏ</a>
											</div>
										</td>
										<td style="text-align:center">Gửi email</td>
										<td style="text-align:center;color: #a0a0a0;font-size:.8em;">
											<div><?php echo $item['receiver_name']?><br><?php echo $item['receiver_email']?></div>
										</td>
										<td class="basket-order-item-price"><span class="item_price_cart"><?php echo My_Zend_Globals::numberFormat($item['price']*$item['quantity'])?></span> VNĐ</td>
									</tr>
									<?php $totalPriceOrder+= ($item['price']*$item['quantity']);?>
									<?php }?>
								</tbody>
							</table>                            
						</div>
						<?php }?>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="basket-order-summary-container">
					<ul class="basket-alerts">
					</ul>
					<div class="basket-order-summary">
						<div class="basket-order-summary-inner">
							<h4 class="text-center">Giá trị đơn hàng</h4>

							<div class="basket-order-summary-item clearfix">
								<span class="pull-left">Tổng cộng</span>
								<span class="pull-right total_price_order"><?php echo My_Zend_Globals::numberFormat($totalPriceOrder);?> VNĐ</span>
							</div>

							<div class="basket-order-summary-item clearfix">
								<span class="fl">Phí vận chuyển</span>
								<span class="fr shipOrderPrice"><?php echo !empty($this->shippingCost)?My_Zend_Globals::numberFormat($this->shippingCost).' VNĐ':'Miễn phí';?></span>
							</div>

							<div class="basket-order-summary-item basket-order-summary-item-promo">
								<p class="basket-order-summary-item-link" style="cursor:pointer"><span class="basket-order-summary-item-promo-arrow">►</span> Bạn có mã khuyến mãi?</p>
								<form class="simple-form form-in-cart" style="display:none">
									<div class="promo-code-fields">
										<div class="row clearfix">
											<div class="input col-md-8">
												<input type="text" value="" size="" placeholder="Mã khuyến mãi" name="promotion_code" id="promotion_code">
											</div>
											<div class="col-md-4">
												<a class="button" href="javascript:void(0)" id="apply_promotion_code" style="width: 80px;">Áp dụng</a>
											</div>
										</div>
									</div>
								</form>
							</div>

							<div class="basket-order-summary-item basket-order-summary-item-total">
								<span class="pull-left">Tổng cộng</span>
								<span class="pull-right"><span class="total_price_order_final"><?php echo My_Zend_Globals::numberFormat($totalPriceOrder);?></span> VNĐ</span>
							</div>

						</div>
					</div>
					<a class="button" href="<?php echo BASE_URL.'/checkout.html';?>">Tiến hành thanh toán</a>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	cart.shippingCost = <?php echo $this->shippingCost;?>;
	$('.basket-order-summary-item-link').click(function(){
		$('.form-in-cart').toggle();
	});
</script>