<div id="main-content">
	<h1 class="page-title">Thư viện bài viết: Tháng <?php echo $this->month?> - <?php echo $this->year;?></h1>
	<div class="breadcrumbs-wrapper clearfix">
		<ul class="breadcrumbs">
			<li><span><a href="/blog">Trang chủ</a></span></li>
			<li><span class="current"><?php echo $this->year?></span></li>
			<li <?php if($this->page == 1 || empty($this->articles)){ echo 'class="lastcrumb"';}?>><span class="current"><?php echo $this->month?></span></li>
			<?php if($this->page > 1){?>
			<li class="lastcrumb"><span class="current">Trang <?php echo $this->page?></span></li>
			<?php }?>
		</ul>
	</div>
	<div class="page-content">
		<ul class="news-block-columns-2 clearfix">
			<?php if(!empty($this->articles)){?>
			<?php foreach($this->articles as $article){?>
			<li class="clearfix">
				<div class="news-image-container">
					<a title="<?php echo $article['title']?>" href="<?php echo Article::articleUrl($article);?>"><img alt="<?php echo $article['title']?>" style="width:315px;height:209px" class="img-responsive" alt="" src="<?php echo $article['picture']?>"></a>
				</div>
				<h3 class="news-title"><a title="<?php echo $article['title']?>" href="<?php echo Article::articleUrl($article);?>"><?php echo My_Zend_Globals::cutString($article['title'], 0, 50);?></a><span>Ngày <?php echo date('j', $article['created_date'])?>, Tháng <?php echo date('n', $article['created_date'])?> - <?php echo date('Y', $article['created_date'])?></span></h3>
				<p><?php echo My_Zend_Globals::cutString($article['description'], 0, 120);?></p>
			</li>
			<?php }}else{?>
			<li class="clearfix">
				Hiện không có bài viết nào
			</li>
			<?php }?>
		</ul>
		<div class="clear"></div>
		<?php if($this->totalPage > 1){?>
		<div class="pagination-wrapper">
			<?php $nextPage = $this->page + 1;
				  $prevPage = $this->page - 1;
			?>
			<p class="clearfix">
				<?php if($this->totalPage > $this->page){?>
				<span class="fl"><a href="<?php echo $this->canonicalUrl.'?page='.$nextPage;?>">← Bài viết cũ hơn</a></span>
				<?php }?>
				<?php if($this->page > 1){?>
				<span class="fr"><a href="<?php echo $this->canonicalUrl.'?page='.$prevPage;?>">Bài viết mới hơn →</a></span>
				<?php }?>
			</p>
		</div>
		<?php }?>
	</div>
</div>