<section class="about-page">
	<div class="container clearfix">
		<div class="row nav-secondary-container clearfix">
			<div class="col-md-12">
				<h1 class="nav-secondary-title">Về chúng tôi</h1>
				<ul id="standard-nav" class="nav-secondary" role="tablist">
					<li class="active"><a href="/about-us.html?content=our-mission" data-section="our-mission" data-title="Nhiệm vụ của chúng tôi">Nhiệm vụ của chúng tôi</a></li>
					<li><a href="/about-us.html?content=team-page" data-section="team-page" data-title="Đội ngũ nhân viên">Đội ngũ nhân viên</a></li>
					<li><a href="/about-us.html?content=careers-page" data-section="careers-page" data-title="Cơ hội nghề nghiệp">Cơ hội nghề nghiệp</a></li>
				</ul>
			</div>
		</div>
		
		<div class="tab-content">
			<div id="tab-01" class="tab-pane fade about-content our-mission active">
				<div class="row about-row clearfix">
					<div class="col-md-4">
						<h2 class="our-mission-lead">We are making it easy for folks to eat and live better. Hear a little bit more about why we love Plated by watching our video!</h2>
					</div>
					<div class="col-md-8">
						<div class="video-wrapper">
							<iframe src="//player.vimeo.com/video/68390755?title=0&amp;byline=0&amp;portrait=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
						</div>
					</div>
				</div>
				<div class="row our-mission-copy clearfix">
					<div class="col-md-4">
						<h3>Quality</h3>
						<img class="img-responsive" src="<?php echo $this->layout()->_general['static']['path'];?>/images/about_01.jpg" alt="Quality">
						<p>Great recipes call for great ingredients. That means sustainably sourced seafood, a generous helping of seasonal fruits and vegetables, and meat raised without antibiotics or added hormones. We avoid processed and artificial foods, because quite simply, the whole and healthful stuff tastes better.</p>
					</div>
					<div class="col-md-4">
						<h3>Convenience</h3>
						<img class="img-responsive" src="<?php echo $this->layout()->_general['static']['path'];?>/images/about_02.jpg" alt="Convenience">
						<p>We recognize that meal planning and shopping are often roadblocks for getting good food on your plate each week. We’re committed to sidestepping the hassle with pre-portioned ingredients and easy-to-follow recipes delivered fresh to your door.</p>
					</div>
					<div class="col-md-4">
						<h3>Community</h3>
						<img class="img-responsive" src="<?php echo $this->layout()->_general['static']['path'];?>/images/about_03.jpg" alt="Community">
						<p>We enjoy all the bells and whistles of modernity, but we still think there’s nothing like cooking to bring people together. We also prioritize the connection between local farms and consumers, bringing premium meats, seafood and produce to your dinner table. (You know, where it belongs.)</p>
					</div>
				</div>
			</div>

			<div id="tab-02" class="tab-pane fade about-content team-page">
				<div class="row clearfix">
					<div class="col-md-10 col-md-offset-1">
						<div class="team-members-container">
							<div class="team-member">
								<img class="img-responsive" alt="Jessica Nebbeling" src="<?php echo $this->layout()->_general['static']['path'];?>/images/pic_person.jpg">
								<div class="team-member-overlay"></div>
								<div class="team-member-details">
									<h4>Patrick McGee</h4>
									<p>Software Engineer</p>
								</div>
							</div>
							<div class="team-member">
								<img class="img-responsive" alt="Jessica Nebbeling" src="<?php echo $this->layout()->_general['static']['path'];?>/images/pic_person.jpg">
								<div class="team-member-overlay"></div>
								<div class="team-member-details">
									<h4>Nicole Drummond</h4>
									<p>Human Resources Generalist</p>
								</div>
							</div>
							<div class="team-member">
								<img class="img-responsive" alt="Jessica Nebbeling" src="<?php echo $this->layout()->_general['static']['path'];?>/images/pic_person.jpg">
								<div class="team-member-overlay"></div>
								<div class="team-member-details">
									<h4>Nicholas Karrat</h4>
									<p>Senior Vice President, Marketing</p>
								</div>
							</div>
							<div class="team-member">
								<img class="img-responsive" alt="Jessica Nebbeling" src="<?php echo $this->layout()->_general['static']['path'];?>/images/pic_person.jpg">
								<div class="team-member-overlay"></div>
								<div class="team-member-details">
									<h4>Heidi Knight</h4>
									<p>Customer Experience Associate</p>
								</div>
							</div>
							<div class="team-member">
								<img class="img-responsive" alt="Jessica Nebbeling" src="<?php echo $this->layout()->_general['static']['path'];?>/images/pic_person.jpg">
								<div class="team-member-overlay"></div>
								<div class="team-member-details">
									<h4>Eric Burd</h4>
									<p>Senior Vice President, Product</p>
								</div>
							</div>
							<div class="team-member">
								<img class="img-responsive" alt="Jessica Nebbeling" src="<?php echo $this->layout()->_general['static']['path'];?>/images/pic_person.jpg">
								<div class="team-member-overlay"></div>
								<div class="team-member-details">
									<h4>Eric Burd</h4>
									<p>Senior Vice President, Product</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div id="tab-03" class="tab-pane fade about-content careers-page">
				<div class="row clearfix">
					<div class="col-md-12">
						<div id="careers">
							<h1>Work at Plated</h1>
							<h2 class="lead text-center">We're changing the way America eats and re-connecting people to their food, one plate at a time. Join us! </h2>
							<div class="resumator-basic-widget">
								<div class="resumator-jobs-text">
									<div class="resumator-department-heading">Customer Experience</div>
									<div class="resumator-jobs-text">
										<div class="resumator-job-title">Full-Time Customer Experience Associate</div>
										<div class="resumator-job-info"><span class="resumator-job-location">Location: </span>United States</div>
										<div class="resumator-job-view-details"><a href="#" class="resumator-job-link">+ View details</a></div>
									</div>
								</div>
							</div>
							<div class="resumator-basic-widget">
								<div class="resumator-jobs-text">
									<div class="resumator-department-heading">Senior Web Designer</div>
									<div class="resumator-jobs-text">
										<div class="resumator-job-title">Full-Time Customer Experience Associate</div>
										<div class="resumator-job-info"><span class="resumator-job-location">Location: </span>United States</div>
										<div class="resumator-job-view-details"><a href="#" class="resumator-job-link">+ View details</a></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<script>
var loadSection = function(t) 
{
    $(".about-content").hide();
    $('.about-content').removeClass('in');
    $(".about-page #standard-nav li").removeClass("active");
    $(".about-page #standard-nav").find("[data-section='" + t + "']").parent().addClass("active");
    $(".about-content." + t).fadeIn();
    $(".about-content." + t).addClass('in');
};
var tab = "<?php echo $_GET['content']?>";
	loadSection(tab);

$("#standard-nav a").click(function(t) 
{
	var e = $(this).data("section");
        i = $(this).data("title");
        n = {
            content: e
        };
    history.pushState(n, i, "?content=" + e);
});
</script>