<section class="home-wrapper">
	<div class="banwis-container">
		<div class="banwis-overlay"></div>
		<div class="home-featured-image" style="background-image:url(<?php echo $this->layout()->_general['static']['path'];?>/images/banner_home.jpg)"></div>
	</div>
	<div class="home-content">
		<div class="container">
			<span class="headline hidden-sm hidden-xs">Việc ăn ngon trở nên dễ dàng hơn</span>
			<span class="headline visible-sm visible-xs">Việc ăn ngon<br>trở nên dễ dàng hơn</span>
			<h4 class="hidden-sm hidden-xs">Nguyên liệu tươi và các món ăn được thiết kế bắt mắt, cung cấp mỗi ngày</h4>
			<h4 class="visible-sm visible-xs">Nguyên liệu tươi và các món ăn được thiết kế bắt mắt, cung cấp mỗi ngày</h4>
			<div class="row text-center">
				<a class="home-button learn-more" href="<?php echo BASE_URL?>/cach-thuc-van-hanh.html">Tìm hiểu thêm</a>
				<a class="home-button btn-orange" href="<?php echo BASE_URL?>/thuc-don">Mua ngay</a>
			</div>
		</div>
	</div>
</section>
<div class="home-with-thought text-center">
	<img src="<?php echo $this->layout()->_general['static']['path'];?>/images/ico_spec.png" alt="Fwt-icon@2x">
</div>
<div class="home-bottom-with-thought">
	<div class="container clearfix">
		<div class="row text-center clearfix">
			<div class="obj-bottom col-md-4">
				<img src="<?php echo $this->layout()->_general['static']['path'];?>/images/ico_1.png" alt="Cow-icon@2x">
				<h4>KHÔNG DÙNG KHÁNG SINH VA HORMON TĂNG TRƯỞNG</h4>
				<p>Chúng tôi cam kết chất lượng về nguồn thực phẩm. Đảm bảo không dùng thuốc kháng sinh hoặc hóc môn tăng trưởng gây hại cho sức khỏe.</p>
			</div>
			<div class="obj-bottom col-md-4">
				<img src="<?php echo $this->layout()->_general['static']['path'];?>/images/ico_2.png" alt="Fish-icon@2x">
				<h4>THU MUA HẢI SẢN TRONG NƯỚC</h4>
				<p>Nguồn hải sản mà chúng tôi cung cấp từ nguồn tin cậy. Đảm bảo chất lượng về độ lạnh trong suốt quá trình vận chuyển và đóng gói. Đảm bảo hàng luôn tươi ngon.</p>
			</div>
			<div class="obj-bottom col-md-4">
				<img src="<?php echo $this->layout()->_general['static']['path'];?>/images/ico_3.png" alt="Produce-icon@2x">
				<h4>RAU CỦ QUẢ TƯƠI, THEO MÙA</h4>
				<p>Các thực đơn sẽ được thiết kế dựa trên loại rau củ quả tươi theo từng mùa trong năm được chọn lựa từ những nhà cung cấp có uy tín trong nước.</p>
			</div>
		</div>
		<div class="row text-center clearfix visible-sm visible-xs">
			<a class="home-button learn-more" href="<?php echo BASE_URL?>/cach-thuc-van-hanh.html">Tìm hiểu thêm</a>
			<a class="home-button btn-orange" href="<?php echo BASE_URL?>/thuc-don">Mua ngay</a>
		</div>
	</div>
</div>