<section id="mass-header">
	<section class="container content clearfix">
		<div class="row show-grid">
			<div class="col-md-12 clearfix">
				<div class="privacy">
					<h2>Ucancook&trade; Chính sách bảo vệ thông tin cá nhân người tiêu dùng</h2>
					<p><strong>Chào mừng quý khách đến Ucancook.vn!</strong></p>
					<p>Tại Ucancook.vn, tất cả các thông tin hoặc nội dung mang tính riêng tư của Quý khách đều được chúng tôi tuyệt đối tôn trọng và cam kết bảo mật hoàn toàn. Do vậy, Chính sách riêng tư, bảo vệ thông tin cá nhân người tiêu dùng được thể hiện dưới đây sẽ được chúng tôi cam kết thực hiện nhằm bảo vệ tối đa quyền lợi của tất cả Quý khách.</p>
					<p>Chính sách bảo vệ thông tin cá nhân người tiêu dùng sẽ giúp giải thích cụ thể về cách chúng tôi tiếp nhận, sử dụng và cung cấp thông tin cá nhân của người tiêu dùng (chỉ trong những trường hợp thật sự cần thiết). Đồng thời, Chính sách này cũng sẽ trình bày các quy trình thực hiện nhằm bảo mật thông tin cá nhân của quý khách và giải thích quyền lựa chọn của quý khách về việc sử dụng và cung cấp thông tin cá nhân của mình.</p>
					<h3><strong>Mục đích và phạm vi thu thập thông tin</strong></h3>
					<p>Thu thập thông tin là việc hệ thống của chúng tôi ghi nhận và lưu trữ một hoặc nhiều thông tin khác nhau do quý khách chủ động cung cấp khi có nhu cầu mua sắm, đặ hàng trên website Ucancook.vn</p>
					<p>Khi đăng ký tạo Tài khoản mới hoặc tại các thời điểm khác khi sử dụng trang web, khách hàng được yêu cầu cung cấp thông tin cá nhân đầy đủ và hoàn toàn chính xác bao gồm họ tên, địa chỉ email, mật khẩu truy cập Tài khoản, ngày sinh, giới tính, số điện thoại, địa chỉ giao hàng.</p>
					<p>Thông tin cá nhân của Quý khách được thu thập trên cơ sở dữ liệu ghi nhận qua thao tác nhập liệu do Quý khách thực hiện, bao gồm và không giới hạn: họ tên, địa chỉ email, mật khẩu truy cập Tài khoản, ngày sinh, giới tính, số điện thoại, địa chỉ giao hàng, chi tiết thông tin thanh toán, thông tin thẻ và tài khoản ngân hàng...</p>
					<p>Cookies và browser tại thời điểm truy cập của khách hàng được hệ thống ghi nhận tự động nhằm mục đích hỗ trợ bảo mật tài khoản cá nhân của khách hàng cũng như bảo mật hệ thống của trang web.</p>		
					<h3><strong>Phạm vi sử dụng thông tin</strong></h3>
					<p>Chúng tôi sẽ không cho thuê, bán hoặc tiết lộ Thông tin cá nhân của Quý khách cho bên thứ ba không liên quan mà không có sự đồng ý của Quý khách, trừ những điều được nêu trong Chính sách bảo vệ thông tin cá nhân người tiêu dùng này.</p>
					<p>Quá trình thu thập, lưu trữ và xử lý thông tin của Quý khách được ưu tiên nhằm phục vụ cho nhu cầu mua sắm và đặt hàng của Quý khách trên website Ucancook.vn, phục vụ cho quá trình xử lý đơn hàng, giao nhận sản phẩm/hàng hóa mà khách hàng đã đặt mua đến địa chỉ mà khách hàng yêu cầu, cung cấp thông tin liên quan đến sản phẩm/hàng hóa, hỗ trợ quản lý Tài khoản của Quý khách, kiểm soát việc tải dữ liệu từ trang web, nhận diện khách hàng truy cập vào web, cải tiến các chức năng của trang web, hỗ trợ cho những thông báo hoặc giao tiếp cần thiết, nghiên cứu thị trường và phân tích nhu cầu mua sắm.</p>
					<p>Các thông tin khuyến mại hoặc các tin tức về sản phẩm/ hàng hóa được chúng tôi cung cấp trên trang web sẽ chỉ được gửi khi có sự đồng ý của khách hàng, theo các thông tin cá nhân khách hàng đã cung cấp (bao gồm cả email, số điện thoại, địa chỉ v.v.).</p>
					<p>Để phục vụ cho mục đính giao hàng đến Quý khách, chúng tôi có thể sẽ chuyển các thông tin cần thiết của Quý khách gồm họ tên và địa chỉ cho bên thứ 3 (nhà cung cấp hoặc các đơn vị chuyển phát được chỉ định).</p>
					<p>Khi Quý khách thực hiện thao tác thanh toán trực tuyến tại trang web, các thông tin có liên quan bao gồm thông tin thẻ và tài khoản ngân hàng của Quý khách sẽ được xử lý bởi các đại lý mạng lưới quốc tế của chúng tôi. Quý khách chỉ đưa cho chúng tôi hoặc đại lý hoặc website những thông tin chính xác, không gây nhầm lẫn và phải thông báo cho chúng tôi nếu có thay đổi.</p>
					<p>Quý khách cam kết bảo mật thông tin dữ liệu của cá nhân và không được phép tiết lộ cho bên thứ ba bất kỳ. Chúng tôi không chịu bất kỳ trách nhiệm nào cho việc dùng sai mật khẩu nếu đây không phải lỗi của chúng tôi.</p>
					<h3><strong>Thời gian lưu trữ thông tin</strong></h3>
					<p>Thông tin cá nhân của khách hàng mà chúng tôi thu thập được sẽ được chúng tôi lưu giữ trong khoảng thời gian phù hợp với quy định của pháp luật hoặc cho đến khi các thông tin đó còn đáp ứng được mục đích và phạm vi sử dụng được quy định tại Điều Khoản Và Điều Kiện này.</p>
					<h3><strong>Địa chỉ của đơn vị thu thập và quản lý thông tin cá nhân</strong></h3>
					<p style="margin-left:20px">
						Ucancook.vn<br/>  
						21 Nguyễn Văn Tráng, Phường Bến Thành, Quận 1, thành phố Hồ Chí Minh. <br/>
						Tel: +84 8 38 322 794 <br/>
						E-mail: contact@Ucancook.vn												
					<p>
					<h3><strong>Phương tiện và công cụ để người dùng tiếp cận và chỉnh sửa dữ liệu cá nhân của mình</strong></h3>
					<p>Tất cả các thông tin chi tiết về đơn đặt hàng của Quý khách cũng được chúng tôi lưu trữ nhưng sẽ không được công khai trực tiếp. Quý khách hoàn toàn có thể tiếp cận thông tin này (bao gồm chi tiết đơn đặt hàng, những sản phẩm đã mua, chi tiết email, ngân hàng và bản tin mà quý khách đặt theo dõi dài hạn), tiến hành sửa đổi, cập nhật các thông tin cá nhân của mình bằng cách đăng nhập vào tài khoản cá nhân và chọn mục "Chỉnh sửa thông tin cá nhân". Đồng thời, tại mọi thời điểm, khách hàng có quyền yêu cầu chúng tôi thay đổi thông tin cá nhân, thông tin giao hàng bằng cách liên hệ với Bộ phận hỗ trợ Khách hàng của chúng tôi về các yêu cầu của Quý khách qua số điện thoại <strong>+84 8 38 322 794</strong> hoặc gửi mail đến địa chỉ <strong>contact@Ucancook.vn</strong>.</p>
					<p>Khách hàng có đầy đủ các quyền và nghĩa vụ với các thông tin cá nhân đã cung cấp của mình (bao gồm cả Tài khoản, mật khẩu v.v.) và các hoạt động của khách hàng trên trang web sẽ được thực hiện gắn liền với việc sử dụng các thông tin này. Ngay khi phát hiện có bất kỳ dấu hiệu sử dụng trái phép Tài Khoản và mật khẩu cá nhân nào của mình, khách hàng có thể thông báo ngay cho chúng tôi theo số điện thoại <strong>+84 8 38 322 794</strong> hoặc email đến <strong>contact@Ucancook.vn</strong> để được hỗ trợ kịp thời.</p>
					<h3><strong>Cam kết bảo mật thông tin cá nhân khách hàng</strong></h3>
					<p>Quy định tại Điều 6, ĐIỀU KHOẢN VÀ ĐIỀU KIỆN SỬ DỤNG VÀ MUA HÀNG TRÊN WEBSITE THƯƠNG MẠI ĐIỆN TỬ BÁN HÀNG Ucancook.vn, có nội dung như sau:</p>
					<ol style="list-style-type:disc">
						<li>Khi Quý khách thực hiện giao dịch trên trang web, việc bảo mật và đảm bảo an toàn cho tất cả thông tin của khách hàng (bao gồm các thông tin cá nhân, thông tin thanh toán v.v.) được chúng tôi ưu tiên hàng đầu bằng các công vụ và biện pháp hỗ trợ tốt nhất.</li>
						<li>Chúng tôi chỉ sử dụng các thông tin cá nhân chúng tôi nhận được từ Quý khách để phục vụ yêu cầu của Quý khách hoặc các mục đích khác được Quý khách đồng ý mà không chuyển giao, cung cấp, sao chép cho bên thứ ba nào vì mục đích thương mại hoặc bất kỳ mục đích nào khác trái quy định pháp luật.</li>
						<li>Trong trường hợp pháp luật hoặc cơ quan Nhà nước có yêu cầu, chúng tôi có trách nhiệm cung cấp các thông tin cá nhân, thông tin về giao dịch của Quý khách cho cơ quan Nhà nước hoặc tổ chức có liên quan.</li>
						<li>Ngay từ bước đầu tiên đến khi hoàn tất quá trình đặt hàng, thông tin thanh toán của Quý khách sẽ được mã hóa để đảm bảo an toàn. Khi kết thúc quá trình này, chế độ an toàn sẽ tự động thoát.</li>
						<li>Chúng tôi hoàn toàn không chịu bất kỳ trách nhiệm nào, bằng bất kỳ hình thức nào, đối với những thiệt hại hoặc tổn thất, mất mát (nếu có) do Quý khách không tuân thủ các quy định về bảo mật thông tin nêu trong Điều kiện và Điều khoản này (bao gồm bảo mật các thông tin thanh toán quy định tại Mục 4.3).</li>
						<li>Không một cá nhân hoặc tổ chức nào được phép can thiệp hoặc chỉnh sửa, thay đổi cấu trúc dữ liệu trong trang web dù bằng các loại hình công cụ, ứng dụng, chương trình hoặc bất kỳ hình thức nào khác. Tất cả mọi hoạt động tuyên truyền, cổ vũ hoặc phát tán các hành vi bất hợp phát nhằm mục đích xâm nhập, soa chép, lưu trữ hoặc phá hoại các hệ thống dữ liệu trên trang web đều bị nghiêm cấm theo quy định của pháp luật Việt Nam. Chúng tôi sẽ yêu cầu các cơ quan Nhà nước có thẩm quyền xử lý theo quy định của pháp luật các cá nhân hoặc tổ chức có hành vi vi phạm này khi cần thiết.</li>
					</ol>					
					<h3><strong>Quyền truy cập vào những thông tin cá nhân người tiêu dùng</strong></h3>
					<ol style="list-style-type:disc">
						<li>Khách hàng có toàn quyền truy cập, thay đổi, hoặc xóa bỏ thông tin cá nhân bằng cách truy cập trang web Ucancook.vn, đăng nhập và chọn mục “Chỉnh sửa thông tin cá nhân”. Đồng thời, tại mọi thời điểm, khách hàng có quyền yêu cầu chúng tôi thay đổi thông tin cá nhân, thông tin giao hàng bằng cách liên hệ với Bộ phận hỗ trợ Khách hàng của chúng tôi về các yêu cầu của Quý khách qua số điện thoại <strong>+84 8 38 322 794</strong> hoặc gửi mail đến địa chỉ <strong>contact@Ucancook.vn</strong>.</li>
						<li>Trung tâm Chăm sóc Khách Hàng và Bộ phận Tiếp thị được quyền truy cập thông tin của khách hàng ở giới hạn thông báo các chương trình chăm sóc khách hàng, khuyến mãi, thông tin sản phẩm dưới sự cho phép của khách hàng.</li>
						<li>Cơ chế giải quyết khiếu nại: tất cả các khiếu nại liên quan đến vấn đề bảo vệ thông tin cá nhân của người tiêu dùng được điều chỉnh và giải quyết theo Pháp luật Việt Nam. Khách hàng có quyền gửi khiếu nại của mình đến Trung tâm Chăm sóc Khách hàng qua số điện thoại <strong>+84 8 38 322 794</strong> hoặc gửi email đến địa chỉ <strong>contact@Ucancook.vn</strong> để phản ảnh và có quyền được hồi thỏa đáng trong vòng 24 giờ làm việc. Nếu có bất kỳ tranh chấp nào phát sinh từ việc sử dụng trang web hoặc đặt hàng trên trang web này không thể giải quyết bằng phương cách thỏa thuận, tranh chấp này sẽ được giải quyết sau cùng tại Toàn án có thẩm quyền tại Việt Nam.</li>
					</ol>
					<h3><strong>Các lưu ý khác về thông tin cá nhân</strong></h3>		
					<ol style="list-style-type:disc">
						<li>Chúng tôi có thể dùng thông tin cá nhân của Quý khách để nghiên cứu thị trường, phân tích thị hiếu tiêu dùng và chi tiết sẽ được ẩn, chỉ được dùng để thống kê. Quý khách có thể từ chối không tham gia bất cứ lúc nào. Bất kỳ câu trả lời cho khảo sát hoặc thăm dò thị trường mà chúng tôi cần Quý khách làm sẽ không được chuyển cho bên thứ ba. Việc cần thiết duy nhất là cung cấp email của Quý khách nếu Quý khách muốn tham gia. Câu trả lời sẽ được lưu tách riêng với email của Quý khách.</li>
						<li>Quý khách sẽ nhận được thông tin về chúng tôi, về website, các website khác, sản phẩm, bản tin, bất cứ các tin tức nổi bật liên quan đến các công ty nằm trong nhóm hoặc các đối tác kinh doanh. Nếu Quý khách không muốn nhận những thông tin này, vui lòng nhấn vào link từ chối trong bất kỳ email chúng tôi gửi cho Quý khách. Trong vòng 7 ngày nhận chỉ dẫn của Quý khách, chúng tôi sẽ ngừng gửi thông tin.</li>
						<li>Chúng tôi sẽ tiếp tục giấu tên dữ liệu người dùng trên website và sử dụng cho nhiều mục đích khác nhau, bao gồm việc xác định vị trí của người dùng và cách sử dụng các khía cạnh nhất định của website hoặc đường link chứa trong email tới người dùng và cung cấp dữ liệu ẩn danh đó cho bên thứ 3 là nhà xuất bản. Tuy nhiên, dữ liệu này không có khả năng xác định cá nhân.</li>
					</ol>
				</div>
			</div>
		</div>
	</section>
</section>