<section id="mass-header">
	<section class="container content clearfix">
		<div class="row show-grid">
			<div class="col-md-12 clearfix">
				<div class="privacy">
					<h2>Ucancook&trade; Thỏa thuận người dùng</h2>
					<p><strong>Chào mừng quý khách đến Ucancook.vn!</strong>
					</p>
					<p>Chúng tôi là Công ty TNHH UCANCOOK, có trụ sở tại 21 Nguyễn Văn Tráng, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh.</p>
					<p>Ucancook.vn là một website thương mại điện tử do UCANCOOK sở hữu và vận hành. Các sản phẩm trưng bày trên website này sẽ được bán theo các Điều Khoản và Điều Kiện dưới đây (“Điều Khoản và Điều Kiện”). Khi quý khách truy cập trang web này, quý khách cần phải đọc kĩ và chấp thuận Điều Khoản và Điều Kiện trước khi tạo tài khoản và đặt mua các sản phẩm.</p>
					<p>Điều Khoản và Điều Kiện này được kết nối với các tài liệu khác trên trang web, bao gồm các chính sách và hướng dẫn liên quan. Các tài liệu này là một phần không tách rời của Điều Khoản và Điều Kiện. Một khi chấp thuận Điều Khoản và Điều Kiện, Quý Khách cũng chấp thuận các điều kiện và điều khoản khác quy định trong các tài liệu đó.</p>
					<p>Điều Khoản và Điều Kiện có thể được sửa đổi bổ sung tùy theo thời điểm. Bất kì sửa đổi bổ sung nào cũng sẽ được thông báo cho Quý Khách qua địa chỉ email đăng ký trên trang web. Điều Khoản và Điều Kiện sửa đổi sẽ có hiệu lực sau 24 giờ kể từ ngày chúng tôi gửi thông báo và áp dụng cho tác đơn đặt hàng kể từ thời điểm sau 24 giờ đó. Bất kì đơn hàng này được đặt sau ngày công bố Điều Khoản và Điều Kiện sửa đổi sẽ được xem là Quý Khách đã đồng ý với Điều Khoản và Điều Kiện mới đó.</p>
					<h3><strong>HOẶC</strong></h3>
					<p>Bất kì sửa đổi nào sẽ có hiệu lực ngay lập tức kể từ khi Điều Khoản và Điều Kiện sửa đổi được đăng tải trên trang web. Chúng tôi sẽ thông báo về việc sửa đổi tại trang chủ của website trong vòng 7 ngày kể từ ngày công bố. Quý Khách vui lòng kiểm tra bản sửa đổi trước khi đặt mua hàng trên trang web. Bất kì đơn hàng này được đặt sau ngày công bố Điều Khoản và Điều Kiện sửa đổi sẽ được xem là Quý Khách đã đồng ý với Điều Khoản và Điều Kiện mới đó.</p>
					<p>Tại mọi thời điểm, Quý Khách có quyền ngừng sử dụng và không mua sản phẩm trên website này nếu Quý Khách không đồng ý với Điều Khoản và Điều Kiện hoặc bất kì quy tắc, chính sách hoặc các vấn đề khác có liên quan.</p>
					<h3><strong>Định nghĩa</strong></h3>
					<p>Trừ khi được quy định khác trong Điều Khoản và Điều Kiện này, các từ ngữ dưới đây sẽ có nghĩa như sau:</p>
					<ol style="list-style-type:disc">
						<li><strong>"Tài khoản"</strong> là tài khoản Quý Khách đăng ký và đăng nhập vào để mua hàng hóa trên trang web.</li>
						<li><strong>"Ngày làm việc"</strong> là các ngày trong tuần trừ Chủ Nhật và các ngày Lễ theo quy định của pháp luật Việt Nam.</li>
						<li><strong>"Ngày làm việc của ngân hàng"</strong> là các ngày trong tuần trừ thứ 7, chủ nhật và các ngày Lễ theo quy định của pháp luật Việt Nam.</li>
						<li><strong>"Giỏ hàng"</strong> là danh sách các món hàng mà Quý Khách đã chọn và dự định đặt mua, bao gồm số lượng sản phẩm và giá trị đơn hàng. Quý Khách có thể thay đổi giỏ hàng cho đến khi hoàn thành việc đặt hàng. </li>
						<li><strong>"Quý Khách"</strong> là các cá nhân trong lãnh thổ Việt Nam đủ 18 tuổi hoặc dưới 18 tuổi nhưng có sự giám sát của Cha mẹ hoặc người giám hộ và mua sắm trên trang web của chúng tôi.</li>
						<li><strong>"Mã giảm giá"</strong> là một chuỗi kí tự do chúng tôi thiết lập dùng để trừ vào khoản tiền Quý Khách phải trả khi mua hàng trên trang web.</li>
						<li><strong>"Bất Khả Kháng"</strong> là các sự kiện nằm ngoài tầm kiểm soát của chúng tôi, bao gồm nhưng không giới hạn ở các thiên tai (bão lũ, hạn hán, động đất), các cuộc nổi dậy, bạo động, chiến tranh, các hành vi thù địch, các hoạt động hiếu chiến, các tình trạng khẩn cấp cấp quốc gia, khủng bố, đình công, bệnh dịch, cháy nổ, tai nạn, hệ thống máy móc hư hỏng, hạn chế giao thông, các hành động của bên thứ ba (ví dụ tin tặc), phần mềm của một bên thứ ba có liên quan không hoạt động, gián đoạn trong việc cung cấp các tiện ích công cộng (bao gồm điện, nước, hệ thống viễn thông, internet) và việc thiếu hụt sản phẩm.</li>
						<li><strong>"UCANCOOK"</strong> hay <strong>"chúng tôi"</strong> là Công ty TNHH UCANCOOK có trụ sở tại 21 Nguyễn Văn Tráng, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh.</li>
						<li><strong>"Đơn hàng"</strong> là đơn hàng Quý Khách đặt mua trên trang web để mua các sản phẩm do UCANCOOK bán. Sau khi đơn hàng được UCANCOOK xác nhận, đơn hàng đó sẽ là một hợp đồng ràng buộc Quý Khách và chúng tôi.</li>
						<li><strong>"Xác nhận đơn hàng"</strong> là thư điện tử chúng tôi gửi cho Quý Khách nhằm xác nhận chúng tôi đồng ý cung cấp các sản phẩm cho Quý Khách theo các điều khoản và điều kiện nhất định.</li>
						<li><strong>"Sản phẩm"</strong> là sản phẩm chúng tôi bán trên trang web tùy từng thời điểm.</li>
						<li><strong>"Điều Khoản và Điều Kiện"</strong> hoặc <strong>"T&C"</strong> là điều khoản và điều kiện sử dụng và mua bán trên trang thương mại điện tử Ucancook.vn.</li>
						<li><strong>"Website"</strong> hoặc <strong>"Trang web"</strong> là website Ucancook.vn do UCANCOOK điều hành để bán các sản phẩm cho Quý Khách.</li>
					</ol>					
					<h3><strong>Tạo và quản lý tài khoản của Quý Khách</strong></h3>
					<p>Để mua các sản phẩm trên Ucancook.vn, Quý Khách có thể không cần phải lập tài khoản nhưng miễn là Quý Khách điền đầy đủ thông tin được yêu cầu trong quá trình thanh toán, bao gồm số điện thoại di động của Quý Khách. Tuy nhiên, chúng tôi khuyến  khích tất cả các khách hàng thiết lập một tài khoản riêng để có thể được hưởng đầy đủ các tiện ích và các chương trình khuyến mãi chúng tôi thực hiện tùy từng thời điểm.</p>
					<p>Các cá nhân tại Việt Nam, thỏa mãn các điều kiện dưới đây có thể lập một tài khoản trên Trang web:</p>
					<ol style="list-style-type:disc">
						<li>Đủ 18 tuổi</li>
						<li>Dưới 18 tuổi với sự giám sát của người giám hộ</li>
					</ol>
					<p>Quý Khách có thể theo đường dẫn này để tạo tài khoản. Quý Khách phải đọc và chấp thuận Điều Khoản và Điều Kiện để hoàn thành quá trình lập tài khoản. Chúng tôi khuyến nghị Quý Khách giữ gìn mật khẩu cẩn trọng và không tiết lộ với những người khác. Quý Khách vui lòng ngay lập tức thông báo cho UCANCOOK khi nhận thấy các dấu hiệu truy cập trái phép vào tài khoản của Quý Khách.</p>
					<p>Tài khoản được cấp cho Quý Khách chỉ nhằm mục đích mua bán trên Trang web. Các thông tin cung cấp khi đăng ký tài khoản phải có thật và chính xác trong mọi khía cạnh. Chúng tôi đề nghị Quý Khách nhanh chóng cập nhật thông tin cá nhân khi có sự thay đổi. Quý Khách cũng có thể yêu cầu UCANCOOK giúp đỡ Quý Khách thay đổi các thông tin cá nhân có liên quan này bằng việc trao đổi với Trung Tâm Chăm Sóc Khách Hàng UCANCOOK theo số điện thoại 08 38 322 794.</p>
					<p>UCANCOOK có quyền từ chối đơn hàng hoặc từ chối giao hàng khi phát hiện thông tin Quý Khách cung cấp không đúng và UCANCOOK sẽ không có bất kì trách nhiệm nào đối với các thiệt hại trực tiếp hay gián tiếp gây ra từ việc Quý Khách không tuân thủ quy định này.</p>					
					<h3><strong>Chính sách bảo mật</strong></h3>
					<h3 style="font-size:1.05em"><strong><i>Phạm vi thông tin thu thập</i></strong></h3>
					<p>Khi Quý Khách đăng ký một tài khoản trên Ucancook.vn, UCANCOOK sẽ thu thập các thông tin cá nhân, bao gồm mật khẩu tài khoản, tên đầy đủ, địa chỉ hộp thư điện tử, ngày sinh, giới tính, số điện thoại, địa chỉ giao hàng và các thông tin khác cần có tùy từng thời điểm.</p>
					<p>UCANCOOK cũng sẽ sử dụng lịch sử mua hàng, giá trị giao dịch, điều khoản giao hàng và phương thức thanh toán.</p>
					<h3 style="font-size:1.05em"><strong><i>Mục đích và phạm vi sử dụng thông tin cá nhân</i></strong></h3>					
					<p>Các thông tin đề cập bên trên được thu thập cho chỉ cho một mục đích vận hành quy trình mua bán dựa trên đơn hàng của Quý Khách. Các thông tin này cũng được dùng để hỗ trợ việc quản lý tài khoản của Quý Khách, cải thiện các tính năng trên website hoặc xử lý các trục trặc trong quá trình giao dịch.</p>
					<p>UCANCOOK chú trọng đến việc duy trì mối quan hệ lâu bền với khách hàng. Vì vậy, các thông tin về lịch sử mua hàng cũng như các thông tin cá nhân khác có thể được sử dụng tùy từng thời điểm để xây dựng các chiến dịch hỗ trợ khách hàng và các chương trình khuyến mãi.</p>
					<p>Với sự đồng ý trước của Quý Khách, chúng tôi thỉnh thoảng sẽ gửi thông tin về các chương trình khuyến mãi hoặc các thông tin khác cho Quý Khách thông qua hộp thư điện tử, địa chỉ nhà hoặc số điện thoại.</p>
					<p>Chúng tôi có thể sẽ tiết lộ thông tin của Quý Khách với một bên thứ ba nhằm phục vụ việc giao hàng hoặc thanh toán tiền hàng.</p>
					<h3 style="font-size:1.05em"><strong><i>Lưu trữ và bảo mật thông tin cá nhân</i></strong></h3>								
					<p>Thông tin Quý Khách cung cấp cho chúng tôi sẽ được lưu trữ trong một thời gian nhất định phù hợp với quy định của pháp luật. UCANCOOK cam kết sử dụng các thông tin này cho các mục đích đã nêu bên trên và các mục đích khác đã được Quý Khách đồng ý trước khi sử dụng. UCANCOOK sẽ không sử dụng hay tiết lộ chúng cho bất kì bên thứ ba nào với mục đích thương mại hoặc mục đích phạm pháp nào khác.</p>
					<p>UCANCOOK có thể phải tiết lộ thông tin cá nhân của Quý Khách hoặc thông tin về giao dịch của Quý Khách khi có yêu cầu của cơ quan nhà nước có thẩm quyền.</p>
					<p>UCANCOOK nhận thức rõ tầm quan trọng của việc bảo mật thông tin và vì vậy áp dụng các biện pháp bảo mật tốt nhất. Quý Khách có trách nhiệm tuân thủ đầy đủ các quy tắc về bảo mật để đảm bảo hiệu quả của việc bảo mật này. UCANCOOK sẽ không có trách nhiệm đối với bất kì thiệt hại, mất mát nào gây ra bởi hành vi không tuân thủ của Quý Khách.</p>
					<h3><strong>Tuyên bố và đảm bảo</strong></h3>
					<p>UCANCOOK cam kết rằng:</p>
					<ol style="list-style-type:disc">
						<li>UCANCOOK là một công ty được thành lập và tồn tại hợp pháp và có đầy đủ năng lực và quyền hạn để thực hiện hoạt động kinh doanh tại Việt Nam và trên website ucancook.vn</li>
						<li>UCANCOOK tuân thủ các quy định của pháp luật Việt Nam liên quan đến việc kinh doanh các loại hàng hóa trưng bày trên Trang web, đặc biệt là các quy định liên quan đến an toàn thực phẩm, cạnh tranh, sở hữu trí tuệ và bảo vệ người tiêu dùng.</li>
						<li>UCANCOOK chịu trách nhiệm đối với các sản phẩm của mình, đặc biệt là hàng hóa có khiếm khuyết về nguồn gốc, quy cách, chất lượng không phù hợp với các tiêu chí đã công bố. UCANCOOK có chính sách đổi hoặc trả hàng cho các sản phẩm đã mua nhưng không đạt tiêu chuẩn chất lượng như đã công bố trên Trang web hoặc do lỗi trong quá trình giao dịch.</li>
					</ol>
					<h3><strong>Các hành vi bị cấm khi sử dụng Trang web Ucancook.vn</strong></h3>
					<p>Người dùng không được phép:</p>
					<ol style="list-style-type:disc">
						<li>Nhận xét, đánh giá nhằm công kích, phỉ báng, đe dọa, gây phiền nhiễu người khác hoặc có hành vi thiếu văn hóa với người khác</li>
						<li>Nhận xét về chính trị như tuyên truyền, chống phá, xuyên tạc chính quyền Việt Nam hoặc có các nhận xét, đánh giá mang tính kì thị về tôn giáo, giới tính, sắc tộc, hoặc giai cấp</li>
						<li>Tuyên truyền văn hóa phẩm đồi trụy gây phản cảm hoặc các thông tin trái với quy định pháp luật khác</li>
						<li>Phổ biến các tài liệu hoặc khuyến khích người khác thực hiện hành vi vi phạm pháp luật</li>
						<li>Can thiệp vào quyền sử dụng tài khoản hợp pháp của người dùng khác trên Trang web</li>
						<li>Có hành vi vi phạm pháp luật liên quan đến việc sử dụng internet, mạng viễn thông công cộng hoặc quyền sở hữu trí tuệ</li>
						<li>Tạo các thông tin sai sự thật, giả mạo khách hàng khác hoặc Ban quản lý Trang web</li>
						<li>Can thiệp hay làm gián đoạn đường truyền trên Trang web hoặc các trang web khác được kết nối với Ucancook.vn</li>
						<li>Thực hiện các hành vi khác vi phạm pháp luật Việt Nam</li>
					</ol>
					<p>UCANCOOK có quyền yêu cầu và phối hợp với cơ quan có chức năng để xử lý các hành vi vi phạm pháp luật theo quy định của pháp luật dân sự, pháp luật hình sự và các quy định khác của pháp luật Việt Nam.</p>
					<h3><strong>Quy trình mua bán hàng hóa trên Ucancook.vn</strong></h3>
					<h3 style="font-size:1.05em"><strong><i>Chuyển quyền sở hữu hàng hóa</i></strong></h3>					
					<p>Quyền sở hữu đối với hàng hóa sẽ được chuyển giao từ UCANCOOK sang Quý Khách kể từ khi hàng hóa được xuất kho để giao cho Quý Khách. Quý Khách sẽ chịu các rủi ro về vận chuyển và chịu cước phí vận chuyển. Phí này thường đã được cộng vào giá dịch vụ.</p>
					<h3 style="font-size:1.05em"><strong><i>Chăm sóc khách hàng</i></strong></h3>	
					<p>Để cung cấp dịch vụ tốt nhất cho Quý Khách, chúng tôi xây dựng một đội chăm sóc khách hàng riêng cho Ucancook.vn. Quý Khách có thể liên hệ với Trung tâm Chăm sóc Khách hàng từ <strong style="color:red">8h00am đến 05h00pm từ thứ 2 đến thứ 7</strong>. Công ty sẽ không hoạt động vào các ngày chủ nhật và các ngày lễ theo quy định của Việt Nam. Chúng tôi sẵn lòng hỗ trợ về mặt kỹ thuật trong quá trình giao dịch hoặc giải đáp các thắc mắc liên quan đến chất lượng, quy cách, cách thức bảo quản và hướng dẫn sử dụng các sản phẩm Quý Khách đặt mua.</p>
					<p>Để tạo điều kiện thuận lợi cho việc thanh toán, chúng tôi chấp nhận việc thanh toán bằng nhiều hình thức khác nhau. Quý Khách có thể xem Phương thức và Hướng dẫn Thanh toán để chọn cho mình phương thức thanh toán phù hợp</p>
					<p>Sau khi xác nhận đặt hàng, UCANCOOK sẽ giúp Quý Khách sắp xếp việc giao hàng với bên thứ 3 theo Quy trình Giao hàng cụ thể.</p>
					<p>Chúng tôi cũng áp dụng chính sách đổi trả hàng hóa đã mua trong các trường hợp hợp lý quy định tại Chính sách Đổi trả hàng của chúng tôi.</p>
					<p>Mặc dù chúng tôi luôn mong muốn cung cấp dịch vụ khách hàng tốt nhất cho Quý Khách, chúng tôi không thể đáp ứng tất cả các yêu cầu của Quý Khách hoặc không thể kiểm soát các trường hợp Bất Khả Kháng. Vì vậy, trong phạm vi rộng nhất mà pháp luật cho phép, chúng tôi không có trách nhiệm thực hiện các dịch vụ không được cam kết trong Điều Khoản và Điều Kiện cũng như ở các nội dung khác trên Trang web. UCANCOOK không có trách nhiệm với bất kì mất mát hay thiệt hại nào phát sinh với Quý Khách từ việc truy cập hoặc không thể truy cập được vào Trang web vì bất kì lý do gì, bao gồm nhưng không giới hạn ở việc duy trì website, hệ thống bị hư hỏng, cúp điện hoặc phí sử dụng internet.</p>
					<h3 style="font-size:1.05em"><strong><i>Quyền sở hữu trí tuệ </i></strong></h3>
					<p>Tất cả các quyền sở hữu trí tuệ, đăng kí hay không đăng kí, trên Trang web này, các nội dung thông tin, thiết kế web, bao gồm nhưng không giới hạn ở văn bản, đồ họa, phầm mềm, hình ảnh, video, nhạc, âm thanh, cách thức chọn lựa và sắp xếp, và tất cả các phần mềm lập trình, mã nguồn, và các ứng dụng sẽ thuộc quyền sở hữu của chúng tôi.</p>
					<p>Người dùng không được phép sử dụng các tài sản thuộc quyền sở hữu trí tuệ của chúng tôi cho mục đích thương mại, quảng cáo, giới thiệu hoặc sử dụng, sửa đổi, sao chép hoặc chia sẻ một phần hoặc toàn bộ mà không có sự đồng ý của chúng tôi.</p>
					<p>Bất kì nội dung nào do Quý Khách nhập vào và/ hoặc cung cấp cho chúng tôi trên Trang Web hoặc các trang web khác kết nối với Trang Web, bao gồm nhưng không giới hạn ở câu hỏi, đánh giá, bình luận, đề nghị nhưng không bao gồm các thông tin cá nhân của Quý Khách (sau đây được gọi chung là “Ý Kiến Đóng Góp” sẽ là tài sản độc quyền và duy nhất của chúng tôi và sẽ không được hoàn trả lại cho Quý Khách. Bên cạnh các quyền đối với Ý Kiến Đóng Góp, khi Quý Khách đăng tải bình luận hoặc đánh giá đối với Trang Web, Quý Khách mặc nhiên trao cho chúng tôi quyền sử dụng tên mà Quý Khách dùng khi đánh giá, bình luận hoặc đăng tải nội dung khác. Quý Khách không được phép sử dụng địa chỉ email giả, giả mạo làm người khác hoặc có hành vi khác gây hiểu lầm cho chúng tôi hay các bên thứ ba về nguồn gốc của Ý Kiến Đóng Góp. Chúng tôi có quyền, nhưng không có nghĩa vụ, chỉnh sửa hoặc hủy bỏ các Ý Kiến Đóng Góp</p>					
					<h3><strong>Quyền và nghĩa vụ của Quý Khách</strong></h3>
					<p>Quý Khách có quyền:</p>
					<ol style="list-style-type:disc">
						<li>Thiết lập tài khoản trên Ucancook.vn và mua hàng hóa trên Trang Web với giá cố định nếu Quý Khách đáp ứng được các điều kiện quy định tại <strong>"Tạo và quản lý tài khoản của Quý Khách".</strong></li>
						<li>Yêu cầu Trung tâm Chăm sóc Khách hàng giúp đỡ.</li>
						<li>Gửi thư khiếu nại về các đơn hàng đã đặt.</li>
						<li>Yêu cầu đổi hoặc hoàn trả theo <strong>Chính sách Đổi/ trả hàng hóa.</strong></li>
						<li>Các quyền khác theo pháp luật.</li>
					</ol>
					<p>Quý Khách có nghĩa vụ:</p>
					<ol style="list-style-type:disc">
						<li>Cung cấp thông tin chính xác và chịu trách nhiệm về tính chính xác và chân thực của chúng.</li>
						<li>Quản lý và bảo mật thông tin về tài khoản.</li>
						<li>Nhận kiện hàng nếu niêm phong vẫn còn nguyên vẹn.</li>
						<li>Thanh toán đầy đủ cho các sản phẩm Quý Khách đặt mua và tuân thủ triệt để các quy định liên quan đến bảo mật khi thanh toán qua cổng thông tin điện tử.</li>
						<li>Tuân thủ các quy tắc và cảnh báo khác do UCANCOOK thông báo tùy từng thời điểm.</li>
						<li>Không được sử dụng bất kì ứng dụng, phần mềm, công cụ hoặc bất kì hình thức nào khác để can thiệp, chỉnh sửa, thay đổi cấu trúc dữ liệu của Trang Web.</li>
						<li>Không được sử dụng bất kì nội dung nào trên Trang Web nhằm mục đích thương mại hoặc nhân danh bên thứ ba nào khác mà không có sự đồng ý trước bằng văn bản của UCANCOOK.</li>
						<li>Tuân thủ triệt để các quy định khác của pháp luật.</li>
					</ol>
					<p>Bằng việc đặt mua hàng trên Ucancook.vn, chúng tôi hiểu rằng Quý Khách đã nhận thức đầy đủ và chấp nhận tất cả các rủi ro liên quan đến việc sử dụng máy vi tính hoặc các thiết bị khác khi truy cập Trang Web.</p>
					<h3><strong>Quyền và nghĩa vụ của UCANCOOK</strong></h3>
					<p>Bên cạnh các quyền khác được quy định trong Điều Khoản và Điều Kiện, UCANCOOK có các quyền sau đây:</p>
					<ol style="list-style-type:disc">
						<li>Từ chối đơn hàng của Quý Khách trong trường hợp hết hàng.</li>
						<li>Yêu cầu Quý Khách cung cấp thông tin chính xác khi lập tài khoản, tiến hành thanh toán hoặc các thông tin khác cần thiết cho việc xử lý đơn hàng trên Trang Web.</li>
						<li>Sử dụng các thông tin được cung cấp theo quy định của pháp luật Việt Nam và theo đúng Điều Khoản và Điều Kiện.</li>
						<li>Khóa, tạm ngưng hoặc hủy tài khoản của Quý Khách khi phát hiện có hành vi vi phạm Điều Khoản và Điều Kiện hoặc vi phạm pháp luật Việt Nam</li>
					</ol>
					<p>UCANCOOK có nghĩa vụ:</p>
					<ol style="list-style-type:disc">
						<li>Điều hành Trang Web theo quy định của pháp luật Việt Nam.</li>
						<li>Cung cấp các sản phẩm với đúng tiêu chuẩn chất lượng về an toàn thực phẩm theo quy định của pháp luật.</li>
						<li>Thay thế các sản phẩm bị lỗi theo <strong>Chính sách Đổi/ trả hàng hóa</strong>.</li>
						<li>Bảo mật các thông tin riêng tư theo quy định của pháp luật và <strong>Chính sách bảo mật</strong>.</li>
					</ol>
					<h3><strong>Miễn trừ, từ bỏ và giới hạn trách nhiệm</strong></h3>
					<p>Trong phạm vi tối đa pháp luật cho phép, UCANCOOK không chịu bất kì trách nhiệm nào đối với:</p>
					<ol style="list-style-type:disc">
						<li>Máy vi tính hoặc các thiết bị khác không thích hợp với Trang Web.</li>
						<li>Bất kì thiệt hại trực tiếp hay gián tiếp phát sinh từ các vấn đề về kỹ thuật mà không phải là lỗi trực tiếp của UCANCOOK khi truy cập Trang Web.</li>
						<li>Tắc nghẽn đường truyền truy cập vào Trang Web.</li>
						<li>Bất kì thiệt hại trực tiếp hay gián tiếp phát sinh từ Bất Khả Kháng.</li>
						<li>Bất kì thiệt hại nào gây ra cho máy tính hoặc thiết bị khác của Quý Khách khi truy cập Trang Web.</li>
					</ol>
					<p>Trong mọi trường hợp, mức đền bù sẽ không quá <strong style="color:red">2 lần</strong> giá trị sản phẩm có phát sinh tranh chấp</p>
					<h3><strong>Luật áp dụng và Giải quyết tranh chấp</strong></h3>
					<p>Điều Khoản và Điều Kiện này, cùng với các tài liệu khác trên Trang Web và các giao dịch mua bán sẽ được điều chỉnh theo pháp luật Việt Nam.</p>
					<p>Bất kì khiếu nại hay tranh chấp phát sinh từ hoặc liên quan đến giao dịch trên Trang Web sẽ được giải quyết thông qua thương lượng, hòa giải. Nếu không giải quyết được, vụ việc sẽ được đưa ra giải quyết tại Tòa án nhân dân có thẩm quyền để giải quyết theo pháp luật Việt Nam</p>
				</div>
			</div>
		</div>
	</section>
</section>