<div id="content-listing" style="margin:20px 0 20px 100px">
	<div class="tree-folder">
		<a href="/" class="icon-home"></a>
		<a href="/" class="icon-next">Trang 404</a>
	</div>
	<div class="list">
	<h2 class="cate-title">Trang 404</h2>
	<div style="clear:both"></div>
		<div class="left">
			<h1>Xin lỗi! <span>Trang không tồn tại!</span></h1>				
			<p>Nội dung trang bạn muốn truy cập không tồn tại.</p>				
			<div class="listHeading"><b>Bạn có thể thử:</b></div>
			<ul class="paddedList">
				<li>Kiểm tra lại kết nối website.</li>
				<li><b>Hoặc</b> <a href="<?php echo BASE_URL;?>">Trở về trang chủ.</a>	</li>
				<li><b>Hoặc liên hệ với chúng tôi.</b> <a href="<?php echo BASE_URL;?>/gioi-thieu-ve-phongdodanong.html">Contact Our.</a></li>
			</ul>	
		</div>
	</div><!--End.list-->	
</div>