<div class="module moduletable_style adblock">
	<div class="leomodule">
		<h3 class="moduletitle">
			<span>Facebook</span>
		</h3>
		<div class="fb-container">										
			<div><fb:like-box href="<?php echo FACEBOOK_FANPAGE_URL?>" width="302" colorscheme="light" show_faces="true" stream="false" header="false" height="340"></fb:like-box></div>
		</div>
	</div>
</div>

<div class="adblock">
<!-- Begin Adbrand -->
<script language="javascript" type="text/javascript">
    var adbrand_zoneId = 'va_BBAEF744609AF5E5';
    var adbrand_width  = '300';
    var adbrand_height = '600';
    var adbrand_sizeId = '23';
    var adbrand_typeId = '3';  
</script> 
<script type="text/javascript" src="http://embed.adbrand.net/adbrand.js"></script> 
<!-- End: Adbrand -->
</div>