<div>
	<script type="text/javascript"><!--
	google_ad_client = "ca-pub-0677294388374027";									
	google_ad_slot = "4621415774";
	google_ad_width = 300;
	google_ad_height = 250;
	//-->
	</script>
	<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>																	
</div>
<div style="margin:5px 0;">
	<script type="text/javascript"><!--
	google_ad_client = "ca-pub-0677294388374027";	
	google_ad_slot = "6098148971";
	google_ad_width = 300;
	google_ad_height = 250;
	//-->
	</script>
	<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>																	
</div>