<?php
$this->headLink()
			->appendStylesheet($this->layout()->_general['server']['path'].'/css/ui-lightness/jquery-ui-1.9.2.custom.min.css');

$this->headScript()
		->appendFile($this->layout()->_general['server']['path'].'/js/jquery-ui-1.8.18.custom.min.js')
		->appendFile($this->layout()->_general['server']['path'].'/js/jquery.ui.autocomplete.js')
        ->appendFile($this->layout()->_general['server']['path'].'/js/jquery.validate.pack.js')
        ->appendFile($this->layout()->_general['server']['path'].'/js/tiny_mce/jquery.tinymce.js')
        ->appendFile($this->layout()->_general['server']['path'].'/js/upload.js');        
?>
<div id="content">
    <div class="breadcrumb clearfix">
        <div class="title k2">Thêm bài viết mới</div>       
    </div>
    <div class="clear"></div>   
    <div class="">
        <div class="fdefault posting">
            <form action="" method="post">
                <?php if ($this->message): ?>
                <div class="<?php echo $this->message['type']; ?>"><p><?php echo $this->message['msg']; ?></p></div>
                <?php endif; ?>
                <h3 class="n1">Thông tin cơ bản</h3>
                <div class="group_listing_input">
                    <div class="listing_input hgauto">
                        <div class="post_label_container">
                            <label class="postLabel">Tiêu đề tin:</label>
                        </div>
                        <input name="title" type="text" value="<?php echo $this->escape($this->article['title']); ?>" class="title_text_input" />                       
                    </div>                 
                    <div class="listing_input hgauto">
                        <div class="post_label_container">
                            <label class="postLabel">Danh mục:</label>
                        </div>
                        <select class="medium_text_input" name="category_id" id="category_id">
                            <option value="">Chọn danh  mục</option>
                            <?php
                            foreach ($this->categoryTree as $parent)
                            {
                                echo '<optgroup label="'.$parent['category_name'].'" class="first">';
                                if ($parent['sub'])
                                {
                                    foreach ($parent['sub'] as $sub)
                                    {
                                        echo '<option '.($sub['category_id']==$this->article['category_id']?'selected="selected"':'').' value="'.$sub['category_id'].'" class="second">'.$sub['category_name'].'</option>';
                                    }
                                }
                                echo '</optgroup>';
                            }

                            ?>
                        </select>
                    </div>
                    <div class="listing_input hgauto">
                    	<div class="post_label_container">
                            <label class="postLabel">Hình ảnh:</label>                            
                        </div>
                        <div id="divUpload"></div>            
                        <div id="show_picture" style="margin: 10px 130px"></div>        
                        <input type="hidden" name="picture" id="picture" />
                    </div>
                    <div class="listing_input hgauto">
                        <div class="post_label_container">
                            <label class="postLabel">Mô tả ngắn:</label>
                        </div>
                        <textarea name="description" style="width:562px; height: 100px;"><?php echo $this->escape($this->article['description']); ?></textarea>                                              
                    </div>
                    <div class="listing_input hgauto">
                        <div class="post_label_container">
                            <label class="postLabel">Trạng thái:</label>
                        </div>
                        <select class="medium_text_input" name="status" id="status">
                            <option value="1">Hiện</option>
                            <option value="0">Ẩn</option>
                        </select>
                    </div>
                    <div class="listing_input hgauto">
                        <div class="post_label_container">
                            <label class="postLabel">Hot Top trang chủ:</label>
                        </div>
                        <input type="checkbox" id="is_hot" name="is_hot" value="1"> 
                       Hot Top Trang chủ 
                    </div>
                </div>
                <div class="line clear"></div>
                <h3 class="n2">Tag</h3>
                <div class="group_listing_input">
                	<div class="listing_input hgauto">
                        <div class="post_label_container">
                            <label class="postLabel">Từ khóa:</label>
                        </div>
                        <input name="tag_name" id="tag_name" type="text" value="" class="title_text_input" /> <input type="button" value="Thêm Tag" onclick="addTag()" />
                        <div class="tag_box" id="tag_box">                       
                        </div>
                    </div>
                </div>
                <div class="line clear"></div>
                <h3 class="n3">Mô tả chung</h3>
                <textarea id="mce_0" name="content" class="box_html" rows="" cols=""><?php echo $this->article['content']; ?></textarea>
                <div class="button_listing_input">
                    <input id="btn_submit" type="submit" class="button_update" value="" name="btn_submit" />
                </div>                
            </form>
        </div>
    </div>
</div>
<script type="text/javascript"> 
    var editor_tiny_url = '<?php echo $this->layout()->_general['server']['path'].'/js/tiny_mce/tiny_mce.js';?>';

    function addTagInput(id, name)
    {
        var html = '<div class="tag" id="tag_'+ id +'">'+ name +' <a class="remove_tag" onclick="removeTag('+ id +')" href="javascript:void(0)" tag-id="'+ id +'">(x)</a><input type="hidden" name="tag_id[]" value="'+ id +'" /></div>';
        $('#tag_box').append(html);
        $('#tag_name').val('');
    }

    function removeTag(id)
    {       
    	$('#tag_'+ id).remove();
    }   

    function addTag()
    {
    	var tag_name = $('#tag_name').val();

    	if(tag_name != '')
    	{
        	$.post(Settings.baseurl +'/adm/tag/ajax-add-tag', {tag_name: tag_name}, function(data){
            	if(data.tag_id > 0)
            	{
            		addTagInput(data.tag_id, data.tag_name);
            	}            	
        	}, 'json');
    	}
    } 
    
    $(function(){           
        $('textarea.box_html').tinymce({
            /*General options*/
            script_url  : editor_tiny_url,
            language 	: "vi",
            theme 		: "advanced",
            plugins 	: "paste,youtubeIframe",
            width: "700",
            height: "500",
            /*Theme options*/
            theme_advanced_buttons1 : "bold,italic,underline,forecolor,backcolor,|,fontselect,fontsizeselect,|,image_custom,youtubeIframe,|,outdent,indent,|,undo,redo,|,justifyleft,justifycenter,justifyright,justifyfull,|,link,unlink",
            theme_advanced_buttons1_add : "code",
            theme_advanced_buttons2 : "",
            theme_advanced_buttons3 : "",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            paste_auto_cleanup_on_paste : true,
            /*paste_remove_spans : true,
                        paste_remove_styles : true,*/
            paste_preprocess : function(pl, o) {
               
            },
            paste_postprocess : function(pl, o) {
                o.node.innerHTML = o.node.innerHTML.replace(/<span>(.*)<\/span>/g, '$1');
                var i=0;
                for (i=0;i<=4;i++){
                    o.node.innerHTML = o.node.innerHTML.replace(/<span style=\"(.*)\"><span style=\"(.*)\">(.*)<\/span><\/span>/gi, '<span style="$1 $2">$3</span>');
                }
                o.node.innerHTML = o.node.innerHTML.replace(/<(span|p)[^>]*> <\/(span|p)>/gi, '');
                o.node.innerHTML = o.node.innerHTML.replace(/<(span|p)[^>]*><\/(span|p)>/gi, '');
            },
            theme_advanced_resizing : true,
            theme_advanced_resize_horizontal : false,
            theme_advanced_resizing_max_width : 700,
            theme_advanced_resizing_min_width : 700,
            theme_advanced_resizing_min_height : 500,
            entity_encoding : "raw",
            extended_valid_elements : "iframe[src|width|height|name|align]",
            setup : function(ed) {
                // Add a custom button
                ed.addButton('image_custom', {
                    title : 'Đăng ảnh',
                    image : Settings.imgurl+'/mce_danganh.jpg',
                    onclick : ImageUpload.showPopup
                });

                ed.onBeforeSetContent.add(function(ed, o) {
                    //o.content = myTopic.cleanupContent(o.content);
                });
            }
        });       
    });

    function callbackUpload(resp)
    {
    	switch(resp.error_code)
    	{
    		case 0:    		
    			var photoSrc = resp.data.photo_src;	    			
    			$('#picture').val(photoSrc);
    			$('#show_picture').html('<img src="'+ photoSrc+ '" width="100"/>');
    		break;
    	}
    }

    options = {    	       
    	ajaxFile: Settings.uploadurl,
        file_types: "jpg,gif,png",
        width:156,
        height:156,
        time: '1353335609',
        seckey: '4e30e636dca09d00335e87a03f4e5400',
        callback: callbackUpload
    };
    $('#divUpload').photoUpload(options);

    $( "#tag_name" ).autocomplete({
    	source: Settings.baseurl + "/adm/tag/ajax-search",
    	minLength: 2,
    	select: function( event, ui ) {
    		addTagInput(ui.item.id, ui.item.value);
    	}
    });
</script>