<footer>
	<div class="footer-top">
		<div class="container clearfix">
			<div class="row footer-connect-row clearfix">
				<div class="col-md-7 footer-sign-up">
					<h3 class="footer-top-header">Đăng ký nhận bản tin</h3>
					<div class="footer-newsletter-signup pull-left">
						<form class="simple-form">
							<div class="inline">
								<input type="email" size="35" placeholder="Nhập địa chỉ email" name="email_newsletter" class="newsletter-email">
							</div>
							<a class="sign-up-button" id="registerNewsletter" href="javascript:void(0)" id="registerNewsletter">Đăng ký</a>
						</form>
						<div class="newsletter-form-message" style="margin-top:39px;color:red"></div>
					</div>
				</div>
				<div class="col-md-5 footer-social">
					<h3 class="footer-top-header">Kết nối với chúng tôi!</h3>
					<ul class="social-links inline pull-right">
						<li class="social-link"><a target="_blank" class="social-facebook" href="javascript:void(0)">Facebook</a>
						</li>
						<li class="social-link"><a target="_blank" class="social-twitter" href="javascript:void(0)">Twitter</a>
						</li>
						<li class="social-link"><a target="_blank" class="social-pinterest" href="javascript:void(0)">Pinterest</a>
						</li>
						<li class="social-link"><a target="_blank" class="social-youtube" href="javascript:void(0)">YouTube</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="row footer-nav-row clearfix">
				<div class="col-md-3">
					<h4>TÌM HIỂU THÊM</h4>
					<ul>
						<li><a href="<?php echo BASE_URL?>/cach-thuc-van-hanh.html">Cách thức vận hành</a>
						</li>
						<li><a href="<?php echo BASE_URL?>/cach-thuc-van-hanh.html#delivery-zones">Khu vực giao hàng</a>
						</li>
						<li><a href="<?php echo BASE_URL?>/phieu-qua-tang.html">Phiếu quà tặng</a>
						</li>
					</ul>
				</div>
				<div class="col-md-3">
					<h4>TÌM HIỂU VỀ UCANCOOK</h4>
					<ul>
						<li><a href="<?php echo BASE_URL?>/about-us.html?content=our-mission">Nhiệm vụ</a>
						</li>
						<li><a href="<?php echo BASE_URL?>/about-us.html?content=careers-page">Cơ hội nghề nghiệp</a>
						</li>
						<li><a href="<?php echo BASE_URL?>/blog">Blog</a>
						</li>
					</ul>
				</div>
				<div class="col-md-3">
					<h4>BẠN CẦN TRỢ GIÚP?</h4>
					<ul>				
						<li>Gọi số <?php echo PHONE_NUMBER;?></li>
						<li>Email help@ucancook.vn</li>
					</ul>
				</div>
				<div class="col-md-3">
					<a data-toggle="modal" data-target="#popup-refer" class="footer-refer-friend"></a>
				</div>
			</div>
		</div>
	</div>
	<div class="footer-bottom">
		<div class="container clearfix">
			<div class="row">
				<div class="col-md-9">
					<ul class="inline footer-bottom-nav">
						<li class="brand-link-mini"><a class="logo-mini" href="/">Trang chủ Ucancook.vn</a></li>
						<li class="copyright">&copy; 2014 Ucancook.vn</li>
						<li><a href="<?php echo BASE_URL?>/thoa-thuan-su-dung.html">Thỏa thuận sử dụng</a></li>
						<li><a href="<?php echo BASE_URL?>/chinh-sach-quyen-rieng-tu.html">Chính sách quyền riêng tư</a></li>
					</ul>
				</div>
				<div class="col-md-3">

				</div>
			</div>
		</div>
	</div>
</footer>
