<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headMeta(); ?>
	<meta name="viewport" content="width=device-width initial-scale=1.0 maximum-scale=1.0 user-scalable=yes" />
	<meta name="msapplication-navbutton-color" content="#dd4800" />
	<meta name="application-name" content="ucancook.vn" />
	<meta name="msapplication-starturl" content="http://www.ucancook.vn/" />
	<meta name="msapplication-window" content="width=1024;height=768"/>
	<meta property="fb:app_id" content="344527302396637"/>
	<meta name="author" content="">
	<?php $imageSrc = isset($this->thumbImageSrc) ? $this->thumbImageSrc : $this->layout()->_general['static']['path'] . '/images/logo.png';?>
    <link rel="image_src" href="<?php echo $imageSrc ?>" />
    <?php if(isset($this->canonicalUrl) && !empty($this->canonicalUrl)):?>
    <link rel="canonical" href="<?php echo $this->canonicalUrl ?>" />
    <?php endif; ?>
	<link rel="shortcut icon" href="<?php echo $this->layout()->_general['static']['path'];?>/images/favicon_u.ico">
	<link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400,300,700,800">
	<link href="<?php echo $this->layout()->_general['static']['path'];?>/css/base.css" rel="stylesheet">
	<link href="<?php echo $this->layout()->_general['static']['path'];?>/css/layout_news.css" rel="stylesheet">
	<link href="<?php echo $this->layout()->_general['static']['path'];?>/css/bootstrap.css" rel="stylesheet">
	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
	 	var Settings = {domain: "<?php echo DOMAIN;?>", baseurl: "<?php echo BASE_URL?>"};
	 	var Account = {	UID: "<?php echo LOGIN_UID ?>"};
	</script>
    <script src="<?php echo $this->layout()->_general['static']['path'];?>/js/jquery.js"></script>
	<script src="<?php echo $this->layout()->_general['static']['path'];?>/js/bootstrap.min.js"></script>
	<script src="<?php echo $this->layout()->_general['static']['path'];?>/js/global.js"></script>
	<script src="<?php echo $this->layout()->_general['static']['path'];?>/js/jquery.bxslider.min.js"></script>
	<script src="<?php echo $this->layout()->_general['static']['path'];?>/js/news.js"></script>
	<script type="text/javascript">
		//<![CDATA[
		  (function() {
		    var shr = document.createElement('script');
		    shr.setAttribute('data-cfasync', 'false');
		    shr.src = '//dsms0mj1bbhn4.cloudfront.net/assets/pub/shareaholic.js';
		    shr.type = 'text/javascript'; shr.async = 'true';
		    shr.onload = shr.onreadystatechange = function() {
		      var rs = this.readyState;
		      if (rs && rs != 'complete' && rs != 'loaded') return;
		      var site_id = '10907652770b65788586e42bb5393dd6';
		      try { Shareaholic.init(site_id); } catch (e) {}
		    };
		    var s = document.getElementsByTagName('script')[0];
		    s.parentNode.insertBefore(shr, s);
		  })();
		//]]>
	</script>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=344527302396637&version=v2.0";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>		
</head>
<body>
	<div id="fb-root"></div>
	<div id="loading" style="display:none;position:fixed;top:0;left:0;z-index:99999;background:rgba(255,255,255,0.6);width:100%;height:100%;cursor:wait"></div>
	<div class="wrapper">
		<div class="wrapper-inside">
			<div class="header clearfix">
				<h1 class="logo"><a href="<?php echo BASE_URL.'/blog';?>">Logo</a></h1>
				<ul class="list-social clearfix hidden-xs">
					<li class="ic ic-01"><a href="javascript:void(0)">twitter</a></li>
					<li class="ic ic-02"><a href="javascript:void(0)">pinterest</a></li>
					<li class="ic ic-03"><a href="javascript:void(0)">facebook</a></li>
					<li class="ic ic-04"><a href="javascript:void(0)">google</a></li>
					<li class="ic ic-05"><a href="javascript:void(0)">instagram</a></li>
					<li class="ic ic-06"><a href="javascript:void(0)">yt</a></li>
				</ul>
			</div>
			<div id="main-menu-wrapper" class="clearfix">
				<div class="mobile-menu-button visible-sm visible-xs"></div>
				<div class="mobile-menu-wrapper" style="display:none;">	
					<ul id="mobile-menu">
						<li class="menu-item"><a href="<?php echo BASE_URL;?>">Ucancook</a></li>
						<li class="menu-item"><a href="<?php echo BASE_URL;?>/cach-thuc-van-hanh.html">CÁCH THỨC VẬN HÀNH</a></li>
						<li class="menu-item"><a href="<?php echo BASE_URL;?>/thuc-don">Thực đơn tuần này</a></li>
					</ul>
				</div>
				<ul id="main-menu" class="fl clearfix hidden-xs hidden-sm">
					<li class="menu-item"><a href="<?php echo BASE_URL;?>">Ucancook</a></li>
					<li class="menu-item"><a href="<?php echo BASE_URL;?>/cach-thuc-van-hanh.html">CÁCH THỨC VẬN HÀNH</a></li>
					<li class="menu-item"><a href="<?php echo BASE_URL;?>/thuc-don">Thực đơn tuần này</a></li>
				</ul>			
				<div class="menu-search-button hidden-xs"></div>
				<div class="menu-search-form" style="display:none">
					<input type="text" name="s" value="<?php if(!empty($this->keyword)) echo $this->keyword; else echo 'Nhập vào từ khóa';?>" onfocus="if(this.value=='Nhập vào từ khóa')this.value='';" onblur="if(this.value=='')this.value='Nhập vào từ khóa';" class="menu-search-field">
				</div>
			</div>
			<?php echo $this->layout()->content?>
			<div id="sidebar-content">
				<div class="widget subscribe">
					<div class="widget-title clearfix">
						<h3>Đăng ký nhận bản tin</h3>
						<form class="newsletter-form">
							<input type="text" style="width:80%;" placeholder="Địa chỉ email" name="email" class="newsletter-email">
							<input type="button" value="Đăng ký" class="newsletter-submit" id="registerNewsletter">	
						</form>
						<span class="newsletter-form-message" style="display:none"></span>
					</div>
				</div>
				<div class="widget">
					<div class="widget-title clearfix">
						<h3>Danh mục</h3>
						<div class="widget-title-border">
							<div class="widget-title-block"></div>
						</div>
					</div>
					<?php 
						$categoryList = Category::selectCategoryList(array('type' => Category::TYPE_CATEGORY_NEWS));
					?>
					<ul>
						<?php foreach($categoryList as $category){?>
						<li class="cat-item"><a title="<?php echo $category['category_name']?>" href="<?php echo Category::categoryNewsUrl($category);?>"><?php echo $category['category_name']?></a></li>
						<?php }?>
					</ul>
				</div>
				<div class="widget">
					<div class="widget-title clearfix">
						<h3>Thư viện bài viết</h3>
						<div class="widget-title-border">
							<div class="widget-title-block"></div>
						</div>
					</div>
					<select class="archive-dropdown">
						<option value="">Chọn tháng</option>
						<?php $curMonth = date('n');$curYear = date('Y');$preYear = $curYear - 1;?>
						<?php for($j = $curYear; $j >= $preYear; $j--){?>
						<?php for($i = $curMonth; $i >= 1; $i--){?>
						<option value="/blog/archive?month=<?php echo $i;?>&year=<?php echo $j?>">Tháng <?php echo $i;?>, <?php echo $j;?></option>
						<?php }}?>
					</select>
				</div>
				<div class="widget">
					<div class="textwidget">
						<a href="javascript:void(0)"><img src="<?php echo $this->layout()->_general['static']['path'];?>/images/plated-banner-vertical.jpg"></a>
					</div>
				</div>
				<div class="sidebar-fade"></div>
			</div>
			<div class="clear"></div>
		</div>
		<div id="footer-wrapper">
			<ul class="footer-columns-4 clearfix">
				<li class="footer-col4">
					<div class="widget">
						<div class="widget-title clearfix">
							<h6>Xu hướng ẩm thực</h6>
						</div>
						<?php $tag = Tag::getList(array(), 0, 40);?>
						<div class="ctc">
							<?php foreach($tag as $item){?>
							<a style="font-size: 11.230769230769pt;" title="<?php echo $item['tag_name']?>" class="ctc-tag" href="<?php echo Tag::tagUrl($item)?>"><?php echo $item['tag_name']?></a>		
							<?php }?>			
						</div>
					</div>
				</li>
				<li class="footer-col4">
					<div class="widget">
						<div class="widget-title clearfix">
							<h6>Tìm hiểu thêm</h6>
						</div>
						<div class="menu-main-menu-container">
							<ul class="menu">
								<li class="menu-item"><a href="<?php echo BASE_URL?>/">Ucancook</a>
								</li>
								<li class="menu-item"><a href="<?php echo BASE_URL.'/cach-thuc-van-hanh.html';?>">Cách thức vận hành</a>
								</li>
								<li class="menu-item"><a href="<?php echo BASE_URL.'/thuc-don'?>">Thực đơn tuần này</a>
								</li>
							</ul>
						</div>
					</div>
				</li>
				<li class="footer-col4">
					<div class="widget">
						<div class="widget-title clearfix">
							<h6>Bài đọc nhiều nhất</h6>
						</div>
						<?php $mostView = Article::getArticleMostView();?>
						<ul>
							<?php foreach($mostView as $article){?>
							<li>
								<a title="<?php echo $article['title']?>" href="<?php echo Article::articleUrl($article);?>"><?php echo $article['title']?></a>
							</li>
							<?php }?>
						</ul>
					</div>
				</li>
				<li class="footer-col4 end">
					<div class="widget">
						<div class="widget-title clearfix">
							<h6>Kết nối với chúng tôi</h6>
						</div>
						<ul class="list-social clearfix">
							<li class="ic ic-01"><a href="javascript:void(0)">twitter</a></li>
							<li class="ic ic-02"><a href="javascript:void(0)">pinterest</a></li>
							<li class="ic ic-03"><a href="javascript:void(0)">facebook</a></li>
							<li class="ic ic-04"><a href="javascript:void(0)">google</a></li>
							<li class="ic ic-05"><a href="javascript:void(0)">instagram</a></li>
							<li class="ic ic-06"><a href="javascript:void(0)">yt</a></li>
						</ul>
					</div>
				</li>
			</ul>
		</div>
		<div id="footer-bottom" class="clearfix">
			<div class="fl clearfix">
				<ul class="footer-menu">
					<li class="menu-item"><a href="<?php echo BASE_URL?>/about-us.html" title="Về chúng tôi">Về chúng tôi</a></li>
					<li class="menu-item"><a href="<?php echo BASE_URL?>/cach-thuc-van-hanh.html#delivery-zones">Khu vực giao hàng</a></li>
					<li class="menu-item"><a href="<?php echo BASE_URL?>/phieu-qua-tang.html">Phiếu quà tặng</a></li>
					<li class="menu-item"><a href="<?php echo BASE_URL?>/chinh-sach-quyen-rieng-tu.html">Chính sách quyền riêng tư</a></li>
				</ul>
			</div>	
			<div class="fr clearfix"><p>&copy; Copyright 2014</p></div>
		</div>
	</div>
</body>
</html>