<?php
	$this->headLink()->appendStylesheet($this->layout()->_general['server']['path'].'/css/calendar.css');
?>
<div id="content">
    <div class="breadcrumb clearfix">
        <div class="title k2">Thêm mới thực đơn | <a href="<?php echo BASE_URL?>/adm/menu/menu-list">Quản lý thực đơn</a></div>
    </div>
    <?php
   	if(isset($_GET['result']) && $_GET['result'] == 'success')
   	{
   	?>
	<div class="warning" style="color:green;font-weight:bold">Thực đơn đã được thêm vào thành công!</div>
	<?php
	}
	?>
    <div class="clear"></div>
    <form id="insert_menu" method="post">
	    <div>
	        <div class="fdefault posting">
                <div class="group_listing_input">
                    <div class="listing_input hgauto">
                        <div class="post_label_container">
                            <label class="postLabel">Chọn lịch:</label>
                        </div>
                        <fieldset class="fs_parent">
	                        <fieldset class="fs_top">
						        <legend>Recurrence Pattern</legend>
						        <div class="col_1">
						            <div>
						              <input id="daily" type="radio" name="recurrence_pattern" value="daily" checked>
						              <label for="daily">Daily</label>
						            </div>
						            <div>
						              <input id="weekly" type="radio" name="recurrence_pattern" value="weekly">
						              <label for="weekly">Weekly</label>
						            </div>
						        </div>
						        <div class="col_2">
						            <div class="group_day">
						                <div>
						                  	<input id="monday" class="ckb_day" type="checkbox" name="days[]" value="1" checked>
						                  	<label for="monday">Monday</label>
						                </div>
						                <div>
						                  	<input id="tuesday" class="ckb_day" type="checkbox" name="days[]" value="2" checked>
						                  	<label for="tuesday">Tueday</label>
						                </div>
						                <div>
						                  	<input id="wednesday" class="ckb_day" type="checkbox" name="days[]" value="3" checked>
						                  	<label for="wednesday">Wednesday</label>
						                </div>
						                <div>
						                  	<input id="thursday" class="ckb_day" type="checkbox" name="days[]" value="4" checked>
						                  	<label for="thursday">Thursday</label>
						                </div>
						                <div>
						                  	<input id="friday" class="ckb_day" type="checkbox" name="days[]" value="5" checked>
						                  	<label for="friday">Friday</label>
						                </div>
						                <div>
						                  	<input id="saturday" class="ckb_day" type="checkbox" name="days[]" value="6" checked>
						                  	<label for="saturday">Saturday</label>
						                </div>
						                <div>
						                  	<input id="sunday" class="ckb_day" type="checkbox" name="days[]" value="7" checked>
						                  	<label for="sunday">Sunday</label>
						                </div>
						            </div>
						        </div>
						    </fieldset>
						    <?php 
						    	$start_date = strtotime(date('d-m-Y'). "00:00:01");
						    	$end_date = strtotime('+ 1 year', $start_date);
						    ?>
	                        <fieldset class="fs_top">
						        <legend>Range of recurrence</legend>
						        <div class="col_3">
						            <div style="padding-bottom:10px">
						              	Start Date&nbsp;&nbsp;
						              	<select name="start_date" id="start_date">
						              		<option value="0">Chọn ngày bắt đầu</option>
						              		<?php for($i = $start_date; $i < $end_date; $i+=86400){ ?>
						              		<option value="<?php echo $i?>">Ngày <?php echo date('d-m-Y', $i);?></option>
						              		<?php }?>
						              	</select>
						            </div>
						            <div>
						             	End Date&nbsp;&nbsp;&nbsp;
						             	<select name="end_date" id="end_date">
						             		<option value="0">Chọn ngày kết thúc</option>
						              		<?php for($i = $start_date; $i < $end_date; $i+=86400){ ?>
						              		<option value="<?php echo $i?>">Ngày <?php echo date('d-m-Y', $i);?></option>
						              		<?php }?>
						              	</select>
						            </div>
						           
						        </div>
						    </fieldset>
						</fieldset>
                    </div>
                    <div class="listing_input hgauto">
                        <div class="post_label_container">
                            <label class="postLabel">Chọn món ăn:</label>
                        </div>
                       	<select id="dish_id" name="dish_id" class="cat" style="width:152px">
							<option value="0">Chọn món ăn</option>
							<?php foreach($this->dishes as $item){?>
							<option value="<?php echo $item['id']?>"><?php echo $item['name']?></option>
							<?php }?>
						</select>
                    </div>	   
                    <div class="listing_input hgauto">
                        <div class="post_label_container">
                            <label class="postLabel">Số lượng bán :</label>
                      	</div>
						<input type="text" class="large" name="quantity" id="quantity"  alt="">    
					</div>
                    <div class="button_listing_input">
                    	<input id="btn_submit" type="button" class="button_update" value="" name="btn_submit" />
                	</div>	
                </div>							                                           
	        </div>
	    </div>
    </form>
</div>
<script>
	$('#btn_submit').click(function() {
		var pattern = $('input:radio[name=recurrence_pattern]:checked').val();
		if (typeof pattern == "undefined") {
			alert("Vui lòng chọn kiểu lặp lại");return;
		}
		
		var start_date = $('#start_date').val();
		if (start_date == 0) {
			alert("Vui lòng chọn ngày bắt đầu");return;
		}
		
		var end_date = $('#end_date').val();
		if (end_date == 0) {
			alert("Vui lòng chọn ngày kết thúc");return;
		}

		var dish_id = $('#dish_id').val();
		if (dish_id == 0) {
			alert("Vui lòng chọn món ăn");return;
		}

		var quantity = $('#quantity').val();
		if (quantity == 0) {
			alert("Vui lòng nhập số lượng");return;
		}

		$('#insert_menu').submit();
	});
	$('.ckb_day').click(function(){
		$('input:radio[name="recurrence_pattern"]').filter('[value="particular"]').attr('checked', true);
	});
	$('input[name="recurrence_pattern"').click(function() {
		var val = $(this).val();
		if(val == "weekly") {
			$('.ckb_day').removeAttr("checked");
		} else {
			$('.ckb_day').attr("checked", "checked");
		}
	});
</script>