<?php
	$this->headLink()->appendStylesheet($this->layout()->_general['server']['path'].'/css/jquery.ui.datepicker.css');
	$this->headScript()->appendFile($this->layout()->_general['server']['path'].'/js/jquery.ui.datepicker.js'); 
	$params = $this->filters;
?>
<div id="content">
    <div class="breadcrumb clearfix">
        <div class="title k2">Quản lý thực đơn</div>
        <div class="addLink">
    		<span class="action"><a class="add" href="/adm/menu/add-menu" title="Thêm mới thực đơn"></a></span>	
		</div>
    </div>
    <form id="frm" name="frm" method="get" action="/adm/menu/menu-list">
        <ul class="filter clearfix">            
           	<li>
				<label>Ngày bán</label>
				<input type="text" class="datepicker large" name="sale_date" value="<?php echo !empty($params['sale_date'])?date('d-m-Y', $params['sale_date']):'';?>">			
			</li>  
            <li id="category_option">
                <label>Món ăn</label>
                 <select id="type" name="dish_id" class="cat">
					<option value="0">Chọn món ăn</option>
					<?php foreach($this->dishes as $item){?>
					<option value="<?php echo $item['id']?>" <?php if($item['id'] == $params['dish_id']) echo 'selected="selected"';?>><?php echo $item['name']?></option>
					<?php }?>
				</select>                
            </li>                             
            <li>
                <label>Limit</label>
                   <select class="cat" name="limit">
                     	<option value="30" <?php if(30 == $params['limit']) echo 'selected="selected"';?>>30</option>
                        <option value="50" <?php if(50 == $params['limit']) echo 'selected="selected"';?>>50</option>
                    	<option value="100" <?php if(100 == $params['limit']) echo 'selected="selected"';?>>100</option>
                   </select>
             </li>                               
              <li class="clear">
                <input id="submit" name="submit" value="" class="button_search" type="submit" />
             </li>
         </ul>
     </form>
    <div class="clear"></div>
    <?php echo $this->paging; ?>
   <div class="table_member">
        <table cellspacing="0" cellpadding="0" border="0" width="100%">
              <tbody>
                    <tr>
                       <td valign="middle" colspan="6" class="firstRow"></td>
                    </tr>
                    <tr>                      
                        <td style="width: 10px" class="secondRow">STT</td>         
						<td width="9%" class="secondRow">Hình ảnh</td>					   
                        <td width="36%" class="secondRow">Tên món</td>
                        <td width="18%" class="secondRow">Loại món</td>	          
					    <td width="18%" class="secondRow">Ngày bán</td>						   
                        <td width="16%" class="secondRow">Thao tác</td>
                    </tr>   
                    <?php
                    if (is_array($this->menues) && !empty($this->menues)) { $i = 1;
                        foreach ($this->menues as $key => $value) {
                    ?>
	                    <tr>
		                    <td align="center" class="ctn"><?php echo $i; ?></td>
		                    <td class="ctn"><img src="<?php echo $this->multiDish[$value['dish_id']]['image'];?>" style="width:70px;height:70px"></td>	                    
		                    <td class="ctn">
		                    	<?php echo $this->multiDish[$value['dish_id']]['name'];?>
		                    </td>	                    		               
		                    <td class="ctn"><?php echo Dish::$_ARRAY_TYPE[$this->multiDish[$value['dish_id']]['type']]['name'];?></td>	               		                   	
		                    <td class="ctn"><?php 
		                    	$day = date('N', $value['sale_date']);
		                    	My_Zend_Globals::verbalDate($day);
		                    	echo date('d-m-Y', $value['sale_date']); ?></td>	    
		                    <td class="ctn">	                    	
								<a href="<?php echo BASE_URL.'/adm/menu/edit-menu/id/'.$value['id']?>" class="b_edit" title="Cập nhật thực đơn này"><img src="<?php echo $this->layout()->_general['server']['path']; ?>/images/b_edit.jpg" alt="" width="60px" height="20px"/></a> 
								<a href="javascript:void(0)" class="btn btn-danger btn-sm delete_menu" title="Xóa thực đơn này" rel="<?php echo $value['id'];?>"><img src="<?php echo $this->layout()->_general['server']['path']; ?>/images/b_del.jpg" alt="" width="60px" height="20px"/></a>
		                    </td>
	                </tr>  
	                <?php $i++;}}else{?>
	                <tr>
	                    <td class="ctn nonSearch" colspan="6">Không tìm thấy kết quả phù hợp theo yêu cầu của bạn.</td>
	                </tr>
	                <?php } ?>            	                	
                    <tr>
						<td valign="middle" colspan="6" class="firstRow"></td>                 
					</tr>
           </tbody>
       </table>
    </div>
    <?php echo $this->paging; ?>
 </div>
<script>
	$(document).ready(function()
	{
		$(".datepicker").datepicker({ dateFormat: 'dd-mm-yy' });
		$('.delete_menu').click(function()
		{
			var obj = $(this);
			var menuId = $(this).attr('rel');
			
			$(this).myBoxy (Boxy,{
				type: 'confirm',
				message: 'Bạn chắc chắn muốn xóa thực đơn này?',
				callback: function() 
				{
					var boxy = Boxy.get($(".popup"));
						boxy.hide();
					
					$(this).myBoxy (Boxy,{
			            title: 'Loading',
			            type: 'loading',
			            message: '<img src="'+Settings.imgurl+'/loading_more.gif" alt="Loading" style="margin-bottom:5px;margin-left:10px;" />'
			        });
							
					$.ajax({
						type: "POST",
						url: Settings.baseurl + '/adm/menu/delete-menu',
						data:{id:menuId},
						dataType:'json',
						success: function(data)
						{   
							var boxy = Boxy.get($(".popup"));
								boxy.hide();
							
							if(data.error == 0)
							{
								$(this).myBoxy (Boxy,{
									type: 'success',
									message: 'Bạn đã xóa thực đơn thành công.'
								});    
								obj.parent().parent().remove();
							}
							else
							{
								$(this).myBoxy (Boxy,{
									type:'alert',
									message: 'Thao tác thất bại. Bạn vui lòng thử lại sau.'
								});
							}
						}
					});
				}
			});
		});
	});
</script>  <!--End Content-->  