<?php
global $_CITIES;

$_CITIES = array (
29 => array ('city_id' => 29, 'country_id' => 196, 'city_name' => 'TP. Hồ Chí Minh', 'ordering' => 1, 'be_id' => 79, 'sendo_id' => 1, 'code' => 79),
22 => array ('city_id' => 22, 'country_id' => 196, 'city_name' => 'Hà Nội', 'ordering' => 2, 'be_id' => 1, 'sendo_id' => 2, 'code' => 1),
1 => array ('city_id' => 1, 'country_id' => 196, 'city_name' => 'An Giang', 'ordering' => 65, 'be_id' => 89, 'sendo_id' => 3, 'code' => 89),
3 => array ('city_id' => 3, 'country_id' => 196, 'city_name' => 'Bà Rịa - Vũng Tàu', 'ordering' => 65, 'be_id' => 77, 'sendo_id' => 58, 'code' => 77),
2 => array ('city_id' => 2, 'country_id' => 196, 'city_name' => 'Bạc Liêu', 'ordering' => 65, 'be_id' => 95, 'sendo_id' => 7, 'code' => 95),
4 => array ('city_id' => 4, 'country_id' => 196, 'city_name' => 'Bắc Cạn', 'ordering' => 65, 'be_id' => 6, 'sendo_id' => 5, 'code' => 6),
5 => array ('city_id' => 5, 'country_id' => 196, 'city_name' => 'Bắc Giang', 'ordering' => 65, 'be_id' => 24, 'sendo_id' => 6, 'code' => 24),
6 => array ('city_id' => 6, 'country_id' => 196, 'city_name' => 'Bắc Ninh', 'ordering' => 65, 'be_id' => 27, 'sendo_id' => 8, 'code' => 27),
7 => array ('city_id' => 7, 'country_id' => 196, 'city_name' => 'Bến Tre', 'ordering' => 65, 'be_id' => 83, 'sendo_id' => 9, 'code' => 83),
8 => array ('city_id' => 8, 'country_id' => 196, 'city_name' => 'Bình Dương', 'ordering' => 65, 'be_id' => 74, 'sendo_id' => 61, 'code' => 74),
9 => array ('city_id' => 9, 'country_id' => 196, 'city_name' => 'Bình Định', 'ordering' => 65, 'be_id' => 52, 'sendo_id' => 11, 'code' => 152),
10 => array ('city_id' => 10, 'country_id' => 196, 'city_name' => 'Bình Phước', 'ordering' => 65, 'be_id' => 70, 'sendo_id' => 12, 'code' => 70),
11 => array ('city_id' => 11, 'country_id' => 196, 'city_name' => 'Bình Thuận', 'ordering' => 65, 'be_id' => 60, 'sendo_id' => 13, 'code' => 60),
12 => array ('city_id' => 12, 'country_id' => 196, 'city_name' => 'Cà Mau', 'ordering' => 65, 'be_id' => 96, 'sendo_id' => 14, 'code' => 96),
13 => array ('city_id' => 13, 'country_id' => 196, 'city_name' => 'Cao Bằng', 'ordering' => 65, 'be_id' => 4, 'sendo_id' => 16, 'code' => 4),
14 => array ('city_id' => 14, 'country_id' => 196, 'city_name' => 'Cần Thơ', 'ordering' => 3, 'be_id' => 92, 'sendo_id' => 15, 'code' => 92),
15 => array ('city_id' => 15, 'country_id' => 196, 'city_name' => 'Đà Nẵng', 'ordering' => 4, 'be_id' => 48, 'sendo_id' => 17, 'code' => 48),
64 => array ('city_id' => 64, 'country_id' => 196, 'city_name' => 'Điện Biên', 'ordering' => 65, 'be_id' => 11, 'sendo_id' => 19, 'code' => 11),
63 => array ('city_id' => 63, 'country_id' => 196, 'city_name' => 'Đắc Nông', 'ordering' => 65, 'be_id' => 67, 'sendo_id' => 62, 'code' => 67),
16 => array ('city_id' => 16, 'country_id' => 196, 'city_name' => 'Đắc Lắc', 'ordering' => 65, 'be_id' => 66, 'sendo_id' => 18, 'code' => 66),
17 => array ('city_id' => 17, 'country_id' => 196, 'city_name' => 'Đồng Nai', 'ordering' => 65, 'be_id' => 75, 'sendo_id' => 20, 'code' => 75),
19 => array ('city_id' => 19, 'country_id' => 196, 'city_name' => 'Đồng Tháp', 'ordering' => 65, 'be_id' => 87, 'sendo_id' => 63, 'code' => 87),
20 => array ('city_id' => 20, 'country_id' => 196, 'city_name' => 'Gia Lai', 'ordering' => 65, 'be_id' => 64, 'sendo_id' => 21, 'code' => 64),
21 => array ('city_id' => 21, 'country_id' => 196, 'city_name' => 'Hà Giang', 'ordering' => 65, 'be_id' => 2, 'sendo_id' => 22, 'code' => 2),
23 => array ('city_id' => 23, 'country_id' => 196, 'city_name' => 'Hà Nam', 'ordering' => 65, 'be_id' => 35, 'sendo_id' => 23, 'code' => 35),
24 => array ('city_id' => 24, 'country_id' => 196, 'city_name' => 'Hà Tây', 'ordering' => 65, 'be_id' => 28, 'sendo_id' => 2, 'code' => 28),
25 => array ('city_id' => 25, 'country_id' => 196, 'city_name' => 'Hà Tĩnh', 'ordering' => 65, 'be_id' => 42, 'sendo_id' => 25, 'code' => 42),
26 => array ('city_id' => 26, 'country_id' => 196, 'city_name' => 'Hải Dương', 'ordering' => 65, 'be_id' => 30, 'sendo_id' => 26, 'code' => 30),
27 => array ('city_id' => 27, 'country_id' => 196, 'city_name' => 'Hải Phòng', 'ordering' => 65, 'be_id' => 31, 'sendo_id' => 27, 'code' => 31), 
65 => array ('city_id' => 65, 'country_id' => 196, 'city_name' => 'Hậu Giang', 'ordering' => 65, 'be_id' => 93, 'sendo_id' => 24, 'code' => 93),
28 => array ('city_id' => 28, 'country_id' => 196, 'city_name' => 'Hòa Bình', 'ordering' => 65, 'be_id' => 17, 'sendo_id' => 28, 'code' => 17),
30 => array ('city_id' => 30, 'country_id' => 196, 'city_name' => 'Hưng Yên', 'ordering' => 65, 'be_id' => 33, 'sendo_id' => 64, 'code' => 33),
31 => array ('city_id' => 31, 'country_id' => 196, 'city_name' => 'Khánh Hòa', 'ordering' => 65, 'be_id' => 56, 'sendo_id' => 30, 'code' => 56),
32 => array ('city_id' => 32, 'country_id' => 196, 'city_name' => 'Kiên Giang', 'ordering' => 65, 'be_id' => 91, 'sendo_id' => 55, 'code' => 91),
33 => array ('city_id' => 33, 'country_id' => 196, 'city_name' => 'Kon Tum', 'ordering' => 65, 'be_id' => 62, 'sendo_id' => 65, 'code' => 62),
34 => array ('city_id' => 34, 'country_id' => 196, 'city_name' => 'Lai Châu', 'ordering' => 65, 'be_id' => 12, 'sendo_id' => 32, 'code' => 12),
35 => array ('city_id' => 35, 'country_id' => 196, 'city_name' => 'Lạng Sơn', 'ordering' => 65, 'be_id' => 20, 'sendo_id' => 34, 'code' => 20),
36 => array ('city_id' => 36, 'country_id' => 196, 'city_name' => 'Lào Cai', 'ordering' => 65, 'be_id' => 10, 'sendo_id' => 35, 'code' => 10),
37 => array ('city_id' => 37, 'country_id' => 196, 'city_name' => 'Lâm Đồng', 'ordering' => 65, 'be_id' => 68, 'sendo_id' => 33, 'code' => 68),
38 => array ('city_id' => 38, 'country_id' => 196, 'city_name' => 'Long An', 'ordering' => 65, 'be_id' => 80, 'sendo_id' => 36, 'code' => 80),
39 => array ('city_id' => 39, 'country_id' => 196, 'city_name' => 'Nam Định', 'ordering' => 65, 'be_id' => 36, 'sendo_id' => 37, 'code' => 36),
40 => array ('city_id' => 40, 'country_id' => 196, 'city_name' => 'Nghệ An', 'ordering' => 65, 'be_id' => 40, 'sendo_id' => 38, 'code' => 40),
41 => array ('city_id' => 41, 'country_id' => 196, 'city_name' => 'Ninh Bình', 'ordering' => 65, 'be_id' => 37, 'sendo_id' => 66, 'code' => 37),
42 => array ('city_id' => 42, 'country_id' => 196, 'city_name' => 'Ninh Thuận', 'ordering' => 65, 'be_id' => 58, 'sendo_id' => 39, 'code' => 58),
43 => array ('city_id' => 43, 'country_id' => 196, 'city_name' => 'Phú Thọ', 'ordering' => 65, 'be_id' => 25, 'sendo_id' => 40, 'code' => 25),
44 => array ('city_id' => 44, 'country_id' => 196, 'city_name' => 'Phú Yên', 'ordering' => 65, 'be_id' => 54, 'sendo_id' => 41, 'code' => 54),
45 => array ('city_id' => 45, 'country_id' => 196, 'city_name' => 'Quảng Bình', 'ordering' => 65, 'be_id' => 44, 'sendo_id' => 42, 'code' => 44),
46 => array ('city_id' => 46, 'country_id' => 196, 'city_name' => 'Quảng Nam', 'ordering' => 65, 'be_id' => 49, 'sendo_id' => 43, 'code' => 49),
47 => array ('city_id' => 47, 'country_id' => 196, 'city_name' => 'Quảng Ngãi', 'ordering' => 65, 'be_id' => 51, 'sendo_id' => 44, 'code' => 51),
48 => array ('city_id' => 48, 'country_id' => 196, 'city_name' => 'Quảng Ninh', 'ordering' => 65, 'be_id' => 22, 'sendo_id' => 45, 'code' => 22),
49 => array ('city_id' => 49, 'country_id' => 196, 'city_name' => 'Quảng Trị', 'ordering' => 65, 'be_id' => 45, 'sendo_id' => 46, 'code' => 45),
50 => array ('city_id' => 50, 'country_id' => 196, 'city_name' => 'Sơn La', 'ordering' => 65, 'be_id' => 14, 'sendo_id' => 67, 'code' => 14),
51 => array ('city_id' => 51, 'country_id' => 196, 'city_name' => 'Sóc Trăng', 'ordering' => 65, 'be_id' => 94, 'sendo_id' => 47, 'code' => 94),
52 => array ('city_id' => 52, 'country_id' => 196, 'city_name' => 'Tây Ninh', 'ordering' => 65, 'be_id' => 72, 'sendo_id' => 48, 'code' => 72),
53 => array ('city_id' => 53, 'country_id' => 196, 'city_name' => 'Thái Bình', 'ordering' => 65, 'be_id' => 34, 'sendo_id' => 49, 'code' => 34),
54 => array ('city_id' => 54, 'country_id' => 196, 'city_name' => 'Thái Nguyên', 'ordering' => 65, 'be_id' => 19, 'sendo_id' => 50, 'code' => 19),
55 => array ('city_id' => 55, 'country_id' => 196, 'city_name' => 'Thanh Hóa', 'ordering' => 65, 'be_id' => 38, 'sendo_id' => 51, 'code' => 38),
56 => array ('city_id' => 56, 'country_id' => 196, 'city_name' => 'Thừa Thiên Huế', 'ordering' => 65, 'be_id' => 46, 'sendo_id' => 52, 'code' => 46),
57 => array ('city_id' => 57, 'country_id' => 196, 'city_name' => 'Tiền Giang', 'ordering' => 65, 'be_id' => 82, 'sendo_id' => 53, 'code' => 82),
58 => array ('city_id' => 58, 'country_id' => 196, 'city_name' => 'Trà Vinh', 'ordering' => 65, 'be_id' => 84, 'sendo_id' => 54, 'code' => 84),
59 => array ('city_id' => 59, 'country_id' => 196, 'city_name' => 'Tuyên Quang', 'ordering' => 65, 'be_id' => 8, 'sendo_id' => 55, 'code' => 8),
60 => array ('city_id' => 60, 'country_id' => 196, 'city_name' => 'Vĩnh Long', 'ordering' => 65, 'be_id' => 86, 'sendo_id' => 60, 'code' => 86),
61 => array ('city_id' => 61, 'country_id' => 196, 'city_name' => 'Vĩnh Phúc', 'ordering' => 65, 'be_id' => 26, 'sendo_id' => 57, 'code' => 26),
62 => array ('city_id' => 62, 'country_id' => 196, 'city_name' => 'Yên Bái', 'ordering' => 65, 'be_id' => 15, 'sendo_id' => 59, 'code' => 15),
);

global $_DISTRICTS;

$_DISTRICTS = array(
	1 => array(
	1=>array("district_name" => "Thành phố Long Xuyên", "be_id"	=> "387", "main" => 1, 'sendo_id' => 67, 'code' => 883),
	2=>array("district_name" => "Thị xã Châu Đốc", "be_id"	=> "388", "main" => 0, 'sendo_id' => 66, 'code' => 884),
	3=>array("district_name" => "Thị xã Tân Châu", "be_id"	=> "389", "main" => 0, 'sendo_id' => 69, 'code' => 887),
	4=>array("district_name" => "Huyện An Phú", "be_id"	=> "390", "main" => 0, 'sendo_id' => 68, 'code' => 886),
	5=>array("district_name" => "Huyện Châu Phú", "be_id"	=> "391", "main" => 0, 'sendo_id' => 73, 'code' => 889),
	6=>array("district_name" => "Huyện Châu Thành", "be_id"	=> "392", "main" => 0, 'sendo_id' => 75, 'code' => 892),
	7=>array("district_name" => "Huyện Chợ Mới", "be_id"	=> "393", "main" => 0, 'sendo_id' => 74, 'code' => 893),
	8=>array("district_name" => "Huyện Phú Tân", "be_id"	=> "394", "main" => 0, 'sendo_id' => 70, 'code' => 888),
	9=>array("district_name" => "Huyện Thoại Sơn", "be_id"	=> "395", "main" => 0, 'sendo_id' => 76, 'code' => 894),
	10=>array("district_name" => "Huyện Tịnh Biên", "be_id"	=> "396", "main" => 0, 'sendo_id' => 71, 'code' => 890),
	11=>array("district_name" => "Huyện Tri Tôn", "be_id"	=> "397", "main" => 0, 'sendo_id' => 72, 'code' => 891),
	), 
	2 => array(
	1=>array("district_name" => "Thị xã Bạc Liêu", "be_id"	=> "398", "main" => 0,'sendo_id' => 121, 'code' => 954), 
	2=>array("district_name" => "Huyện Phước Long", "be_id"	=> "403", "main" => 0,'sendo_id' => 125, 'code' => 957),
	3=>array("district_name" => "Huyện Hông Dân", "be_id"	=> "402", "main" => 0,'sendo_id' => 123, 'code' => 956),
	4=>array("district_name" => "Huyện Vĩnh Lợi", "be_id"	=> "404", "main" => 0,'sendo_id' => 122, 'code' => 958),
	5=>array("district_name" => "Huyện Giá Rai", "be_id"	=> "400", "main" => 0,'sendo_id' => 124, 'code' => 959),
	6=>array("district_name" => "Huyện Đông Hải", "be_id"	=> "399", "main" => 0,'sendo_id' => 126, 'code' => 960),
	7=>array("district_name" => "Huyện Hòa Bình", "be_id"	=> "401", "main" => 0,'sendo_id' => 721, 'code' => 961),
	), 
	3 => array(
	1=>array("district_name" => "Thành phố Vũng Tàu", "be_id"	=> "701", "main" => 1,'sendo_id' => 77, 'code' => 747),
	2=>array("district_name" => "Thị xã Bà Rịa", "be_id"	=> "702", "main" => 0,'sendo_id' => 78, 'code' => 748),
	3=>array("district_name" => "Huyện Long Điền", "be_id"	=> "706", "main" => 0,'sendo_id' => 80, 'code' => 752),
	4=>array("district_name" => "Huyện Đất Đỏ", "be_id"	=> "705", "main" => 0,'sendo_id' => 84, 'code' => 753),
	5=>array("district_name" => "Huyện Tân Thành", "be_id"	=> "707", "main" => 0,'sendo_id' => 82, 'code' => 754),
	6=>array("district_name" => "Huyện Châu Đức", "be_id"	=> "703", "main" => 0,'sendo_id' => 83, 'code' => 750),
	7=>array("district_name" => "Huyện Xuyên Mộc", "be_id"	=> "708", "main" => 0,'sendo_id' => 79, 'code' => 751),
	8=>array("district_name" => "Huyện Côn Đảo", "be_id"	=> "704", "main" => 0,'sendo_id' => 78, 'code' => 748),
	), 
	4 => array(
	1=>array("district_name" => "Thị xã Bắc Kạn", "be_id"	=> "61", "main" => 0,'sendo_id' => 127, 'code' => 58),
	2=>array("district_name" => "Huyện Ba Bể", "be_id"	=> "62", "main" => 0,'sendo_id' => 132, 'code' => 61),
	3=>array("district_name" => "Huyện Bạch Thông", "be_id"	=> "63", "main" => 0,'sendo_id' => 129, 'code' => 63),
	4=>array("district_name" => "Huyện Chợ Đồn", "be_id"	=> "65", "main" => 0,'sendo_id' => 128, 'code' => 64),
	5=>array("district_name" => "Huyện Chợ Mới", "be_id"	=> "66", "main" => 0,'sendo_id' => 133, 'code' => 65),
	6=>array("district_name" => "Huyện Na Rì", "be_id"	=> "68", "main" => 0,'sendo_id' => 130, 'code' => 66),
	7=>array("district_name" => "Huyện Ngân Sơn", "be_id"	=> "67", "main" => 0,'sendo_id' => 131, 'code' => 62),
	8=>array("district_name" => "Huyện Pác Nặm", "be_id"	=> "69", "main" => 0,'sendo_id' => 134, 'code' => 60),
	), 
	5 => array(
	1=>array("district_name" => "Thành phố Bắc Giang", "be_id"	=> "70", "main" => 1,'sendo_id' => 135, 'code' => 213),
	2=>array("district_name" => "Huyện Yên Thế", "be_id"	=> "71", "main" => 0, 'sendo_id' => 136, 'code' => 215),
	3=>array("district_name" => "Huyện Tân Yên", "be_id"	=> "72", "main" => 0, 'sendo_id' => 140, 'code' => 216),
	4=>array("district_name" => "Huyện Lục Ngạn", "be_id"	=> "73", "main" => 0, 'sendo_id' => 138, 'code' => 219),
	5=>array("district_name" => "Huyện Hiệp Hòa", "be_id"	=> "74", "main" => 0, 'sendo_id' => 141, 'code' => 223),
	6=>array("district_name" => "Huyện Lạng Giang", "be_id"	=> "75", "main" => 0, 'sendo_id' => 142, 'code' => 217),
	7=>array("district_name" => "Huyện Sơn Động", "be_id"	=> "76", "main" => 0, 'sendo_id' => 137, 'code' => 220),
	8=>array("district_name" => "Huyện Lục Nam", "be_id"	=> "77", "main" => 0, 'sendo_id' => 139, 'code' => 218),
	9=>array("district_name" => "Huyện Việt Yên", "be_id"	=> "78", "main" => 0, 'sendo_id' => 143, 'code' => 222),
	10=>array("district_name" => "Huyện Yên Dũng", "be_id"	=> "79", "main" => 0, 'sendo_id' => 135, 'code' => 213),
	), 
	6 => array(
	1=>array("district_name" => "Thành phố Bắc Ninh", "be_id"	=> "80", "main" => 1, 'sendo_id' => 145, 'code' => 256),
	2=>array("district_name" => "Thị xã Từ Sơn", "be_id"	=> "81", "main" => 0, 'sendo_id' => 149, 'code' => 261),
	3=>array("district_name" => "Huyện Gia Bình", "be_id"	=> "82", "main" => 0, 'sendo_id' => 151, 'code' => 263),
	4=>array("district_name" => "Huyện Lương Tài", "be_id"	=> "83", "main" => 0, 'sendo_id' => 152, 'code' => 264),
	5=>array("district_name" => "Huyện Quế Võ", "be_id"	=> "84", "main" => 0, 'sendo_id' => 148, 'code' => 259),
	6=>array("district_name" => "Huyện Thuận Thành", "be_id"	=> "85", "main" => 0, 'sendo_id' => 150, 'code' => 262),
	7=>array("district_name" => "Huyện Tiên Du", "be_id"	=> "86", "main" => 0, 'sendo_id' => 147, 'code' => 260),
	8=>array("district_name" => "Huyện Yên Phong", "be_id"	=> "87", "main" => 0, 'sendo_id' => 146, 'code' => 258),
	), 
	7 => array(
	1=>array("district_name" => "Thành phố Bến Tre", "be_id"	=> "405", "main" => 1, 'sendo_id' => 153, 'code' => 829),
	2=>array("district_name" => "Huyện Ba Tri", "be_id"	=> "406", "main" => 0, 'sendo_id' => 159, 'code' => 836),
	3=>array("district_name" => "Huyện Bình Đại", "be_id"	=> "407", "main" => 0, 'sendo_id' => 158, 'code' => 835),
	4=>array("district_name" => "Huyện Châu Thành", "be_id"	=> "408", "main" => 0, 'sendo_id' => 155, 'code' => 831),
	5=>array("district_name" => "Huyện Chợ Lách", "be_id"	=> "409", "main" => 0, 'sendo_id' => 154, 'code' => 832),
	6=>array("district_name" => "Huyện Giồng Trôm", "be_id"	=> "410", "main" => 0, 'sendo_id' => 157, 'code' => 834),
	7=>array("district_name" => "Huyện Mỏ Cày Bac", "be_id"	=> "411", "main" => 0, 'sendo_id' => 156, 'code' => 838),
	8=>array("district_name" => "Huyện Mỏ Cày Nam", "be_id"	=> "412", "main" => 0, 'sendo_id' => 722, 'code' => 833),
	9=>array("district_name" => "Huyện Thạnh Phú", "be_id"	=> "413", "main" => 0, 'sendo_id' => 160, 'code' => 837),
	), 
	8 => array(
	1=>array("district_name" => "Thị xã Thủ Dầu Một", "be_id"	=> "426", "main" => 1, 'sendo_id' => 85, 'code' => 718),
	2=>array("district_name" => "Huyện Bến Cát", "be_id"	=> "428", "main" => 0, 'sendo_id' => 86, 'code' => 721),
	3=>array("district_name" => "Huyện Dầu Tiếng", "be_id"	=> "429", "main" => 0, 'sendo_id' => 91, 'code' => 720),
	4=>array("district_name" => "Huyện Tân Uyên", "be_id"	=> "431", "main" => 0, 'sendo_id' => 87, 'code' => 723),
	5=>array("district_name" => "Huyện Phú Giáo", "be_id"	=> "430", "main" => 0, 'sendo_id' => 90, 'code' => 722),
	6=>array("district_name" => "Huyện Thuận An", "be_id"	=> "427", "main" => 0, 'sendo_id' => 88, 'code' => 725),
	7=>array("district_name" => "Huyện Dĩ An", "be_id"	=> "425", "main" => 0, 'sendo_id' => 89, 'code' => 724),
	), 
	9 => array(
	1=>array("district_name" => "Thành phố Qui Nhơn", "be_id"	=> "414", "main" => 1, 'sendo_id' => 109, 'code' => 540),
	2=>array("district_name" => "Huyện An Lão", "be_id"	=> "415", "main" => 0, 'sendo_id' => 110, 'code' => 542),
	3=>array("district_name" => "Huyện An Nhơn", "be_id"	=> "416", "main" => 0, 'sendo_id' => 119, 'code' => 549),
	4=>array("district_name" => "Huyện Hoài Ân", "be_id"	=> "417", "main" => 0, 'sendo_id' => 112, 'code' => 544),
	5=>array("district_name" => "Huyện Hoài Nhơn", "be_id"	=> "418", "main" => 0, 'sendo_id' => 113, 'code' => 543),
	6=>array("district_name" => "Huyện Phù Cát", "be_id"	=> "419", "main" => 0, 'sendo_id' => 115, 'code' => 548),
	7=>array("district_name" => "Huyện Phù Mỹ", "be_id"	=> "420", "main" => 0, 'sendo_id' => 114, 'code' => 545),
	8=>array("district_name" => "Huyện Tuy Phước", "be_id"	=> "422", "main" => 0, 'sendo_id' => 120, 'code' => 550),
	9=>array("district_name" => "Huyện Tây Sơn", "be_id"	=> "421", "main" => 0, 'sendo_id' => 117, 'code' => 547),
	10=>array("district_name" => "Huyện Vân Canh", "be_id"	=> "423", "main" => 0, 'sendo_id' => 118, 'code' => 551),
	11=>array("district_name" => "Huyện Vĩnh Thạnh", "be_id"	=> "424", "main" => 0, 'sendo_id' => 116, 'code' => 546),
	), 
	10 => array(
	1=>array("district_name" => "Thị xã Đồng Xoài", "be_id"	=> "433", "main" => 1, 'sendo_id' => 92, 'code' => 689),
	2=>array("district_name" => "Thị xã Bình Long", "be_id"	=> "432", "main" => 0, 'sendo_id' => 95, 'code' => 690),
	3=>array("district_name" => "Thị xã Phước Long", "be_id"	=> "434", "main" => 0, 'sendo_id' => 98, 'code' => 688),
	4=>array("district_name" => "Huyện Bù Đăng", "be_id"	=> "435", "main" => 0, 'sendo_id' => 99, 'code' => 696),
	5=>array("district_name" => "Huyện Bù Đốp", "be_id"	=> "436", "main" => 0, 'sendo_id' => 97, 'code' => 693),
	6=>array("district_name" => "Huyện Bù Gia Mập", "be_id"	=> "437", "main" => 0, 'sendo_id' => 723, 'code' => 691),
	7=>array("district_name" => "Huyện Chơn Thành", "be_id"	=> "438", "main" => 0, 'sendo_id' => 94, 'code' => 697),
	8=>array("district_name" => "Huyện Đồng Phú", "be_id"	=> "439", "main" => 0, 'sendo_id' => 93, 'code' => 695),
	9=>array("district_name" => "Huyện Hớn Quản", "be_id"	=> "440", "main" => 0, 'sendo_id' => 724, 'code' => 694),
	10=>array("district_name" => "Huyện Lộc Ninh", "be_id"	=> "441", "main" => 0, 'sendo_id' => 96, 'code' => 692),
	), 
	11 => array(
	1=>array("district_name" => "Thành phố Phan Thiết", "be_id"	=> "442", "main" => 1, 'sendo_id' => 100, 'code' => 593),
	2=>array("district_name" => "Thị xã La Gi", "be_id"	=> "443", "main" => 0, 'sendo_id' => 719, 'code' => 594),
	3=>array("district_name" => "Huyện Tuy Phong", "be_id"	=> "451", "main" => 0, 'sendo_id' => 101, 'code' => 595),
	4=>array("district_name" => "Huyện Bắc Bình", "be_id"	=> "444", "main" => 0, 'sendo_id' => 102, 'code' => 596),
	5=>array("district_name" => "Huyện Hàm Thuận Bắc", "be_id"	=> "447", "main" => 0, 'sendo_id' => 103, 'code' => 597),
	6=>array("district_name" => "Huyện Hàm Thuận Nam", "be_id"	=> "448", "main" => 0, 'sendo_id' => 104, 'code' => 598),
	7=>array("district_name" => "Huyện Tánh Linh", "be_id"	=> "450", "main" => 0, 'sendo_id' => 107, 'code' => 599),
	8=>array("district_name" => "Huyện Hàm Tân", "be_id"	=> "446", "main" => 0, 'sendo_id' => 105, 'code' => 601),
	9=>array("district_name" => "Huyện Đức Linh", "be_id"	=> "445", "main" => 0, 'sendo_id' => 106, 'code' => 600),
	10=>array("district_name" => "Huyện đảo Phú Quý", "be_id"	=> "449", "main" => 0, 'sendo_id' => 108, 'code' => 602),
	), 
	13 => array(
	1=>array("district_name" => "Thị xã Cao Bằng", "be_id"	=> "88", "main" => 1, 'sendo_id' => 161, 'code' => 40),
	2=>array("district_name" => "Huyện Bảo Lạc", "be_id"	=> "89", "main" => 0, 'sendo_id' => 163, 'code' => 43),
	3=>array("district_name" => "Huyện Bảo Lâm", "be_id"	=> "90", "main" => 0, 'sendo_id' => 172, 'code' => 42),
	4=>array("district_name" => "Huyện Hạ Lang", "be_id"	=> "91", "main" => 0, 'sendo_id' => 171, 'code' => 48),
	5=>array("district_name" => "Huyện Hà Quảng", "be_id"	=> "92", "main" => 0, 'sendo_id' => 165, 'code' => 45),
	6=>array("district_name" => "Huyện Hòa An", "be_id"	=> "93", "main" => 0, 'sendo_id' => 168, 'code' => 51),
	7=>array("district_name" => "Huyện Nguyên Bình", "be_id"	=> "94", "main" => 0, 'sendo_id' => 167, 'code' => 52),
	8=>array("district_name" => "Huyện Phục Hòa", "be_id"	=> "95", "main" => 0, 'sendo_id' => 173, 'code' => 50),
	9=>array("district_name" => "Huyện Quảng Uyên", "be_id"	=> "96", "main" => 0, 'sendo_id' => 169, 'code' => 49),
	10=>array("district_name" => "Huyện Thạch An", "be_id"	=> "97", "main" => 0, 'sendo_id' => 170, 'code' => 53),
	11=>array("district_name" => "Huyện Thông Nông", "be_id"	=> "98", "main" => 0, 'sendo_id' => 164, 'code' => 44),
	12=>array("district_name" => "Huyện Trà Lĩnh", "be_id"	=> "99", "main" => 0, 'sendo_id' => 166, 'code' => 46),
	13=>array("district_name" => "Huyện Trùng Khánh", "be_id"	=> "100", "main" => 0, 'sendo_id' => 162, 'code' => 47),
	), 
	12 => array(
	1=>array("district_name" => "Thành phố Cà Mau", "be_id"	=> "452", "main" => 1, 'sendo_id' => 182, 'code' => 964),
	2=>array("district_name" => "Huyện Đầm Dơi", "be_id"	=> "454", "main" => 0, 'sendo_id' => 187, 'code' => 970),
	3=>array("district_name" => "Huyện Ngọc Hiển", "be_id"	=> "456", "main" => 0, 'sendo_id' => 188, 'code' => 973),
	4=>array("district_name" => "Huyện Cái Nước", "be_id"	=> "453", "main" => 0, 'sendo_id' => 183, 'code' => 969),
	5=>array("district_name" => "Huyện Trần Văn Thời", "be_id"	=> "460", "main" => 0, 'sendo_id' => 184, 'code' => 968),
	6=>array("district_name" => "Huyện U Minh", "be_id"	=> "459", "main" => 0, 'sendo_id' => 185, 'code' => 966),
	7=>array("district_name" => "Huyện Thới Bình", "be_id"	=> "458", "main" => 0, 'sendo_id' => 186, 'code' => 967),
	8=>array("district_name" => "Huyện Năm Căn", "be_id"	=> "455", "main" => 0, 'sendo_id' => 189, 'code' => 971),
	9=>array("district_name" => "Huyện Phú Tân", "be_id"	=> "457", "main" => 0, 'sendo_id' => 190, 'code' => 972),
	), 
	14 => array(
	1=>array("district_name" => "Quận Ninh Kiều", "be_id"	=> "463", "main" => 1, 'sendo_id' => 175, 'code' => 916),
	2=>array("district_name" => "Quận Bình Thủy", "be_id"	=> "461", "main" => 1, 'sendo_id' => 174, 'code' => 918),
	3=>array("district_name" => "Quận Cái Răng", "be_id"	=> "462", "main" => 1, 'sendo_id' => 176, 'code' => 919),
	4=>array("district_name" => "Quận Ô Môn", "be_id"	=> "464", "main" => 0, 'sendo_id' => 177, 'code' => 917),
	5=>array("district_name" => "Quận Thốt Nốt", "be_id"	=> "465", "main" => 0, 'sendo_id' => 181, 'code' => 923),
	6=>array("district_name" => "Huyện Phong Điền", "be_id"	=> "467", "main" => 0, 'sendo_id' => 178, 'code' => 926),
	7=>array("district_name" => "Huyện Cờ Đỏ", "be_id"	=> "466", "main" => 0, 'sendo_id' => 179, 'code' => 925),
	8=>array("district_name" => "Huyện Thới Lai", "be_id"	=> "468", "main" => 0, 'sendo_id' => 725, 'code' => 927),
	9=>array("district_name" => "Huyện Vinh Thanh", "be_id"	=> "469", "main" => 0, 'sendo_id' => 180, 'code' => 924),
	), 
	15 => array(
	1=>array("district_name" => "Quận Cẩm Lệ", "be_id"	=> "101", "main" => 1, 'sendo_id' => 48, 'code' => 495),
	2=>array("district_name" => "Quận Hải Châu", "be_id"	=> "102", "main" => 1, 'sendo_id' => 42, 'code' => 492),
	3=>array("district_name" => "Quận Liên Chiểu", "be_id"	=> "103", "main" => 1, 'sendo_id' => 47, 'code' => 490),
	4=>array("district_name" => "Quận Ngũ Hành Sơn", "be_id"	=> "104", "main" => 1, 'sendo_id' => 44, 'code' => 494),
	5=>array("district_name" => "Quận Sơn Trà", "be_id"	=> "105", "main" => 1, 'sendo_id' => 46, 'code' => 493),
	6=>array("district_name" => "Quận Thanh Khê", "be_id"	=> "106", "main" => 1, 'sendo_id' => 43, 'code' => 491),
	7=>array("district_name" => "Huyện Hòa Vang", "be_id"	=> "108", "main" => 0, 'sendo_id' => 49, 'code' => 497),
	8=>array("district_name" => "Huyện Hoàng Sa", "be_id"	=> "107", "main" => 0, 'sendo_id' => 50, 'code' => 498),
	), 
	16 => array(
	1=>array("district_name" => "Thành phố Buôn Ma Thuột", "be_id"	=> "470", "main" => 1, 'sendo_id' => 191, 'code' => 643),
	2=>array("district_name" => "Thị xã Buon Ho", "be_id"	=> "471", "main" => 0, 'sendo_id' => 717, 'code' => 644),
	3=>array("district_name" => "Huyện Buôn Dôn", "be_id"	=> "472", "main" => 0, 'sendo_id' => 203, 'code' => 647),
	4=>array("district_name" => "Huyện Cư Kuin", "be_id"	=> "474", "main" => 0, 'sendo_id' => 726, 'code' => 657),
	5=>array("district_name" => "Huyện Cư M'gar", "be_id"	=> "473", "main" => 0, 'sendo_id' => 192, 'code' => 648),
	6=>array("district_name" => "Huyện Ea H'leo", "be_id"	=> "475", "main" => 0, 'sendo_id' => 194, 'code' => 645),
	7=>array("district_name" => "Huyện Ea Kar", "be_id"	=> "476", "main" => 0, 'sendo_id' => 198, 'code' => 651),
	8=>array("district_name" => "Huyện Ea Soúp", "be_id"	=> "477", "main" => 0, 'sendo_id' => 196, 'code' => 646),
	9=>array("district_name" => "Huyện Krông Bông", "be_id"	=> "479", "main" => 0, 'sendo_id' => 201, 'code' => 653),
	10=>array("district_name" => "Huyện Krông Buk", "be_id"	=> "480", "main" => 0, 'sendo_id' => 193, 'code' => 649),
	11=>array("district_name" => "Huyện Krông Pak", "be_id"	=> "482", "main" => 0, 'sendo_id' => 197, 'code' => 654),
	12=>array("district_name" => "Huyện Lắk", "be_id"	=> "483", "main" => 0, 'sendo_id' => 202, 'code' => 656),
	13=>array("district_name" => "Huyện M'Drắk", "be_id"	=> "484", "main" => 0, 'sendo_id' => 199, 'code' => 652),
	14=>array("district_name" => "Huyện Krông Ana", "be_id"	=> "478", "main" => 0, 'sendo_id' => 200, 'code' => 655),
	15=>array("district_name" => "Huyện Krông Năng", "be_id"	=> "481", "main" => 0, 'sendo_id' => 195, 'code' => 650),
	), 
	17 => array(
	1=>array("district_name" => "Thành phố Biên Hòa", "be_id"	=> "493", "main" => 1, 'sendo_id' => 550, 'code' => 731),
	2=>array("district_name" => "Thị xã Long Khánh", "be_id"	=> "494", "main" => 0, 'sendo_id' => 555, 'code' => 732),
	3=>array("district_name" => "Huyện Định Quán", "be_id"	=> "496", "main" => 0, 'sendo_id' => 553, 'code' => 736),
	4=>array("district_name" => "Huyện Long Thành", "be_id"	=> "497", "main" => 0, 'sendo_id' => 557, 'code' => 740),
	5=>array("district_name" => "Huyện Nhơn Trạch", "be_id"	=> "498", "main" => 0, 'sendo_id' => 558, 'code' => 742),
	6=>array("district_name" => "Huyện Tân Phú", "be_id"	=> "499", "main" => 0, 'sendo_id' => 552, 'code' => 734),
	7=>array("district_name" => "Huyện Thống Nhất", "be_id"	=> "500", "main" => 0, 'sendo_id' => 554, 'code' => 738),
	8=>array("district_name" => "Huyện Vĩnh Cửu", "be_id"	=> "502", "main" => 0, 'sendo_id' => 551, 'code' => 735),
	9=>array("district_name" => "Huyện Xuân Lộc", "be_id"	=> "503", "main" => 0, 'sendo_id' => 556, 'code' => 741),
	10=>array("district_name" => "Huyện Cẩm Mỹ", "be_id"	=> "495", "main" => 0, 'sendo_id' => 560, 'code' => 739),
	11=>array("district_name" => "Huyện Trảng Bom", "be_id"	=> "501", "main" => 0, 'sendo_id' => 559, 'code' => 737),
	), 
	19 => array(
	1=>array("district_name" => "Thành phố Cao Lãnh", "be_id"	=> "504", "main" => 1, 'sendo_id' => 212, 'code' => 866),
	2=>array("district_name" => "Thị xã Sa Đéc", "be_id"	=> "505", "main" => 0, 'sendo_id' => 211, 'code' => 867),
	3=>array("district_name" => "Thị xã Hồng Ngự", "be_id"	=> "508", "main" => 0, 'sendo_id' => 214, 'code' => 870),
	4=>array("district_name" => "Huyện Cao Lãnh", "be_id"	=> "506", "main" => 0, 'sendo_id' => 217, 'code' => 873),
	5=>array("district_name" => "Huyện Châu Thành", "be_id"	=> "507", "main" => 0, 'sendo_id' => 231, 'code' => 877),
	6=>array("district_name" => "Huyện Hồng Ngự", "be_id"	=> "508", "main" => 0, 'sendo_id' => 214, 'code' => 870),
	7=>array("district_name" => "Huyện Lai Vung", "be_id"	=> "509", "main" => 0, 'sendo_id' => 230, 'code' => 876),
	8=>array("district_name" => "Huyện Lấp Vò", "be_id"	=> "510", "main" => 0, 'sendo_id' => 218, 'code' => 875),
	9=>array("district_name" => "Huyện Tam Nông", "be_id"	=> "511", "main" => 0, 'sendo_id' => 215, 'code' => 871),
	10=>array("district_name" => "Huyện Tân Hồng", "be_id"	=> "512", "main" => 0, 'sendo_id' => 213, 'code' => 869),
	11=>array("district_name" => "Huyện Thanh Bình", "be_id"	=> "513", "main" => 0, 'sendo_id' => 216, 'code' => 874),
	12=>array("district_name" => "Huyện Tháp Mười", "be_id"	=> "514", "main" => 0, 'sendo_id' => 219, 'code' => 872),
	), 
	20 => array(
	1=>array("district_name" => "Thành phố Pleiku", "be_id"	=> "515", "main" => 1, 'sendo_id' => 244, 'code' => 622),
	2=>array("district_name" => "Thị xã An Khê", "be_id"	=> "516", "main" => 0, 'sendo_id' => 248, 'code' => 623),
	3=>array("district_name" => "Thị xã Ayun Pa", "be_id"	=> "517", "main" => 0, 'sendo_id' => 253, 'code' => 624),
	4=>array("district_name" => "Huyện Chư Păh", "be_id"	=> "518", "main" => 0, 'sendo_id' => 245, 'code' => 627),
	5=>array("district_name" => "Huyện Chư Prông", "be_id"	=> "519", "main" => 0, 'sendo_id' => 251, 'code' => 632),
	6=>array("district_name" => "Huyện Chư Sê", "be_id"	=> "521", "main" => 0, 'sendo_id' => 252, 'code' => 633),
	7=>array("district_name" => "Huyện Đắk Đoa", "be_id"	=> "522", "main" => 0, 'sendo_id' => 256, 'code' => 626),
	8=>array("district_name" => "Huyện Đắc Pơ", "be_id"	=> "523", "main" => 0, 'sendo_id' => 258, 'code' => 634),
	9=>array("district_name" => "Huyện Đức Cơ", "be_id"	=> "524", "main" => 0, 'sendo_id' => 250, 'code' => 631),
	10=>array("district_name" => "Huyện Ia Grai", "be_id"	=> "525", "main" => 0, 'sendo_id' => 255, 'code' => 628),
	11=>array("district_name" => "Huyện Ia Pa", "be_id"	=> "526", "main" => 0, 'sendo_id' => 257, 'code' => 635),
	12=>array("district_name" => "Huyện K'Bang", "be_id"	=> "527", "main" => 0, 'sendo_id' => 247, 'code' => 625),
	13=>array("district_name" => "Huyện Kông Chro", "be_id"	=> "528", "main" => 0, 'sendo_id' => 249, 'code' => 630),
	14=>array("district_name" => "Huyện Krông Pa", "be_id"	=> "529", "main" => 0, 'sendo_id' => 254, 'code' => 637),
	15=>array("district_name" => "Huyện Mang Yang", "be_id"	=> "530", "main" => 0, 'sendo_id' => 246, 'code' => 629),
	16=>array("district_name" => "Huyện Phú Thiện", "be_id"	=> "531", "main" => 0, 'sendo_id' => 728, 'code' => 638),
	17=>array("district_name" => "Huyện Chư Pưh", "be_id"	=> "520", "main" => 0, 'sendo_id' => 727, 'code' => 639),
	), 
	21 => array(
	1=>array("district_name" => "Thị xã Hà Giang", "be_id"	=> "118", "main" => 0, 'sendo_id' => 302, 'code' => 24),
	2=>array("district_name" => "Huyện Bắc Mê", "be_id"	=> "119", "main" => 0, 'sendo_id' => 308, 'code' => 31),
	3=>array("district_name" => "Huyện Bắc Quang", "be_id"	=> "120", "main" => 0, 'sendo_id' => 311, 'code' => 34),
	4=>array("district_name" => "Huyện Đồng Văn", "be_id"	=> "121", "main" => 0, 'sendo_id' => 303, 'code' => 26),
	5=>array("district_name" => "Huyện Hoàng Su Phì", "be_id"	=> "122", "main" => 0, 'sendo_id' => 309, 'code' => 32),
	6=>array("district_name" => "Huyện Mèo Vạc", "be_id"	=> "123", "main" => 0, 'sendo_id' => 304, 'code' => 27),
	7=>array("district_name" => "Huyện Quản Bạ", "be_id"	=> "124", "main" => 0, 'sendo_id' => 306, 'code' => 29),
	8=>array("district_name" => "Huyện Quang Bình", "be_id"	=> "125", "main" => 0, 'sendo_id' => 312, 'code' => 35),
	9=>array("district_name" => "Huyện Vị Xuyên", "be_id"	=> "126", "main" => 0, 'sendo_id' => 307, 'code' => 30),
	10=>array("district_name" => "Huyện Xín Mần", "be_id"	=> "127", "main" => 0, 'sendo_id' => 310, 'code' => 33),
	11=>array("district_name" => "Huyện Yên Minh", "be_id"	=> "128", "main" => 0, 'sendo_id' => 305, 'code' => 28),
	), 
	23 => array(
	1=>array("district_name" => "Thành phố Phủ Lý", "be_id"	=> "129", "main" => 1, 'sendo_id' => 259, 'code' => 347),
	2=>array("district_name" => "Huyện Bình Lục", "be_id"	=> "130", "main" => 0, 'sendo_id' => 264, 'code' => 352),
	3=>array("district_name" => "Huyện Duy Tiên", "be_id"	=> "131", "main" => 0, 'sendo_id' => 260, 'code' => 349),
	4=>array("district_name" => "Huyện Kim Bảng", "be_id"	=> "132", "main" => 0, 'sendo_id' => 261, 'code' => 350),
	5=>array("district_name" => "Huyện Lý Nhân", "be_id"	=> "133", "main" => 0, 'sendo_id' => 262, 'code' => 353),
	6=>array("district_name" => "Huyện Thanh Liêm", "be_id"	=> "134", "main" => 0, 'sendo_id' => 263, 'code' => 351),
	), 
	22 => array(
	1=>array("district_name" => "Quận Ba Đình", "be_id" => "48", "main" => 1, 'sendo_id' => 21, 'code' => 1),
	2=>array("district_name" => "Quận Cầu Giấy", "be_id" => "53", "main" => 1, 'sendo_id' => 26, 'code' => 5),
	3=>array("district_name" => "Quận Đống Đa", "be_id" => "54", "main" => 1, 'sendo_id' => 24, 'code' => 6),
	4=>array("district_name" => "Quận Hà Đông", "be_id" => "49", "main" => 1, 'sendo_id' => 265, 'code' => 268),
	5=>array("district_name" => "Quận Hai Bà Trưng", "be_id" => "55", "main" => 1, 'sendo_id' => 23, 'code' => 7),
	6=>array("district_name" => "Quận Hoàn Kiếm", "be_id" => "50", "main" => 1, 'sendo_id' => 22, 'code' => 2),
	7=>array("district_name" => "Quận Hoàng Mai", "be_id" => "51", "main" => 1, 'sendo_id' => 28, 'code' => 8),
	8=>array("district_name" => "Quận Long Biên", "be_id" => "52", "main" => 1, 'sendo_id' => 29, 'code' => 4),
	9=>array("district_name" => "Quận Tây Hồ", "be_id" => "56", "main" => 1, 'sendo_id' => 25, 'code' => 3),
	10=>array("district_name" => "Quận Thanh Xuân", "be_id" => "57", "main" => 0, 'sendo_id' => 27, 'code' => 9),
	11=>array("district_name" => "Huyện Ba Vì", "be_id" => "31", "main" => 0, 'sendo_id' => 267, 'code' => 271),
	12=>array("district_name" => "Huyện Chương Mỹ", "be_id" => "38", "main" => 0, 'sendo_id' => 271, 'code' => 277),
	13=>array("district_name" => "Huyện Đan Phượng", "be_id" => "32", "main" => 0, 'sendo_id' => 272, 'code' => 273),
	14=>array("district_name" => "Huyện Đông Anh", "be_id" => "39", "main" => 0, 'sendo_id' => 33, 'code' => 17),
	15=>array("district_name" => "Huyện Gia Lâm", "be_id" => "40", "main" => 0, 'sendo_id' => 32, 'code' => 18),
	16=>array("district_name" => "Huyện Hoài Đức", "be_id" => "33", "main" => 0, 'sendo_id' => 273, 'code' => 274),
	17=>array("district_name" => "Huyện Mê Linh", "be_id" => "709", "main" => 0, 'sendo_id' => 716, 'code' => 250),
	18=>array("district_name" => "Huyện Mỹ Đức", "be_id" => "34", "main" => 0, 'sendo_id' => 275, 'code' => 282),
	19=>array("district_name" => "Huyện Phú Xuyên", "be_id" => "35", "main" => 0, 'sendo_id' => 278, 'code' => 280),
	20=>array("district_name" => "Huyện Phúc Thọ", "be_id" => "41", "main" => 0, 'sendo_id' => 268, 'code' => 272),
	21=>array("district_name" => "Huyện Quốc Oai", "be_id" => "42", "main" => 0, 'sendo_id' => 270, 'code' => 275),
	22=>array("district_name" => "Huyện Sóc Sơn", "be_id" => "43", "main" => 0, 'sendo_id' => 34, 'code' => 16),
	23=>array("district_name" => "Huyện Thanh Oai", "be_id" => "60", "main" => 0, 'sendo_id' => 274, 'code' => 278),
	24=>array("district_name" => "Huyện Thanh Trì", "be_id" => "44", "main" => 0, 'sendo_id' => 31, 'code' => 20),
	25=>array("district_name" => "Huyện Thạch Thất", "be_id" => "59", "main" => 0, 'sendo_id' => 269, 'code' => 276),
	26=>array("district_name" => "Huyện Thường Tín", "be_id" => "36", "main" => 0, 'sendo_id' => 277, 'code' => 279),
	27=>array("district_name" => "Huyện Từ Liêm", "be_id" => "45", "main" => 0, 'sendo_id' => 749, 'code' => 21),
	28=>array("district_name" => "Huyện Ứng Hòa", "be_id" => "37", "main" => 0, 'sendo_id' => 276, 'code' => 281),
	29=>array("district_name" => "Thị xã Sơn Tây", "be_id" => "58", "main" => 0, 'sendo_id' => 266, 'code' => 269),
	), 
	24 => array(
	1=>array("district_name" => "Huyện Ba Vì", "be_id" => "31", "main" => 0, 'sendo_id' => 267, 'code' => 271),
	2=>array("district_name" => "Huyện Chương Mỹ", "be_id" => "38", "main" => 0, 'sendo_id' => 271, 'code' => 277),
	3=>array("district_name" => "Huyện Đan Phượng", "be_id" => "32", "main" => 0, 'sendo_id' => 272, 'code' => 273),
	4=>array("district_name" => "Huyện Hoài Đức", "be_id" => "33", "main" => 0, 'sendo_id' => 273, 'code' => 274),
	5=>array("district_name" => "Huyện Mỹ Đức", "be_id" => "34", "main" => 0, 'sendo_id' => 275, 'code' => 282),
	6=>array("district_name" => "Huyện Phú Xuyên", "be_id" => "35", "main" => 0, 'sendo_id' => 278, 'code' => 280),
	7=>array("district_name" => "Huyện Phúc Thọ", "be_id" => "41", "main" => 0, 'sendo_id' => 268, 'code' => 272),
	8=>array("district_name" => "Huyện Quốc Oai", "be_id" => "42", "main" => 0, 'sendo_id' => 270, 'code' => 275),
	9=>array("district_name" => "Huyện Thạch Thất", "be_id" => "59", "main" => 0, 'sendo_id' => 269, 'code' => 276),
	10=>array("district_name" => "Huyện Thanh Oai", "be_id" => "60", "main" => 0, 'sendo_id' => 274, 'code' => 278),
	11=>array("district_name" => "Huyện Thường Tín", "be_id" => "36", "main" => 0, 'sendo_id' => 277, 'code' => 279),
	12=>array("district_name" => "Huyện Ứng Hòa", "be_id" => "37", "main" => 0, 'sendo_id' => 276, 'code' => 281),
	), 
	25 => array(
	1=>array("district_name" => "Thành phố Hà Tĩnh", "be_id" => "337", "main" => 1, 'sendo_id' => 279, 'code' => 436),
	2=>array("district_name" => "Huyện Đức Thọ", "be_id" => "341", "main" => 0, 'sendo_id' => 282, 'code' => 440),
	3=>array("district_name" => "Huyện Nghi Xuân", "be_id" => "346", "main" => 0, 'sendo_id' => 283, 'code' => 442),
	4=>array("district_name" => "Thị xã Hồng Lĩnh", "be_id" => "338", "main" => 0, 'sendo_id' => 280, 'code' => 437),
	5=>array("district_name" => "Huyện Cẩm Xuyên", "be_id" => "339", "main" => 0, 'sendo_id' => 287, 'code' => 446),
	6=>array("district_name" => "Huyện Can Lộc", "be_id" => "340", "main" => 0, 'sendo_id' => 284, 'code' => 443),
	7=>array("district_name" => "Huyện Hương Khê", "be_id" => "343", "main" => 0, 'sendo_id' => 285, 'code' => 444),
	8=>array("district_name" => "Huyện Hương Sơn", "be_id" => "344", "main" => 0, 'sendo_id' => 281, 'code' => 439),
	9=>array("district_name" => "Huyện Kỳ Anh", "be_id" => "345", "main" => 0, 'sendo_id' => 288, 'code' => 447),
	10=>array("district_name" => "Huyện Thạch Hà", "be_id" => "347", "main" => 0, 'sendo_id' => 286, 'code' => 445),
	11=>array("district_name" => "Huyện Vũ Quang", "be_id" => "348", "main" => 0, 'sendo_id' => 289, 'code' => 441),
	12=>array("district_name" => "Huyện Lộc Hà", "be_id" => "349", "main" => 0, 'sendo_id' => 729, 'code' => 448),
	), 
	26 => array(
	1=>array("district_name" => "Thành phố Hải Dương", "be_id" => "135", "main" => 1, 'sendo_id' => 290, 'code' => 288),
	2=>array("district_name" => "Thị xã Chí Linh", "be_id" => "136", "main" => 0, 'sendo_id' => 291, 'code' => 290),
	3=>array("district_name" => "Huyện Bình Giang", "be_id" => "137", "main" => 0, 'sendo_id' => 301, 'code' => 296),
	4=>array("district_name" => "Huyện Cẩm Giàng", "be_id" => "138", "main" => 0, 'sendo_id' => 298, 'code' => 295),
	5=>array("district_name" => "Huyện Gia Lộc", "be_id" => "139", "main" => 0, 'sendo_id' => 294, 'code' => 297),
	6=>array("district_name" => "Huyện Kim Thành", "be_id" => "140", "main" => 0, 'sendo_id' => 300, 'code' => 293),
	7=>array("district_name" => "Huyện Kinh Môn", "be_id" => "141", "main" => 0, 'sendo_id' => 293, 'code' => 292),
	8=>array("district_name" => "Huyện Nam Sách", "be_id" => "142", "main" => 0, 'sendo_id' => 292, 'code' => 291),
	9=>array("district_name" => "Huyện Ninh Giang", "be_id" => "143", "main" => 0, 'sendo_id' => 297, 'code' => 299),
	10=>array("district_name" => "Huyện Thanh Hà", "be_id" => "144", "main" => 0, 'sendo_id' => 299, 'code' => 294),
	11=>array("district_name" => "Huyện Thanh Miên", "be_id" => "145", "main" => 0, 'sendo_id' => 296, 'code' => 300),
	12=>array("district_name" => "Huyện Tứ Kỳ", "be_id" => "146", "main" => 0, 'sendo_id' => 295, 'code' => 298),
	), 
	27 => array(
	1=>array("district_name" => "Quận Dương Kinh", "be_id" => "147", "main" => 1, 'sendo_id' => 730, 'code' => 309),
	2=>array("district_name" => "Quận Đồ Sơn", "be_id" => "148", "main" => 1, 'sendo_id' => 57, 'code' => 308),
	3=>array("district_name" => "Quận Hải An", "be_id" => "149", "main" => 1, 'sendo_id' => 56, 'code' => 306),
	4=>array("district_name" => "Quận Hồng Bàng", "be_id" => "151", "main" => 1, 'sendo_id' => 52, 'code' => 303),
	5=>array("district_name" => "Quận Kiến An", "be_id" => "150", "main" => 1, 'sendo_id' => 55, 'code' => 307),
	6=>array("district_name" => "Quận Lê Chân", "be_id" => "153", "main" => 1, 'sendo_id' => 53, 'code' => 305),
	7=>array("district_name" => "Quận Ngô Quyền", "be_id" => "152", "main" => 1, 'sendo_id' => 54, 'code' => 304),
	8=>array("district_name" => "Huyện An Dương", "be_id" => "154", "main" => 0, 'sendo_id' => 61, 'code' => 312),
	9=>array("district_name" => "Huyện An Lão", "be_id" => "155", "main" => 0, 'sendo_id' => 58, 'code' => 313),
	10=>array("district_name" => "Huyện Bạch Long Vĩ", "be_id" => "156", "main" => 0, 'sendo_id' => 65, 'code' => 318),
	11=>array("district_name" => "Huyện Cát Hải", "be_id" => "157", "main" => 0, 'sendo_id' => 64, 'code' => 317),
	12=>array("district_name" => "Huyện Kiến Thủy", "be_id" => "158", "main" => 0, 'sendo_id' => 59, 'code' => 314),
	13=>array("district_name" => "Huyện Thủy Nguyên", "be_id" => "161", "main" => 0, 'sendo_id' => 60, 'code' => 311),
	14=>array("district_name" => "Huyện Tiên Lãng", "be_id" => "159", "main" => 0, 'sendo_id' => 62, 'code' => 315),
	15=>array("district_name" => "Huyện Vĩnh Bảo", "be_id" => "160", "main" => 0, 'sendo_id' => 63, 'code' => 316),
	), 
	28 => array(
	1=>array("district_name" => "Thành phố Hòa Bình", "be_id" => "162", "main" => 1, 'sendo_id' => 313, 'code' => 148),
	2=>array("district_name" => "Huyện Lương Sơn", "be_id" => "163", "main" => 0, 'sendo_id' => 319, 'code' => 152),
	3=>array("district_name" => "Huyện Cao Phong", "be_id" => "164", "main" => 0, 'sendo_id' => 343, 'code' => 154),
	4=>array("district_name" => "Huyện Đà Bắc", "be_id" => "165", "main" => 0, 'sendo_id' => 314, 'code' => 150),
	5=>array("district_name" => "Huyện Kim Bôi", "be_id" => "166", "main" => 0, 'sendo_id' => 340, 'code' => 153),
	6=>array("district_name" => "Huyện Kỳ Sơn", "be_id" => "167", "main" => 0, 'sendo_id' => 318, 'code' => 151),
	7=>array("district_name" => "Huyện Lạc Sơn", "be_id" => "168", "main" => 0, 'sendo_id' => 317, 'code' => 157),
	8=>array("district_name" => "Huyện Lạc Thủy", "be_id" => "169", "main" => 0, 'sendo_id' => 341, 'code' => 159),
	9=>array("district_name" => "Huyện Mai Châu", "be_id" => "170", "main" => 0, 'sendo_id' => 315, 'code' => 156),
	10=>array("district_name" => "Huyện Tân Lạc", "be_id" => "172", "main" => 0, 'sendo_id' => 316, 'code' => 155),
	11=>array("district_name" => "Huyện Yên Thủy", "be_id" => "171", "main" => 0, 'sendo_id' => 342, 'code' => 158),
	), 
	29 => array(
	1=>array("district_name" => "Quận 1", "be_id" => "13", "main" => 1, 'sendo_id' => 1, 'code' => 760),
	2=>array("district_name" => "Quận 2", "be_id" => "14", "main" => 1, 'sendo_id' => 2, 'code' => 769),
	3=>array("district_name" => "Quận 3", "be_id" => "15", "main" => 1, 'sendo_id' => 3, 'code' => 770),
	4=>array("district_name" => "Quận 4", "be_id" => "16", "main" => 1, 'sendo_id' => 4, 'code' => 773),
	5=>array("district_name" => "Quận 5", "be_id" => "27", "main" => 1, 'sendo_id' => 5, 'code' => 774),
	6=>array("district_name" => "Quận 6", "be_id" => "18", "main" => 1, 'sendo_id' => 6, 'code' => 775),
	7=>array("district_name" => "Quận 7", "be_id" => "20", "main" => 1, 'sendo_id' => 7, 'code' => 778),
	8=>array("district_name" => "Quận 8", "be_id" => "22", "main" => 1, 'sendo_id' => 8, 'code' => 776),
	9=>array("district_name" => "Quận 9", "be_id" => "24", "main" => 1, 'sendo_id' => 9, 'code' => 763),
	10=>array("district_name" => "Quận 10", "be_id" => "26", "main" => 1, 'sendo_id' => 10, 'code' => 771),
	11=>array("district_name" => "Quận 11", "be_id" => "28", "main" => 1, 'sendo_id' => 11, 'code' => 772),
	12=>array("district_name" => "Quận 12", "be_id" => "30", "main" => 0, 'sendo_id' => 12, 'code' => 761),
	13=>array("district_name" => "Quận Bình Thạnh", "be_id" => "7", "main" => 1, 'sendo_id' => 14, 'code' => 765),
	14=>array("district_name" => "Quận Bình Tân", "be_id" => "6", "main" => 1, 'sendo_id' => 19, 'code' => 777),
	15=>array("district_name" => "Quận Gò Vấp", "be_id" => "8", "main" => 1, 'sendo_id' => 17, 'code' => 764),
	16=>array("district_name" => "Quận Phú Nhuận", "be_id" => "9", "main" => 1, 'sendo_id' => 13, 'code' => 768),
	17=>array("district_name" => "Quận Thủ Đức", "be_id" => "12", "main" => 1, 'sendo_id' => 18, 'code' => 762),
	18=>array("district_name" => "Quận Tân Bình", "be_id" => "10", "main" => 1, 'sendo_id' => 15, 'code' => 766),
	19=>array("district_name" => "Quận Tân Phú", "be_id" => "11", "main" => 1, 'sendo_id' => 16, 'code' => 767),
	20=>array("district_name" => "Huyện Bình Chánh", "be_id" => "1", "main" => 0, 'sendo_id' => 20, 'code' => 785),
	21=>array("district_name" => "Huyện Cần Giờ", "be_id" => "2", "main" => 0, 'sendo_id' => 704, 'code' => 787),
	22=>array("district_name" => "Huyện Củ Chi", "be_id" => "3", "main" => 0, 'sendo_id' => 705, 'code' => 783),
	23=>array("district_name" => "Huyện Hóc Môn", "be_id" => "4", "main" => 0, 'sendo_id' => 703, 'code' => 784),
	24=>array("district_name" => "Huyện Nhà Bè", "be_id" => "5", "main" => 0, 'sendo_id' => 713, 'code' => 786),
	), 
	30 => array(
	1=>array("district_name" => "Thành phố Hưng Yên", "be_id" => "173", "main" => 1, 'sendo_id' => 344, 'code' => 323),
	2=>array("district_name" => "Huyện Ân Thi", "be_id" => "174", "main" => 0, 'sendo_id' => 346, 'code' => 329),
	3=>array("district_name" => "Huyện Khoái Châu", "be_id" => "175", "main" => 0, 'sendo_id' => 347, 'code' => 330),
	4=>array("district_name" => "Huyện Kim Động", "be_id" => "176", "main" => 0, 'sendo_id' => 345, 'code' => 331),
	5=>array("district_name" => "Huyện Mỹ Hào", "be_id" => "177", "main" => 0, 'sendo_id' => 351, 'code' => 328),
	6=>array("district_name" => "Huyện Phù Cừ", "be_id" => "178", "main" => 0, 'sendo_id' => 350, 'code' => 333),
	7=>array("district_name" => "Huyện Tiên Lữ", "be_id" => "179", "main" => 0, 'sendo_id' => 349, 'code' => 332),
	8=>array("district_name" => "Huyện Van Giang", "be_id" => "180", "main" => 0, 'sendo_id' => 353, 'code' => 326),
	9=>array("district_name" => "Huyện Văn Lâm", "be_id" => "181", "main" => 0, 'sendo_id' => 352, 'code' => 325),
	10=>array("district_name" => "Huyện Yên Mỹ", "be_id" => "182", "main" => 0, 'sendo_id' => 348, 'code' => 327),
	), 
	31 => array(
	1=>array("district_name" => "Thành phố Nha Trang", "be_id" => "548", "main" => 0, 'sendo_id' => 354, 'code' => 568),
	2=>array("district_name" => "Huyện Vạn Ninh", "be_id" => "556", "main" => 0, 'sendo_id' => 355, 'code' => 571),
	3=>array("district_name" => "Huyện Ninh Hòa", "be_id" => "550", "main" => 0, 'sendo_id' => 356, 'code' => 572),
	4=>array("district_name" => "Huyện Diên Khánh", "be_id" => "552", "main" => 0, 'sendo_id' => 357, 'code' => 574),
	5=>array("district_name" => "Huyện Cam Lâm", "be_id" => "551", "main" => 0, 'sendo_id' => 731, 'code' => 570),
	6=>array("district_name" => "Thị xã Cam Ranh", "be_id" => "549", "main" => 0, 'sendo_id' => 359, 'code' => 569),
	7=>array("district_name" => "Huyện Khánh Vĩnh", "be_id" => "554", "main" => 0, 'sendo_id' => 358, 'code' => 573),
	8=>array("district_name" => "Huyện Khánh Sơn", "be_id" => "553", "main" => 0, 'sendo_id' => 360, 'code' => 575),
	9=>array("district_name" => "Huyện đảo Trường Sa", "be_id" => "555", "main" => 0, 'sendo_id' => 361, 'code' => 576),
	), 
	32 => array(
	1=>array("district_name" => "Thành phố Rạch Giá", "be_id" => "557", "main" => 1, 'sendo_id' => 362, 'code' => 899),
	2=>array("district_name" => "Thị xã Hà Tiên", "be_id" => "558", "main" => 0, 'sendo_id' => 363, 'code' => 900),
	3=>array("district_name" => "Huyện An Biên", "be_id" => "559", "main" => 0, 'sendo_id' => 370, 'code' => 908),
	4=>array("district_name" => "Huyện An Minh", "be_id" => "560", "main" => 0, 'sendo_id' => 371, 'code' => 909),
	5=>array("district_name" => "Huyện Châu Thành", "be_id" => "561", "main" => 0, 'sendo_id' => 367, 'code' => 905),
	6=>array("district_name" => "Huyện Giồng Riềng", "be_id" => "563", "main" => 0, 'sendo_id' => 368, 'code' => 906),
	7=>array("district_name" => "Huyện Gò Quao", "be_id" => "564", "main" => 0, 'sendo_id' => 369, 'code' => 907),
	8=>array("district_name" => "Huyện Hòn Đất", "be_id" => "565", "main" => 0, 'sendo_id' => 365, 'code' => 903),
	9=>array("district_name" => "Huyện Kiên Hải", "be_id" => "566", "main" => 0, 'sendo_id' => 374, 'code' => 912),
	10=>array("district_name" => "Huyện Kiên Lương", "be_id" => "567", "main" => 0, 'sendo_id' => 364, 'code' => 902),
	11=>array("district_name" => "Huyện Phú Quốc", "be_id" => "568", "main" => 0, 'sendo_id' => 373, 'code' => 911),
	12=>array("district_name" => "Huyện Tân Hiệp", "be_id" => "569", "main" => 0, 'sendo_id' => 366, 'code' => 904),
	13=>array("district_name" => "Huyện Vĩnh Thuận", "be_id" => "571", "main" => 0, 'sendo_id' => 372, 'code' => 910),
	14=>array("district_name" => "Huyện U Minh Thượng", "be_id" => "570", "main" => 0, 'sendo_id' => 732, 'code' => 913),
	), 
	33 => array(
	1=>array("district_name" => "Thành phố Kon Tum", "be_id" => "572", "main" => 1, 'sendo_id' => 375, 'code' => 608),
	2=>array("district_name" => "Huyện Đắk Glei", "be_id" => "573", "main" => 0, 'sendo_id' => 376, 'code' => 610),
	3=>array("district_name" => "Huyện Đắk Hà", "be_id" => "574", "main" => 0, 'sendo_id' => 381, 'code' => 615),
	4=>array("district_name" => "Huyện Đắk Tô", "be_id" => "575", "main" => 0, 'sendo_id' => 378, 'code' => 612),
	5=>array("district_name" => "Huyện Kon Plông", "be_id" => "576", "main" => 0, 'sendo_id' => 380, 'code' => 613),
	6=>array("district_name" => "Huyện Kon Rẫy", "be_id" => "577", "main" => 0, 'sendo_id' => 382, 'code' => 614),
	7=>array("district_name" => "Huyện Ngọc Hồi", "be_id" => "579", "main" => 0, 'sendo_id' => 377, 'code' => 611),
	8=>array("district_name" => "Huyện Sa Thầy", "be_id" => "580", "main" => 0, 'sendo_id' => 379, 'code' => 616),
	9=>array("district_name" => "Huyện Tu Mơ Rông", "be_id" => "578", "main" => 0, 'sendo_id' => 383, 'code' => 617),
	), 
	34 => array(
	1=>array("district_name" => "Thị xã Lai Châu", "be_id" => "183", "main" => 0, 'sendo_id' => 384, 'code' => 105),
	2=>array("district_name" => "Huyện Mường Tè", "be_id" => "184", "main" => 0, 'sendo_id' => 388, 'code' => 107),
	3=>array("district_name" => "Huyện Phong Thổ", "be_id" => "185", "main" => 0, 'sendo_id' => 386, 'code' => 109),
	4=>array("district_name" => "Huyện Sìn Hồ", "be_id" => "186", "main" => 0, 'sendo_id' => 387, 'code' => 108),
	5=>array("district_name" => "Huyện Tam Đường", "be_id" => "187", "main" => 0, 'sendo_id' => 385, 'code' => 106),
	6=>array("district_name" => "Huyện Than Uyên", "be_id" => "188", "main" => 0, 'sendo_id' => 389, 'code' => 110),
	7=>array("district_name" => "Huyện Tân Uyên", "be_id" => "189", "main" => 0, 'sendo_id' => 714, 'code' => 111),
	), 
	35 => array(
	1=>array("district_name" => "Thành phố Lạng Sơn", "be_id" => "190", "main" => 1, 'sendo_id' => 411, 'code' => 178),
	2=>array("district_name" => "Huyện Tràng Định", "be_id" => "191", "main" => 0, 'sendo_id' => 412, 'code' => 180),
	3=>array("district_name" => "Huyện Văn Lãng", "be_id" => "192", "main" => 0, 'sendo_id' => 414, 'code' => 182),
	4=>array("district_name" => "Huyện Văn Quan", "be_id" => "193", "main" => 0, 'sendo_id' => 416, 'code' => 184),
	5=>array("district_name" => "Huyện Bình Gia", "be_id" => "194", "main" => 0, 'sendo_id' => 413, 'code' => 181),
	6=>array("district_name" => "Huyện Bắc Sơn", "be_id" => "195", "main" => 0, 'sendo_id' => 415, 'code' => 185),
	7=>array("district_name" => "Huyện Hữu Lũng", "be_id" => "196", "main" => 0, 'sendo_id' => 421, 'code' => 186),
	8=>array("district_name" => "Huyện Chi Lăng", "be_id" => "197", "main" => 0, 'sendo_id' => 419, 'code' => 187),
	9=>array("district_name" => "Huyện Cao Lộc", "be_id" => "198", "main" => 0, 'sendo_id' => 417, 'code' => 183),
	10=>array("district_name" => "Huyện Lộc Bình", "be_id" => "199", "main" => 0, 'sendo_id' => 418, 'code' => 188),
	11=>array("district_name" => "Huyện Đình Lập", "be_id" => "200", "main" => 0, 'sendo_id' => 420, 'code' => 189),
	), 
	36 => array(
	1=>array("district_name" => "Thành phố Lào Cai", "be_id" => "201", "main" => 1, 'sendo_id' => 390, 'code' => 80),
	2=>array("district_name" => "Huyện Bảo Thắng", "be_id" => "202", "main" => 0, 'sendo_id' => 393, 'code' => 86),
	3=>array("district_name" => "Huyện Bảo Yên", "be_id" => "203", "main" => 0, 'sendo_id' => 396, 'code' => 87),
	4=>array("district_name" => "Huyện Bát Xát", "be_id" => "204", "main" => 0, 'sendo_id' => 392, 'code' => 82),
	5=>array("district_name" => "Huyện Bắc Hà", "be_id" => "205", "main" => 0, 'sendo_id' => 397, 'code' => 85),
	6=>array("district_name" => "Huyện Mường Khương", "be_id" => "206", "main" => 0, 'sendo_id' => 398, 'code' => 83),
	7=>array("district_name" => "Huyện Sa Pa", "be_id" => "207", "main" => 0, 'sendo_id' => 394, 'code' => 88),
	8=>array("district_name" => "Huyện Si Ma Cai", "be_id" => "208", "main" => 0, 'sendo_id' => 391, 'code' => 84),
	9=>array("district_name" => "Huyện Văn Bàn", "be_id" => "209", "main" => 0, 'sendo_id' => 395, 'code' => 89),
	), 
	37 => array(
	1=>array("district_name" => "Thành phố Đà Lạt", "be_id" => "581", "main" => 1, 'sendo_id' => 399, 'code' => 672),
	2=>array("district_name" => "Thành phố Bảo Lộc", "be_id" => "582", "main" => 1, 'sendo_id' => 400, 'code' => 673),
	3=>array("district_name" => "Huyện Lạc Dương", "be_id" => "591", "main" => 0, 'sendo_id' => 404, 'code' => 675),
	4=>array("district_name" => "Huyện Đơn Dương", "be_id" => "589", "main" => 0, 'sendo_id' => 403, 'code' => 677),
	5=>array("district_name" => "Huyện Đức Trọng", "be_id" => "590", "main" => 0, 'sendo_id' => 401, 'code' => 678),
	6=>array("district_name" => "Huyện Lâm Hà", "be_id" => "592", "main" => 0, 'sendo_id' => 408, 'code' => 676),
	7=>array("district_name" => "Huyện Bảo Lâm", "be_id" => "583", "main" => 0, 'sendo_id' => 409, 'code' => 680),
	8=>array("district_name" => "Huyện Di Linh", "be_id" => "588", "main" => 0, 'sendo_id' => 402, 'code' => 679),
	9=>array("district_name" => "Huyện Đạ Huoai", "be_id" => "585", "main" => 0, 'sendo_id' => 405, 'code' => 681),
	10=>array("district_name" => "Huyện Đạ Tẻh", "be_id" => "586", "main" => 0, 'sendo_id' => 406, 'code' => 682),
	11=>array("district_name" => "Huyện Cát Tiên", "be_id" => "584", "main" => 0, 'sendo_id' => 407, 'code' => 683),
	12=>array("district_name" => "Huyện Đam Rông", "be_id" => "587", "main" => 0, 'sendo_id' => 410, 'code' => 674),
	), 
	38 => array(
	1=>array("district_name" => "Thành phố Tân An", "be_id" => "593", "main" => 1, 'sendo_id' => 422, 'code' => 794),
	2=>array("district_name" => "Huyện Bến Lức", "be_id" => "594", "main" => 0, 'sendo_id' => 429, 'code' => 803),
	3=>array("district_name" => "Huyện Cần Đước", "be_id" => "595", "main" => 0, 'sendo_id' => 433, 'code' => 806),
	4=>array("district_name" => "Huyện Cần Giuộc", "be_id" => "596", "main" => 0, 'sendo_id' => 434, 'code' => 807),
	5=>array("district_name" => "Huyện Châu Thành", "be_id" => "597", "main" => 0, 'sendo_id' => 431, 'code' => 808),
	6=>array("district_name" => "Huyện Đức Hòa", "be_id" => "598", "main" => 0, 'sendo_id' => 428, 'code' => 802),
	7=>array("district_name" => "Huyện Đức Huệ", "be_id" => "599", "main" => 0, 'sendo_id' => 427, 'code' => 801),
	8=>array("district_name" => "Huyện Mộc Hóa", "be_id" => "600", "main" => 0, 'sendo_id' => 424, 'code' => 798),
	9=>array("district_name" => "Huyện Tân Hưng", "be_id" => "601", "main" => 0, 'sendo_id' => 435, 'code' => 796),
	10=>array("district_name" => "Huyện Tân Thành", "be_id" => "602", "main" => 0, 'sendo_id' => 425, 'code' => 799),
	11=>array("district_name" => "Huyện Tân Trụ", "be_id" => "603", "main" => 0, 'sendo_id' => 432, 'code' => 805),
	12=>array("district_name" => "Huyện Thạnh Hoa", "be_id" => "604", "main" => 0, 'sendo_id' => 426, 'code' => 800),
	13=>array("district_name" => "Huyện Thủ Thừa", "be_id" => "605", "main" => 0, 'sendo_id' => 430, 'code' => 804),
	14=>array("district_name" => "Huyện Vĩnh Hưng", "be_id" => "606", "main" => 0, 'sendo_id' => 423, 'code' => 797),
	), 
	39 => array(
	1=>array("district_name" => "Thành phố Nam Định", "be_id" => "210", "main" => 1, 'sendo_id' => 454, 'code' => 356),
	2=>array("district_name" => "Huyện Giao Thủy", "be_id" => "211", "main" => 0, 'sendo_id' => 457, 'code' => 365),
	3=>array("district_name" => "Huyện Hải Hậu", "be_id" => "212", "main" => 0, 'sendo_id' => 463, 'code' => 366),
	4=>array("district_name" => "Huyện Mỹ Lộc", "be_id" => "213", "main" => 0, 'sendo_id' => 455, 'code' => 358),
	5=>array("district_name" => "Huyện Nam Trực", "be_id" => "214", "main" => 0, 'sendo_id' => 460, 'code' => 362),
	6=>array("district_name" => "Huyện Nghĩa Hưng", "be_id" => "215", "main" => 0, 'sendo_id' => 462, 'code' => 361),
	7=>array("district_name" => "Huyện Trực Ninh", "be_id" => "216", "main" => 0, 'sendo_id' => 461, 'code' => 363),
	8=>array("district_name" => "Huyện Vụ Bản", "be_id" => "217", "main" => 0, 'sendo_id' => 459, 'code' => 359),
	9=>array("district_name" => "Huyện Xuân Trường", "be_id" => "218", "main" => 0, 'sendo_id' => 456, 'code' => 364),
	10=>array("district_name" => "Huyện Ý Yên", "be_id" => "219", "main" => 0, 'sendo_id' => 458, 'code' => 360),
	), 
	40 => array(
	1=>array("district_name" => "Thành phố Vinh", "be_id" => "350", "main" => 1, 'sendo_id' => 464, 'code' => 412),
	2=>array("district_name" => "Thị xã Cửa Lò", "be_id" => "351", "main" => 0, 'sendo_id' => 465, 'code' => 413),
	3=>array("district_name" => "Thị xã Thái Hòa", "be_id" => "352", "main" => 0, 'sendo_id' => 736, 'code' => 414),
	4=>array("district_name" => "Huyện Anh Sơn", "be_id" => "353", "main" => 0, 'sendo_id' => 476, 'code' => 424),
	5=>array("district_name" => "Huyện Con Cuông", "be_id" => "354", "main" => 0, 'sendo_id' => 472, 'code' => 422),
	6=>array("district_name" => "Huyện Diễn Châu", "be_id" => "355", "main" => 0, 'sendo_id' => 475, 'code' => 425),
	7=>array("district_name" => "Huyện Đô Lương", "be_id" => "356", "main" => 0, 'sendo_id' => 477, 'code' => 427),
	8=>array("district_name" => "Huyện Hưng Nguyên", "be_id" => "357", "main" => 0, 'sendo_id' => 481, 'code' => 431),
	9=>array("district_name" => "Huyện Qùy Châu", "be_id" => "358", "main" => 0, 'sendo_id' => 466, 'code' => 416),
	10=>array("district_name" => "Huyện Kỳ Sơn", "be_id" => "359", "main" => 0, 'sendo_id' => 470, 'code' => 417),
	11=>array("district_name" => "Huyện Nam Đàn", "be_id" => "360", "main" => 0, 'sendo_id' => 480, 'code' => 430),
	12=>array("district_name" => "Huyện Nghi Lộc", "be_id" => "361", "main" => 0, 'sendo_id' => 479, 'code' => 429),
	13=>array("district_name" => "Huyện Nghĩa Đàn", "be_id" => "362", "main" => 0, 'sendo_id' => 468, 'code' => 419),
	14=>array("district_name" => "Huyện Quế Phong", "be_id" => "363", "main" => 0, 'sendo_id' => 482, 'code' => 415),
	15=>array("district_name" => "Huyện Qùy Hợp", "be_id" => "364", "main" => 0, 'sendo_id' => 467, 'code' => 420),
	16=>array("district_name" => "Huyện Quỳnh Lưu", "be_id" => "365", "main" => 0, 'sendo_id' => 469, 'code' => 421),
	17=>array("district_name" => "Huyện Tân Kỳ", "be_id" => "366", "main" => 0, 'sendo_id' => 473, 'code' => 423),
	18=>array("district_name" => "Huyện Thanh Chương", "be_id" => "367", "main" => 0, 'sendo_id' => 478, 'code' => 428),
	19=>array("district_name" => "Huyện Tương Dương", "be_id" => "368", "main" => 0, 'sendo_id' => 471, 'code' => 418),
	20=>array("district_name" => "Huyện Yên Thành", "be_id" => "369", "main" => 0, 'sendo_id' => 474, 'code' => 426),
	), 
	41 => array(
	1=>array("district_name" => "Thành phố Ninh Bình", "be_id" => "220", "main" => 1, 'sendo_id' => 436, 'code' => 369),
	2=>array("district_name" => "Thị xã Tam Điệp", "be_id" => "221", "main" => 0, 'sendo_id' => 437, 'code' => 370),
	3=>array("district_name" => "Huyện Gia Viễn", "be_id" => "222", "main" => 0, 'sendo_id' => 439, 'code' => 373),
	4=>array("district_name" => "Huyện Hoa Lư", "be_id" => "223", "main" => 0, 'sendo_id' => 450, 'code' => 374),
	5=>array("district_name" => "Huyện Kim Sơn", "be_id" => "224", "main" => 0, 'sendo_id' => 452, 'code' => 376),
	6=>array("district_name" => "Huyện Nho Quan", "be_id" => "225", "main" => 0, 'sendo_id' => 438, 'code' => 372),
	7=>array("district_name" => "Huyện Yên Khánh", "be_id" => "226", "main" => 0, 'sendo_id' => 453, 'code' => 375),
	8=>array("district_name" => "Huyện Yên Mô", "be_id" => "227", "main" => 0, 'sendo_id' => 451, 'code' => 377),
	), 
	42 => array(
	1=>array("district_name" => "Thành phố Phan Rang-Tháp Chàm", "be_id" => "607", "main" => 1, 'sendo_id' => 483, 'code' => 582),
	2=>array("district_name" => "Huyện Bác Ái", "be_id" => "608", "main" => 0, 'sendo_id' => 487, 'code' => 584),
	3=>array("district_name" => "Huyện Ninh Hải", "be_id" => "609", "main" => 0, 'sendo_id' => 485, 'code' => 586),
	4=>array("district_name" => "Huyện Ninh Phước", "be_id" => "610", "main" => 0, 'sendo_id' => 486, 'code' => 587),
	5=>array("district_name" => "Huyện Ninh Sơn", "be_id" => "611", "main" => 0, 'sendo_id' => 484, 'code' => 585),
	6=>array("district_name" => "Huyện Thuận Bắc", "be_id" => "612", "main" => 0, 'sendo_id' => 488, 'code' => 588),
	7=>array("district_name" => "Huyện Thuận Nam", "be_id" => "613", "main" => 0, 'sendo_id' => 738, 'code' => 589),
	), 
	43 => array(
	1=>array("district_name" => "Thành phố Việt Trì", "be_id" => "228", "main" => 1, 'sendo_id' => 232, 'code' => 227),
	2=>array("district_name" => "Thị xã Phú Thọ", "be_id" => "229", "main" => 0, 'sendo_id' => 233, 'code' => 228),
	3=>array("district_name" => "Huyện Cẩm Khê", "be_id" => "230", "main" => 0, 'sendo_id' => 237, 'code' => 235),
	4=>array("district_name" => "Huyện Đoan Hùng", "be_id" => "231", "main" => 0, 'sendo_id' => 234, 'code' => 230),
	5=>array("district_name" => "Huyện Hạ Hòa", "be_id" => "232", "main" => 0, 'sendo_id' => 236, 'code' => 231),
	6=>array("district_name" => "Huyện Lâm Thao", "be_id" => "233", "main" => 0, 'sendo_id' => 241, 'code' => 237),
	7=>array("district_name" => "Huyện Phù Ninh", "be_id" => "234", "main" => 0, 'sendo_id' => 240, 'code' => 233),
	8=>array("district_name" => "Huyện Tam Nông", "be_id" => "235", "main" => 0, 'sendo_id' => 242, 'code' => 236),
	9=>array("district_name" => "Huyện Tân Sơn", "be_id" => "236", "main" => 0, 'sendo_id' => 734, 'code' => 240),
	10=>array("district_name" => "Huyện Thanh Ba", "be_id" => "237", "main" => 0, 'sendo_id' => 235, 'code' => 232),
	11=>array("district_name" => "Huyện Thanh Sơn", "be_id" => "238", "main" => 0, 'sendo_id' => 239, 'code' => 238),
	12=>array("district_name" => "Huyện Thanh Thủy", "be_id" => "239", "main" => 0, 'sendo_id' => 243, 'code' => 239),
	13=>array("district_name" => "Huyện Yên Lập", "be_id" => "240", "main" => 0, 'sendo_id' => 238, 'code' => 234),
	), 
	44 => array(
	1=>array("district_name" => "Thành phố Tuy Hòa", "be_id" => "614", "main" => 1, 'sendo_id' => 503, 'code' => 555),
	2=>array("district_name" => "Thị xã Sông Cầu", "be_id" => "615", "main" => 0, 'sendo_id' => 505, 'code' => 557),
	3=>array("district_name" => "Huyện Đông Hòa", "be_id" => "616", "main" => 0, 'sendo_id' => 509, 'code' => 564),
	4=>array("district_name" => "Huyện Đồng Xuân", "be_id" => "617", "main" => 0, 'sendo_id' => 504, 'code' => 558),
	5=>array("district_name" => "Huyện Phú Hòa", "be_id" => "618", "main" => 0, 'sendo_id' => 510, 'code' => 563),
	6=>array("district_name" => "Huyện Sơn Hòa", "be_id" => "619", "main" => 0, 'sendo_id' => 507, 'code' => 560),
	7=>array("district_name" => "Huyện Sông Hinh", "be_id" => "620", "main" => 0, 'sendo_id' => 508, 'code' => 561),
	8=>array("district_name" => "Huyện Tây Hòa", "be_id" => "621", "main" => 0, 'sendo_id' => 511, 'code' => 562),
	9=>array("district_name" => "Huyện Tuy An", "be_id" => "622", "main" => 0, 'sendo_id' => 506, 'code' => 559),
	), 
	45 => array(
	1=>array("district_name" => "Thành phố Đồng Hới", "be_id" => "370", "main" => 1, 'sendo_id' => 512, 'code' => 450),
	2=>array("district_name" => "Huyện Bố Trạch", "be_id" => "371", "main" => 0, 'sendo_id' => 516, 'code' => 455),
	3=>array("district_name" => "Huyện Lệ Thủy", "be_id" => "373", "main" => 0, 'sendo_id' => 518, 'code' => 457),
	4=>array("district_name" => "Huyện Minh Hóa", "be_id" => "374", "main" => 0, 'sendo_id' => 514, 'code' => 452),
	5=>array("district_name" => "Huyện Quảng Trạch", "be_id" => "372", "main" => 0, 'sendo_id' => 515, 'code' => 454),
	6=>array("district_name" => "Huyện Quảng Ninh", "be_id" => "375", "main" => 0, 'sendo_id' => 517, 'code' => 456),
	7=>array("district_name" => "Huyện Tuyên Hóa", "be_id" => "376", "main" => 0, 'sendo_id' => 513, 'code' => 453),
	), 
	46 => array(
	1=>array("district_name" => "Thành phố Tam Kỳ", "be_id" => "624", "main" => 1, 'sendo_id' => 519, 'code' => 502),
	2=>array("district_name" => "Thành phố Hội An", "be_id" => "623", "main" => 1, 'sendo_id' => 520, 'code' => 503),
	3=>array("district_name" => "Huyện Điện Bàn", "be_id" => "627", "main" => 0, 'sendo_id' => 522, 'code' => 507),
	4=>array("district_name" => "Huyện Thăng Bình", "be_id" => "639", "main" => 0, 'sendo_id' => 526, 'code' => 513),
	5=>array("district_name" => "Huyện Bắc Trà My", "be_id" => "625", "main" => 0, 'sendo_id' => 529, 'code' => 515),
	6=>array("district_name" => "Huyện Nam Trà My", "be_id" => "632", "main" => 0, 'sendo_id' => 533, 'code' => 516),
	7=>array("district_name" => "Huyện Núi Thành", "be_id" => "634", "main" => 0, 'sendo_id' => 527, 'code' => 517),
	8=>array("district_name" => "Huyện Phước Sơn", "be_id" => "636", "main" => 0, 'sendo_id' => 532, 'code' => 511),
	9=>array("district_name" => "Huyện Tiên Phước", "be_id" => "640", "main" => 0, 'sendo_id' => 528, 'code' => 514),
	10=>array("district_name" => "Huyện Hiệp Đức", "be_id" => "630", "main" => 0, 'sendo_id' => 525, 'code' => 512),
	11=>array("district_name" => "Huyện Nông Sơn", "be_id" => "633", "main" => 0, 'sendo_id' => 737, 'code' => 519),
	12=>array("district_name" => "Huyện Đông Giang", "be_id" => "628", "main" => 0, 'sendo_id' => 530, 'code' => 505),
	13=>array("district_name" => "Huyện Nam Giang", "be_id" => "631", "main" => 0, 'sendo_id' => 531, 'code' => 510),
	14=>array("district_name" => "Huyện Đại Lộc", "be_id" => "626", "main" => 0, 'sendo_id' => 523, 'code' => 506),
	15=>array("district_name" => "Huyện Phú Ninh", "be_id" => "635", "main" => 0, 'sendo_id' => 535, 'code' => 518),
	16=>array("district_name" => "Huyện Tây Giang", "be_id" => "638", "main" => 0, 'sendo_id' => 534, 'code' => 504),
	17=>array("district_name" => "Huyện Duy Xuyên", "be_id" => "629", "main" => 0, 'sendo_id' => 521, 'code' => 508),
	18=>array("district_name" => "Huyện Quế Sơn", "be_id" => "637", "main" => 0, 'sendo_id' => 524, 'code' => 509),
	), 
	47 => array(
	1=>array("district_name" => "Thành phố Quảng Ngãi", "be_id" => "641", "main" => 1, 'sendo_id' => 536, 'code' => 522),
	2=>array("district_name" => "Huyện Ba Tơ", "be_id" => "642", "main" => 0, 'sendo_id' => 547, 'code' => 535),
	3=>array("district_name" => "Huyện Bình Sơn", "be_id" => "643", "main" => 0, 'sendo_id' => 538, 'code' => 524),
	4=>array("district_name" => "Huyện Đức Phổ", "be_id" => "644", "main" => 0, 'sendo_id' => 546, 'code' => 534),
	5=>array("district_name" => "Huyện Minh Long", "be_id" => "646", "main" => 0, 'sendo_id' => 544, 'code' => 531),
	6=>array("district_name" => "Huyện Mộ Đức", "be_id" => "647", "main" => 0, 'sendo_id' => 545, 'code' => 533),
	7=>array("district_name" => "Huyện Nghĩa Hành", "be_id" => "648", "main" => 0, 'sendo_id' => 543, 'code' => 532),
	8=>array("district_name" => "Huyện Sơn Hà", "be_id" => "649", "main" => 0, 'sendo_id' => 541, 'code' => 529),
	9=>array("district_name" => "Huyện Sơn Tây", "be_id" => "650", "main" => 0, 'sendo_id' => 548, 'code' => 530),
	10=>array("district_name" => "Huyện Sơn Tịnh", "be_id" => "651", "main" => 0, 'sendo_id' => 540, 'code' => 527),
	11=>array("district_name" => "Huyện Tây Trà", "be_id" => "652", "main" => 0, 'sendo_id' => 549, 'code' => 526),
	12=>array("district_name" => "Huyện Trà Bồng", "be_id" => "653", "main" => 0, 'sendo_id' => 539, 'code' => 525),
	13=>array("district_name" => "Huyện Tư Nghĩa", "be_id" => "654", "main" => 0, 'sendo_id' => 542, 'code' => 528),
	14=>array("district_name" => "Huyện dao Lý Sơn", "be_id" => "645", "main" => 0, 'sendo_id' => 537, 'code' => 536),
	), 
	48 => array(
	1=>array("district_name" => "Thành phố Hạ Long", "be_id" => "241", "main" => 1, 'sendo_id' => 489, 'code' => 193),
	2=>array("district_name" => "Thành phố Móng Cái", "be_id" => "242", "main" => 1, 'sendo_id' => 492, 'code' => 194),
	3=>array("district_name" => "Thành phố Uông Bí", "be_id" => "243", "main" => 1, 'sendo_id' => 491, 'code' => 196),
	4=>array("district_name" => "Thị xã Cẩm Phả", "be_id" => "244", "main" => 0, 'sendo_id' => 490, 'code' => 195),
	5=>array("district_name" => "Huyện Ba Chẽ", "be_id" => "246", "main" => 0, 'sendo_id' => 497, 'code' => 202),
	6=>array("district_name" => "Huyện Bình Liêu", "be_id" => "247", "main" => 0, 'sendo_id' => 493, 'code' => 198),
	7=>array("district_name" => "Huyện Cô Tô", "be_id" => "248", "main" => 0, 'sendo_id' => 502, 'code' => 207),
	8=>array("district_name" => "Huyện Đầm Hà", "be_id" => "249", "main" => 0, 'sendo_id' => 494, 'code' => 200),
	9=>array("district_name" => "Huyện Đông Triều", "be_id" => "250", "main" => 0, 'sendo_id' => 498, 'code' => 205),
	10=>array("district_name" => "Huyện Hải Hà", "be_id" => "251", "main" => 0, 'sendo_id' => 495, 'code' => 201),
	11=>array("district_name" => "Huyện Hoành Bồ", "be_id" => "252", "main" => 0, 'sendo_id' => 500, 'code' => 204),
	12=>array("district_name" => "Huyện Tiên Yên", "be_id" => "253", "main" => 0, 'sendo_id' => 496, 'code' => 199),
	13=>array("district_name" => "Huyện Vân Đồn", "be_id" => "254", "main" => 0, 'sendo_id' => 501, 'code' => 203),
	//14=>array("district_name" => "Huyện Yên Hung", "be_id" => "255", "main" => 0, 'sendo_id' => 0, 'code' => 0),
	), 
	49 => array(
	1=>array("district_name" => "Thành phố Đông Hà", "be_id" => "377", "main" => 1, 'sendo_id' => 561, 'code' => 461),
	2=>array("district_name" => "Thị xã Quảng Trị", "be_id" => "378", "main" => 0, 'sendo_id' => 562, 'code' => 462),
	3=>array("district_name" => "Huyện Cam Lộ", "be_id" => "380", "main" => 0, 'sendo_id' => 565, 'code' => 468),
	4=>array("district_name" => "Huyện Đảo Cồn Cỏ", "be_id" => "381", "main" => 0, 'sendo_id' => 570, 'code' => 471),
	5=>array("district_name" => "Huyện Đa Krông", "be_id" => "386", "main" => 0, 'sendo_id' => 569, 'code' => 467),
	6=>array("district_name" => "Huyện Gio Linh", "be_id" => "382", "main" => 0, 'sendo_id' => 564, 'code' => 466),
	7=>array("district_name" => "Huyện Hải Lăng", "be_id" => "383", "main" => 0, 'sendo_id' => 567, 'code' => 470),
	8=>array("district_name" => "Huyện Hướng Hóa", "be_id" => "379", "main" => 0, 'sendo_id' => 568, 'code' => 465),
	9=>array("district_name" => "Huyện Triệu Phong", "be_id" => "384", "main" => 0, 'sendo_id' => 566, 'code' => 469),
	10=>array("district_name" => "Huyện Vĩnh Linh", "be_id" => "385", "main" => 0, 'sendo_id' => 563, 'code' => 464),
	), 
	51 => array(
	1=>array("district_name" => "Thành phố Sóc Trăng", "be_id" => "655", "main" => 1, 'sendo_id' => 571, 'code' => 941),
	2=>array("district_name" => "Huyện Cù Lao Dung", "be_id" => "657", "main" => 0, 'sendo_id' => 578, 'code' => 945),
	3=>array("district_name" => "Huyện Kế Sách", "be_id" => "658", "main" => 0, 'sendo_id' => 572, 'code' => 943),
	4=>array("district_name" => "Huyện Long Phú", "be_id" => "659", "main" => 0, 'sendo_id' => 576, 'code' => 946),
	5=>array("district_name" => "Huyện Mỹ Tú", "be_id" => "660", "main" => 0, 'sendo_id' => 573, 'code' => 944),
	6=>array("district_name" => "Huyện Mỹ Xuyên", "be_id" => "661", "main" => 0, 'sendo_id' => 574, 'code' => 947),
	7=>array("district_name" => "Huyện Ngã Năm", "be_id" => "662", "main" => 0, 'sendo_id' => 742, 'code' => 948),
	8=>array("district_name" => "Huyện Thạnh Trị", "be_id" => "663", "main" => 0, 'sendo_id' => 575, 'code' => 949),
	9=>array("district_name" => "Huyện Vĩnh Châu", "be_id" => "665", "main" => 0, 'sendo_id' => 577, 'code' => 950),
	10=>array("district_name" => "Huyện Châu Thành", "be_id" => "656", "main" => 0, 'sendo_id' => 741, 'code' => 942),
	11=>array("district_name" => "Huyện Trần Đề", "be_id" => "664", "main" => 0, 'sendo_id' => 743, 'code' => 951),
	), 
	50 => array(
	1=>array("district_name" => "Thành phố Sơn La", "be_id" => "256", "main" => 1, 'sendo_id' => 580, 'code' => 116),
	2=>array("district_name" => "Huyện Quỳnh Nhai", "be_id" => "257", "main" => 0, 'sendo_id' => 581, 'code' => 118),
	3=>array("district_name" => "Huyện Mường La", "be_id" => "258", "main" => 0, 'sendo_id' => 582, 'code' => 120),
	4=>array("district_name" => "Huyện Thuận Châu", "be_id" => "259", "main" => 0, 'sendo_id' => 583, 'code' => 119),
	5=>array("district_name" => "Huyện Phú Yên", "be_id" => "260", "main" => 0, 'sendo_id' => 584, 'code' => 121),
	6=>array("district_name" => "Huyện Bắc Yên", "be_id" => "261", "main" => 0, 'sendo_id' => 585, 'code' => 122),
	7=>array("district_name" => "Huyện Mai Sơn", "be_id" => "262", "main" => 0, 'sendo_id' => 586, 'code' => 125),
	8=>array("district_name" => "Huyện Sông Mã", "be_id" => "263", "main" => 0, 'sendo_id' => 588, 'code' => 126),
	9=>array("district_name" => "Huyện Yên Châu", "be_id" => "264", "main" => 0, 'sendo_id' => 587, 'code' => 124),
	10=>array("district_name" => "Huyện Mộc Châu", "be_id" => "265", "main" => 0, 'sendo_id' => 589, 'code' => 123),
	11=>array("district_name" => "Huyện Sốp Cộp", "be_id" => "266", "main" => 0, 'sendo_id' => 590, 'code' => 127),
	), 
	52 => array(
	1=>array("district_name" => "Thị xã Tây Ninh", "be_id" => "666", "main" => 0, 'sendo_id' => 591, 'code' => 703),
	2=>array("district_name" => "Huyện Tân Biên", "be_id" => "672", "main" => 0, 'sendo_id' => 592, 'code' => 705),
	3=>array("district_name" => "Huyện Tân Châu", "be_id" => "673", "main" => 0, 'sendo_id' => 593, 'code' => 706),
	4=>array("district_name" => "Huyện Dương Minh Châu", "be_id" => "669", "main" => 0, 'sendo_id' => 594, 'code' => 707),
	5=>array("district_name" => "Huyện Châu Thành", "be_id" => "668", "main" => 0, 'sendo_id' => 595, 'code' => 708),
	6=>array("district_name" => "Huyện Hòa Thành", "be_id" => "671", "main" => 0, 'sendo_id' => 596, 'code' => 709),
	7=>array("district_name" => "Huyện Bến Cầu", "be_id" => "667", "main" => 0, 'sendo_id' => 597, 'code' => 711),
	8=>array("district_name" => "Huyện Gò Dầu", "be_id" => "670", "main" => 0, 'sendo_id' => 598, 'code' => 710),
	9=>array("district_name" => "Huyện Trảng Bàng", "be_id" => "674", "main" => 0, 'sendo_id' => 599, 'code' => 712),
	), 
	53 => array(
	1=>array("district_name" => "Thành phố Thái Bình", "be_id" => "267", "main" => 1, 'sendo_id' => 627, 'code' => 336),
	2=>array("district_name" => "Huyện Đông Hưng", "be_id" => "268", "main" => 0, 'sendo_id' => 630, 'code' => 340),
	3=>array("district_name" => "Huyện Hưng Hà", "be_id" => "269", "main" => 0, 'sendo_id' => 629, 'code' => 339),
	4=>array("district_name" => "Huyện Kiến Xương", "be_id" => "270", "main" => 0, 'sendo_id' => 632, 'code' => 343),
	5=>array("district_name" => "Huyện Quỳnh Phụ", "be_id" => "271", "main" => 0, 'sendo_id' => 628, 'code' => 338),
	6=>array("district_name" => "Huyện Thái Thụy", "be_id" => "272", "main" => 0, 'sendo_id' => 634, 'code' => 341),
	7=>array("district_name" => "Huyện Tiền Hải", "be_id" => "273", "main" => 0, 'sendo_id' => 633, 'code' => 342),
	8=>array("district_name" => "Huyện Vũ Thư", "be_id" => "274", "main" => 0, 'sendo_id' => 631, 'code' => 344),
	), 
	54 => array(
	1=>array("district_name" => "Thành phố Thái Nguyên", "be_id" => "275", "main" => 1, 'sendo_id' => 635, 'code' => 164),
	2=>array("district_name" => "Thị xã Sông Công", "be_id" => "283", "main" => 0, 'sendo_id' => 636, 'code' => 165),
	3=>array("district_name" => "Huyện Phổ Yên", "be_id" => "277", "main" => 0, 'sendo_id' => 643, 'code' => 172),
	4=>array("district_name" => "Huyện Phú Bình", "be_id" => "279", "main" => 0, 'sendo_id' => 642, 'code' => 173),
	5=>array("district_name" => "Huyện Đồng Hỷ", "be_id" => "280", "main" => 0, 'sendo_id' => 641, 'code' => 169),
	6=>array("district_name" => "Huyện Võ Nhai", "be_id" => "276", "main" => 0, 'sendo_id' => 639, 'code' => 170),
	7=>array("district_name" => "Huyện Định Hóa", "be_id" => "281", "main" => 0, 'sendo_id' => 637, 'code' => 167),
	8=>array("district_name" => "Huyện Đại Từ", "be_id" => "282", "main" => 0, 'sendo_id' => 640, 'code' => 171),
	9=>array("district_name" => "Huyện Phú Lương", "be_id" => "278", "main" => 0, 'sendo_id' => 638, 'code' => 168),
	), 
	55 => array(
	1=>array("district_name" => "Thành phố Thanh Hóa", "be_id" => "284", "main" => 1, 'sendo_id' => 600, 'code' => 380),
	2=>array("district_name" => "Thị xã Bỉm Sơn", "be_id" => "285", "main" => 0, 'sendo_id' => 601, 'code' => 381),
	3=>array("district_name" => "Thị xã Sầm Sơn", "be_id" => "286", "main" => 0, 'sendo_id' => 602, 'code' => 382),
	4=>array("district_name" => "Huyện Bá Thước", "be_id" => "287", "main" => 0, 'sendo_id' => 606, 'code' => 386),
	5=>array("district_name" => "Huyện Cẩm Thủy", "be_id" => "288", "main" => 0, 'sendo_id' => 613, 'code' => 390),
	6=>array("district_name" => "Huyện Đông Sơn", "be_id" => "289", "main" => 0, 'sendo_id' => 626, 'code' => 405),
	7=>array("district_name" => "Huyện Hà Trung", "be_id" => "290", "main" => 0, 'sendo_id' => 619, 'code' => 392),
	8=>array("district_name" => "Huyện Hậu Lộc", "be_id" => "291", "main" => 0, 'sendo_id' => 622, 'code' => 400),
	9=>array("district_name" => "Huyện Hoằng Hóa", "be_id" => "292", "main" => 0, 'sendo_id' => 620, 'code' => 399),
	10=>array("district_name" => "Huyện Lang Chánh", "be_id" => "293", "main" => 0, 'sendo_id' => 610, 'code' => 388),
	11=>array("district_name" => "Huyện Mường Lát", "be_id" => "294", "main" => 0, 'sendo_id' => 605, 'code' => 384),
	12=>array("district_name" => "Huyện Nga Sơn", "be_id" => "295", "main" => 0, 'sendo_id' => 621, 'code' => 401),
	13=>array("district_name" => "Huyện Ngọc Lặc", "be_id" => "296", "main" => 0, 'sendo_id' => 611, 'code' => 389),
	14=>array("district_name" => "Huyện Như Thanh", "be_id" => "297", "main" => 0, 'sendo_id' => 609, 'code' => 403),
	15=>array("district_name" => "Huyện Như Xuan", "be_id" => "298", "main" => 0, 'sendo_id' => 608, 'code' => 402),
	16=>array("district_name" => "Huyện Nông Cống", "be_id" => "299", "main" => 0, 'sendo_id' => 618, 'code' => 404),
	17=>array("district_name" => "Huyện Quan Hóa", "be_id" => "300", "main" => 0, 'sendo_id' => 603, 'code' => 385),
	18=>array("district_name" => "Huyện Quan Sơn", "be_id" => "301", "main" => 0, 'sendo_id' => 604, 'code' => 387),
	19=>array("district_name" => "Huyện Quảng Xương", "be_id" => "302", "main" => 0, 'sendo_id' => 625, 'code' => 406),
	20=>array("district_name" => "Huyện Thạch Thành", "be_id" => "303", "main" => 0, 'sendo_id' => 612, 'code' => 391),
	21=>array("district_name" => "Huyện Thiệu Hóa", "be_id" => "304", "main" => 0, 'sendo_id' => 616, 'code' => 398),
	22=>array("district_name" => "Huyện Thọ Xuân", "be_id" => "305", "main" => 0, 'sendo_id' => 614, 'code' => 395),
	23=>array("district_name" => "Huyện Thường Xuân", "be_id" => "306", "main" => 0, 'sendo_id' => 607, 'code' => 396),
	24=>array("district_name" => "Huyện Tĩnh Gia", "be_id" => "307", "main" => 0, 'sendo_id' => 623, 'code' => 407),
	25=>array("district_name" => "Huyện Triệu Sơn", "be_id" => "308", "main" => 0, 'sendo_id' => 617, 'code' => 397),
	26=>array("district_name" => "Huyện Vĩnh Lộc", "be_id" => "309", "main" => 0, 'sendo_id' => 615, 'code' => 393),
	27=>array("district_name" => "Huyện Yên Định", "be_id" => "310", "main" => 0, 'sendo_id' => 624, 'code' => 394),
	), 
	56 => array(
	1=>array("district_name" => "Thành phố Huế", "be_id" => "539", "main" => 1, 'sendo_id' => 644, 'code' => 474),
	2=>array("district_name" => "Thị xã Hương Thủy", "be_id" => "540", "main" => 0, 'sendo_id' => 649, 'code' => 479),
	3=>array("district_name" => "Huyện A Lưới", "be_id" => "541", "main" => 0, 'sendo_id' => 652, 'code' => 481),
	4=>array("district_name" => "Huyện Hương Trà", "be_id" => "542", "main" => 0, 'sendo_id' => 647, 'code' => 480),
	5=>array("district_name" => "Huyện Nam Đông", "be_id" => "543", "main" => 0, 'sendo_id' => 651, 'code' => 483),
	6=>array("district_name" => "Huyện Phong Điền", "be_id" => "544", "main" => 0, 'sendo_id' => 645, 'code' => 476),
	7=>array("district_name" => "Huyện Phú Lộc", "be_id" => "545", "main" => 0, 'sendo_id' => 650, 'code' => 482),
	8=>array("district_name" => "Huyện Phú Vang", "be_id" => "546", "main" => 0, 'sendo_id' => 648, 'code' => 478),
	9=>array("district_name" => "Huyện Quảng Điền", "be_id" => "547", "main" => 0, 'sendo_id' => 646, 'code' => 477),
	), 
	57 => array(
	1=>array("district_name" => "Thành phố Mỹ Tho", "be_id" => "675", "main" => 1, 'sendo_id' => 653, 'code' => 815),
	2=>array("district_name" => "Thị xã Gò Công", "be_id" => "676", "main" => 0, 'sendo_id' => 654, 'code' => 816),
	3=>array("district_name" => "Huyện Cái Bè", "be_id" => "677", "main" => 0, 'sendo_id' => 655, 'code' => 819),
	4=>array("district_name" => "Huyện Gò Công Đông", "be_id" => "681", "main" => 0, 'sendo_id' => 659, 'code' => 824),
	5=>array("district_name" => "Huyện Gò Công Tây", "be_id" => "682", "main" => 0, 'sendo_id' => 660, 'code' => 823),
	6=>array("district_name" => "Huyện Chợ Gạo", "be_id" => "680", "main" => 0, 'sendo_id' => 658, 'code' => 822),
	7=>array("district_name" => "Huyện Châu Thành", "be_id" => "679", "main" => 0, 'sendo_id' => 657, 'code' => 821),
	8=>array("district_name" => "Huyện Tân Phước", "be_id" => "684", "main" => 0, 'sendo_id' => 661, 'code' => 818),
	9=>array("district_name" => "Huyện Cai Lậy", "be_id" => "678", "main" => 0, 'sendo_id' => 656, 'code' => 820),
	10=>array("district_name" => "Huyện Tân Phú Đông", "be_id" => "683", "main" => 0, 'sendo_id' => 720, 'code' => 825),
	), 
	58 => array(
	1=>array("district_name" => "Thành phố Trà Vinh", "be_id" => "685", "main" => 1, 'sendo_id' => 662, 'code' => 842),
	2=>array("district_name" => "Huyện Càng Long", "be_id" => "686", "main" => 0, 'sendo_id' => 663, 'code' => 844),
	3=>array("district_name" => "Huyện Châu Thành", "be_id" => "689", "main" => 0, 'sendo_id' => 666, 'code' => 847),
	4=>array("district_name" => "Huyện Cầu Kè", "be_id" => "687", "main" => 0, 'sendo_id' => 664, 'code' => 845),
	5=>array("district_name" => "Huyện Tiểu Cần", "be_id" => "691", "main" => 0, 'sendo_id' => 665, 'code' => 846),
	6=>array("district_name" => "Huyện Cầu Ngang", "be_id" => "688", "main" => 0, 'sendo_id' => 668, 'code' => 848),
	7=>array("district_name" => "Huyện Trà Cú", "be_id" => "692", "main" => 0, 'sendo_id' => 667, 'code' => 849),
	8=>array("district_name" => "Huyện Duyên Hải", "be_id" => "690", "main" => 0, 'sendo_id' => 669, 'code' => 850),
	), 
	59 => array(
	1=>array("district_name" => "Thị xã Tuyên Quang", "be_id" => "311", "main" => 0, 'sendo_id' => 670, 'code' => 70),
	2=>array("district_name" => "Huyện Chiêm Hóa", "be_id" => "312", "main" => 0, 'sendo_id' => 672, 'code' => 73),
	3=>array("district_name" => "Huyện Hàm Yên", "be_id" => "313", "main" => 0, 'sendo_id' => 673, 'code' => 74),
	4=>array("district_name" => "Huyện Na Hang", "be_id" => "314", "main" => 0, 'sendo_id' => 671, 'code' => 72),
	5=>array("district_name" => "Huyện Sơn Dương", "be_id" => "315", "main" => 0, 'sendo_id' => 675, 'code' => 76),
	6=>array("district_name" => "Huyện Yên Sơn", "be_id" => "316", "main" => 0, 'sendo_id' => 674, 'code' => 75),
	), 
	60 => array(
	1=>array("district_name" => "Thành phố Vĩnh Long", "be_id" => "693", "main" => 1, 'sendo_id' => 35, 'code' => 855),
	2=>array("district_name" => "Huyện Bình Minh", "be_id" => "694", "main" => 0, 'sendo_id' => 38, 'code' => 861),
	3=>array("district_name" => "Huyện Bình Tân", "be_id" => "695", "main" => 0, 'sendo_id' => 739, 'code' => 863),
	4=>array("district_name" => "Huyện Long Hồ", "be_id" => "696", "main" => 0, 'sendo_id' => 36, 'code' => 857),
	5=>array("district_name" => "Huyện Mang Thít", "be_id" => "697", "main" => 0, 'sendo_id' => 37, 'code' => 858),
	6=>array("district_name" => "Huyện Tam Bình", "be_id" => "698", "main" => 0, 'sendo_id' => 40, 'code' => 860),
	7=>array("district_name" => "Huyện Trà Ôn", "be_id" => "699", "main" => 0, 'sendo_id' => 39, 'code' => 862),
	8=>array("district_name" => "Huyện Vũng Liêm", "be_id" => "700", "main" => 0, 'sendo_id' => 41, 'code' => 859),
	), 
	61 => array(
	1=>array("district_name" => "Thành phố Vĩnh Yên", "be_id" => "317", "main" => 1, 'sendo_id' => 685, 'code' => 243),
	2=>array("district_name" => "Thị xã Phúc Yên", "be_id" => "318", "main" => 0, 'sendo_id' => 692, 'code' => 244),
	3=>array("district_name" => "Huyện Bình Xuyên", "be_id" => "319", "main" => 0, 'sendo_id' => 690, 'code' => 249),
	4=>array("district_name" => "Huyện Lập Thạch", "be_id" => "320", "main" => 0, 'sendo_id' => 687, 'code' => 246),
	5=>array("district_name" => "Huyện Sông Lô", "be_id" => "321", "main" => 0, 'sendo_id' => 735, 'code' => 253),
	6=>array("district_name" => "Huyện Tam Dương", "be_id" => "322", "main" => 0, 'sendo_id' => 686, 'code' => 247),
	7=>array("district_name" => "Huyện Tam Đảo", "be_id" => "323", "main" => 0, 'sendo_id' => 693, 'code' => 248),
	8=>array("district_name" => "Huyện Vĩnh Tường", "be_id" => "324", "main" => 0, 'sendo_id' => 688, 'code' => 252),
	9=>array("district_name" => "Huyện Yên Lạc", "be_id" => "325", "main" => 0, 'sendo_id' => 689, 'code' => 251),
	), 
	62 => array(
	1=>array("district_name" => "Thành phố Yên Bái", "be_id" => "326", "main" => 1, 'sendo_id' => 676, 'code' => 132),
	2=>array("district_name" => "Thị xã Nghĩa Lộ", "be_id" => "327", "main" => 0, 'sendo_id' => 677, 'code' => 133),
	3=>array("district_name" => "Huyện Lục Yên", "be_id" => "328", "main" => 0, 'sendo_id' => 684, 'code' => 135),
	4=>array("district_name" => "Huyện Mù Cang Chải", "be_id" => "329", "main" => 0, 'sendo_id' => 680, 'code' => 137),
	5=>array("district_name" => "Huyện Trấn Yên", "be_id" => "330", "main" => 0, 'sendo_id' => 682, 'code' => 138),
	6=>array("district_name" => "Huyện Trạm Tấu", "be_id" => "331", "main" => 0, 'sendo_id' => 683, 'code' => 139),
	7=>array("district_name" => "Huyện Văn Chấn", "be_id" => "332", "main" => 0, 'sendo_id' => 681, 'code' => 140),
	8=>array("district_name" => "Huyện Văn Yên", "be_id" => "333", "main" => 0, 'sendo_id' => 678, 'code' => 136),
	9=>array("district_name" => "Huyện Yên Bình", "be_id" => "334", "main" => 0, 'sendo_id' => 679, 'code' => 141),
	),
	63 => array(
	1=>array("district_name" => "Thị xã Gia Nghĩa", "be_id" => "485", "main" => 0, 'sendo_id' => 204, 'code' => 660),
	2=>array("district_name" => "Huyện Cư Jút", "be_id" => "486", "main" => 0, 'sendo_id' => 206, 'code' => 662),
	3=>array("district_name" => "Huyện Đắk Glong", "be_id" => "487", "main" => 0, 'sendo_id' => 208, 'code' => 661),
	4=>array("district_name" => "Huyện Đắk Mil", "be_id" => "488", "main" => 0, 'sendo_id' => 209, 'code' => 663),
	5=>array("district_name" => "Huyện Đắk R'Lấp", "be_id" => "489", "main" => 0, 'sendo_id' => 210, 'code' => 666),
	6=>array("district_name" => "Huyện Đắk Song", "be_id" => "490", "main" => 0, 'sendo_id' => 205, 'code' => 665),
	7=>array("district_name" => "Huyện Krông Nô", "be_id" => "491", "main" => 0, 'sendo_id' => 207, 'code' => 664),
	8=>array("district_name" => "Huyện Tuy Đức", "be_id" => "492", "main" => 0, 'sendo_id' => 718, 'code' => 667)
	),
	64 => array(
	1=>array("district_name" => "Thị xã Mường Lay", "be_id" => "110", "main" => 0, 'sendo_id' => 695, 'code' => 95),
	2=>array("district_name" => "Huyện Điện Biên", "be_id" => "111", "main" => 0, 'sendo_id' => 701, 'code' => 100),
	3=>array("district_name" => "Huyện Điện Biên Đông", "be_id" => "112", "main" => 0, 'sendo_id' => 702, 'code' => 101),
	4=>array("district_name" => "Huyện Mường Ảng", "be_id" => "113", "main" => 0, 'sendo_id' => 698, 'code' => 102),
	5=>array("district_name" => "Huyện Mường Chà", "be_id" => "114", "main" => 0, 'sendo_id' => 696, 'code' => 97),
	6=>array("district_name" => "Huyện Mường Nhé", "be_id" => "115", "main" => 0, 'sendo_id' => 697, 'code' => 96),
	7=>array("district_name" => "Huyện Tủa Chùa", "be_id" => "116", "main" => 0, 'sendo_id' => 700, 'code' => 98),
	8=>array("district_name" => "Huyện Tuần Giáo", "be_id" => "117", "main" => 0, 'sendo_id' => 699, 'code' => 99)
	),
	65 => array(
	1=>array("district_name" => "Thành phố Vị Thanh", "be_id" => "533", "main" => 1, 'sendo_id' => 706, 'code' => 930),
	2=>array("district_name" => "Thị xã Ngã Bảy", "be_id" => "532", "main" => 0, 'sendo_id' => 707, 'code' => 931),
	3=>array("district_name" => "Huyện Châu Thành", "be_id" => "534", "main" => 0, 'sendo_id' => 711, 'code' => 933),
	4=>array("district_name" => "Huyện Châu Thành A", "be_id" => "535", "main" => 0, 'sendo_id' => 712, 'code' => 932),
	5=>array("district_name" => "Huyện Long Mỹ", "be_id" => "536", "main" => 0, 'sendo_id' => 709, 'code' => 936),
	6=>array("district_name" => "Huyện Phụng Hiệp", "be_id" => "537", "main" => 0, 'sendo_id' => 710, 'code' => 934),
	7=>array("district_name" => "Huyện Vị Thủy", "be_id" => "538", "main" => 0, 'sendo_id' => 708, 'code' => 935)
	)
);